Repository microsoft/WindowsAppSDK, pull requests merged in 2020-07, with the labels that each got.

#103 User/jonwis/build workflow
  .github/workflows/build.yml
Labels: infrastructure, needs-triage :mag:

#104 Minor post-creation cleanup
  .editorconfig
  DevCmd.cmd
  docs/contributor-guide.md
Labels: needs-triage :mag:

#118 Exclude specs and docs for builds
  .github/workflows/build.yml
Labels: infrastructure

#115 roadmap update with initial focus areas
  docs/roadmap.md
Labels: needs-triage :mag:

#122 Fix Rust typo in readme
  docs/README.md
Labels: needs-triage :mag:

#116 Add status badges to readme
  README.md
Labels: infrastructure

#133 Triage.md
  docs/images/proposal-flow.png
  docs/triage.md
Labels: needs-triage :mag:
