Repository microsoft/WindowsAppSDK, pull requests merged in 2021-08, with the labels that each got.

#1160 Set DefaultLanguage
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.C.props
Labels: needs-triage :mag:

#1159 Adding an explicit reference to resources winmd causes invalid appxmanifest.xml build error
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
Labels: needs-triage :mag:

#1152 Move PushNotifications overrides out of GenerateDynamicDependenciesOverrides.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  tools/GenerateDynamicDependencyOverrides.ps1
  tools/GeneratePushNotificationsOverrides.ps1
Labels: area-DynamicDependencies, area-Infrastructure, area-Notifications, needs-triage :mag:

#1142 Adding PowerNotification APIs
  WindowsAppSDK.sln
  build/NuSpecs/AppxManifest.xml
  dev/PowerNotifications/PowerNotifications.cpp
  dev/PowerNotifications/PowerNotifications.h
  dev/PowerNotifications/PowerNotifications.idl
  dev/PowerNotifications/PowerNotifications.vcxitems
  dev/WindowsAppSDK_DLL/WindowsAppSDK_DLL.vcxproj
  dev/WindowsAppSDK_DLL/packages.config
  test/DynamicDependency/data/Microsoft.WindowsAppSDK.Framework/appxmanifest.xml
  test/PowerNotifications/APITests.cpp
  test/PowerNotifications/FunctionalTests.cpp
  test/PowerNotifications/PowerNotifications-AppxManifest.xml
  test/PowerNotifications/PowerNotifications.vcxproj
  test/PowerNotifications/PowerNotifications.vcxproj.filters
  test/PowerNotifications/packages.config
  test/PowerNotifications/pch.cpp
  test/PowerNotifications/pch.h
Labels: needs-triage :mag:

#1167 Update version for experimental
  build/WindowsAppSDK-Versions.yml
Labels: needs-triage :mag:

#1169 User/ericjohnson327/transform fusion manifest
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/TransformAppxManifest.xslt
Labels: needs-triage :mag:

#1165 TerminalVelocity + DynamicDependency [Get]GenerationId()
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  dev/Common/TerminalVelocityFeatures-DynamicDependency.h
  dev/Common/TerminalVelocityFeatures-DynamicDependency.xml
  dev/DynamicDependency/DynamicDependency.vcxitems
  dev/DynamicDependency/M.AM.DD.PackageDependency.cpp
  dev/DynamicDependency/M.AM.DD.PackageDependency.h
  dev/DynamicDependency/M.AM.DynamicDependency.idl
  dev/DynamicDependency/MsixDynamicDependency.cpp
  dev/DynamicDependency/MsixDynamicDependency.h
  dev/WindowsAppSDK_DLL/WindowsAppSDK.def
  dev/WindowsAppSDK_DLL/WindowsAppSDK_DLL.vcxproj
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.h
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.h
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.cmd
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
  tools/TerminalVelocity/TerminalVelocityFeatures.xsd
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-Experimental.cs
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-Experimental.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-NoNamespace-Experimental.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-NoNamespace-Preview.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-NoNamespace-Stable.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-NoNamespace-WindowsInbox.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-Preview.cs
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-Preview.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-Stable.cs
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-Stable.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-WindowsInbox.cs
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test-WindowsInbox.h
  tools/TerminalVelocity/test/TerminalVelocityFeatures-Test.xml
Labels: area-DynamicDependencies, area-Infrastructure

#1183 Rename preview VSIX to experimental (#1178)
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
Labels: needs-triage :mag:

#1135 Add spec for MSIX Packages
  specs/Deployment/MSIXPackageVersioning.md
  specs/Deployment/MSIXPackages.md
Labels: needs-triage :mag:, area-Infrastructure

#1164 Put objs under common obj folder
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/EnsureOutputLayout.props
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/ManagedTest.csproj
Labels: area-Infrastructure

#1187 remove VSIX extension pack
  dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
Labels: needs-triage :mag:

#1190 Use WinAppSDK's own Helix queues instead of the WinUI/XAML queues
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#1149 Adding BuildAndPublishInsights.yml to CI.yml so that the headers and libs are included in the CI builds.
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndPublishInsights-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource.sln
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource.vcxproj
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource.vcxproj.filters
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource/generaterc.ps1
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource/resource.h
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResource/resource.templ
  dev/WindowsAppSDKInsightsResource/WindowsAppSDKInsightsResourceLib/packages.config
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsights.h
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsights.cpp
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsightsLib.vcxproj
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsightsLib.vcxproj.filters
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/packages.config
  dev/WindowsAppSDK_Insights/nuget.config
Labels: needs-triage :mag:

#1192 Fix two VSIX issues stemming from Reunion -> WindowsAppSDK rename
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/pch.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/pch.h
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/pch.h
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/pch.h
Labels: needs-triage :mag:

#1197 Cherrypick from #1192
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/pch.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/pch.h
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/pch.h
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/pch.h
Labels: needs-triage :mag:

#1191 User/aeloros/feedback
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/ExtensionContract.h
  dev/AppLifecycle/FileActivatedEventArgs.h
  dev/AppLifecycle/LaunchActivatedEventArgs.h
  dev/AppLifecycle/ProtocolActivatedEventArgs.h
  dev/AppLifecycle/StartupActivatedEventArgs.h
Labels: needs-triage :mag:

#1189 Git checkin-to-main policy
  docs/Coding-Guidelines.md
Labels: needs-triage :mag:, area-Infrastructure

#1193 Add FrameworkUdk dll to our test framework package
  test/DynamicDependency/data/Microsoft.WindowsAppSDK.Framework/Makefile.mak
Labels: needs-triage :mag:, area-Infrastructure

#1194 Added test Singleton MSIX package
  WindowsAppSDK.sln
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/Assets/SplashScreen.png
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/Assets/Square150x150Logo.png
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/Assets/Square44x44Logo.png
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/Assets/Wide310x150Logo.png
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/Assets/logo.png
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/Makefile.mak
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/WindowsAppSDK.Test.Singleton.Msix.vcxproj
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/WindowsAppSDK.Test.Singleton.Msix.vcxproj.filters
  test/DynamicDependency/data/WindowsAppSDK.Test.Singleton.Msix/appxmanifest.xml
  test/inc/WindowsAppSDK.Test.Bootstrap.h
  test/inc/WindowsAppSDK.Test.Metadata.h
  test/inc/WindowsAppSDK.Test.Package.h
Labels: needs-triage :mag:, area-Infrastructure

#1185 Samples repo and Docs links
  README.md
  docs/contributor-guide.md
Labels: needs-triage :mag:

#1220 Run MRTCore UnpackagedTests in build pipeline and Helix
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
  build/build-mrt.yml
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
Labels: needs-triage :mag:

#1131 Adding namespace
  WindowsAppSDK.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.System.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Microsoft.Process.Environment/EnvironmentManager.idl
  dev/Microsoft.Process.Environment/Microsoft.Process.Environment.vcxitems
  dev/Microsoft.Process.Environment/Microsoft.Windows.System.EnvironmentManager.cpp
  dev/Microsoft.Process.Environment/Microsoft.Windows.System.EnvironmentManager.h
  dev/WindowsAppSDK_DLL/WindowsAppSDK_DLL.vcxproj
  specs/AppLifecycle/EnvironmentVariables/AppLifecycle Environment Variables.md
Labels: needs-triage :mag:

#1223 Change MRT test names
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
  build/build-mrt.yml
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj.filters
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.runsettings
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/MRTCore/mrt/MrtCore.sln
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj.filters
Labels: needs-triage :mag:

#1234 hide ERROR_MRM_NAMED_RESOURCE_NOT_FOUND
  dev/MRTCore/mrt/Core/src/MRM.cpp
Labels: needs-triage :mag:

#1251 Pass ResourceContext to ResourceCandidate
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceCandidate.cpp
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceCandidate.h
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceMap.cpp
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/UnitTest.cs
Labels: needs-triage :mag:

#1243 MRT core is restoring the packages referenced in WindowsAppSDKInsight…
  build/ProjectReunion-BuildFoundation.yml
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsightsLib.vcxproj
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/packages.config
  dev/WindowsAppSDK_Insights/nuget.config
  dev/WindowsAppSDK_Insights/packages.config
Labels: needs-triage :mag:

#1064 Add unpackaged support to PushNotifications spec
  specs/PushNotifications/PushNotifications-spec.md
Labels: needs-triage :mag:

#1026 Commonize Hybrid CRT support
  Directory.Build.props
  HybridCRT.props
  dev/Detours/Detours.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependency.DataStore.ProxyStub.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/MrtCoreManagedTests.runsettings
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/WindowsAppSDK_BootstrapDLL/WindowsAppSDK_BootstrapDLL.vcxproj
  dev/WindowsAppSDK_DLL/WindowsAppSDK_DLL.vcxproj
Labels: needs-triage :mag:, area-Infrastructure

#1259 add tests in ManagedTest to UnpackagedTests
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/TestCommon/CommonTestCode.cs
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/UnitTest.cs
Labels: needs-triage :mag:

#1254 Adding entries for PowerNotifications WinMD file
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/Intellisense/Microsoft.Windows.System.Power.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Labels: needs-triage :mag:

#1260 Updating FrameworkUDK Nuget
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
  dev/WindowsAppSDK_DLL/WindowsAppSDK_DLL.vcxproj
  dev/WindowsAppSDK_DLL/packages.config
Labels: needs-triage :mag:

#1219 Remove WinMDs from lib/native directory and update VSIX for merging WAS packages
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  build/publish-mrt.yml
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
Labels: needs-triage :mag:

#1267 Use public pool and PAT for publishing public symbols
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#1268 Moving from the static library based solution for telemetry to a head…
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndPublishInsights-Steps.yml
  build/CopyFilesToStagingDir.ps1
  build/ProjectReunion-BuildFoundation.yml
  dev/WindowsAppSDK_DLL/WindowsAppSDK_DLL.vcxproj
  dev/WindowsAppSDK_Insights/WindowsAppRuntimeInsights.h
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsights.h
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsights.cpp
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsightsLib.vcxproj
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/WindowsAppSDKInsightsLib.vcxproj.filters
  dev/WindowsAppSDK_Insights/WindowsAppSDKInsightsLib/packages.config
Labels: needs-triage :mag:

#1279 Include WIL before referencing WindowsAppRuntimeInsights.h
  dev/WindowsAppSDK_Insights/WindowsAppRuntimeInsights.h
Labels: needs-triage :mag:

#1271 Install frameworkudk for LRP
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Makefile.mak
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/PushNotificationsLongRunningTask.Msix.vcxproj
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/PushNotificationsLongRunningTask.Msix.vcxproj.filters
Labels: needs-triage :mag:, area-Notifications

#1298 Add HybridCRT docs
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/GitCheckinToMainPolicy.md
  docs/Coding-Guidelines/HybridCRT.md
  docs/Coding-Guidelines/Languages-CPP.md
  docs/Coding-Guidelines/Languages-Markdown.md
Labels: needs-triage :mag:, area-Infrastructure

#1282 Moved Bootstrap dll to fix VS/AnyCPU projects
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage :mag:, area-DynamicDependencies

#1281 User/default/vsix split
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/Cpp/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/LICENSE
  dev/VSIX/Extension/Cpp/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/WindowsAppSDK.Cpp.Extension.csproj
  dev/VSIX/Extension/Cs/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/LICENSE
  dev/VSIX/Extension/Cs/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/WindowsAppSDK.Cs.Extension.csproj
  dev/VSIX/Extension/Directory.Build.targets
  dev/VSIX/Extension/Original/LICENSE
  dev/VSIX/Extension/Original/WindowsAppSDK.Extension.csproj
  dev/VSIX/Extension/Original/source.extension.vsixmanifest
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
  dev/VSIX/WindowsAppSDK.Extension.sln
Labels: needs-triage :mag:

#1288 C# Projection for PowerNotifications
  WindowsAppSDK.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/Intellisense/Microsoft.Windows.System.Power.Projection.xml
  dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
Labels: needs-triage :mag:

#1308 set rollForward value to latestMajor
  dev/MRTCore/global.json
Labels: needs-triage :mag:

#1306 Guide users to the WinUI repo
  docs/contributor-guide.md
Labels: needs-triage :mag:

#1284 Spec updates for GenerationId and Bootstrap C# API
  specs/dynamicdependencies/DynamicDependencies.md
  specs/dynamicdependencies/sample-b.1.md
Labels: needs-triage :mag:, area-DynamicDependencies

#1333 User/drustheaxe/undo bootstrap move
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: bug, needs-triage :mag:, area-DynamicDependencies

#1332 Fix MRT Core binary vulcanization for API scanning.
  ApiScan.Cpp.props
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
Labels: needs-triage :mag:

#1274 Add Bootstrap C# API. Spec Bootstrap C# and get GenerationId (Flat-C/WinRT) APIs
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.targets
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Bootstrap.cs
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Microsoft.WindowsAppRuntime.Bootstrap.Net.csproj
  dev/DynamicDependency/API/DataStore.cpp
  dev/DynamicDependency/API/DataStore.h
  dev/DynamicDependency/API/DynamicDependency.vcxitems
  dev/DynamicDependency/API/DynamicDependency.vcxitems.filters
  dev/DynamicDependency/API/M.AM.Converters.h
  dev/DynamicDependency/API/M.AM.DD.AddPackageDependencyOptions.cpp
  dev/DynamicDependency/API/M.AM.DD.AddPackageDependencyOptions.h
  dev/DynamicDependency/API/M.AM.DD.CreatePackageDependencyOptions.cpp
  dev/DynamicDependency/API/M.AM.DD.CreatePackageDependencyOptions.h
  dev/DynamicDependency/API/M.AM.DD.PackageDependency.cpp
  dev/DynamicDependency/API/M.AM.DD.PackageDependency.h
  dev/DynamicDependency/API/M.AM.DD.PackageDependencyContext.cpp
  dev/DynamicDependency/API/M.AM.DD.PackageDependencyContext.h
  dev/DynamicDependency/API/M.AM.DD.PackageDependencyRank.cpp
  dev/DynamicDependency/API/M.AM.DD.PackageDependencyRank.h
  dev/DynamicDependency/API/M.AM.DynamicDependency.idl
  dev/DynamicDependency/API/MddCore.Architecture.h
  dev/DynamicDependency/API/MddDetourPackageGraph.cpp
  dev/DynamicDependency/API/MddDetourPackageGraph.h
  dev/DynamicDependency/API/MddLifetimeManagement.cpp
  dev/DynamicDependency/API/MddLifetimeManagement.h
  dev/DynamicDependency/API/MddLifetimeManagementTest.h
  dev/DynamicDependency/API/MddWinRT.cpp
  dev/DynamicDependency/API/MddWinRT.h
  dev/DynamicDependency/API/MsixDynamicDependency.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/DynamicDependency/API/PackageDependency.cpp
  dev/DynamicDependency/API/PackageDependency.h
  dev/DynamicDependency/API/PackageDependencyManager.cpp
  dev/DynamicDependency/API/PackageDependencyManager.h
  dev/DynamicDependency/API/PackageGraph.cpp
  dev/DynamicDependency/API/PackageGraph.h
  dev/DynamicDependency/API/PackageGraphManager.cpp
  dev/DynamicDependency/API/PackageGraphManager.h
  dev/DynamicDependency/API/PackageGraphNode.cpp
  dev/DynamicDependency/API/PackageGraphNode.h
  dev/DynamicDependency/API/PackageId.h
  dev/DynamicDependency/API/PackageInfo.h
  dev/DynamicDependency/API/WinRTInprocModule.h
  dev/DynamicDependency/API/WinRTModuleManager.cpp
  dev/DynamicDependency/API/WinRTModuleManager.h
  dev/DynamicDependency/API/WinRTPackage.cpp
  dev/DynamicDependency/API/WinRTPackage.h
  dev/DynamicDependency/API/appmodel_msixdynamicdependency.h
  dev/DynamicDependency/API/pch.h
  dev/DynamicDependency/API/utf8.h
  dev/DynamicDependency/API/wil_msixdynamicdependency.h
  dev/DynamicDependency/API/winrt_msixdynamicdepednency.h
  dev/DynamicDependency/API/winrt_namespaces.h
  dev/UndockedRegFreeWinRT/catalog.cpp
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
Labels: area-DynamicDependencies

#1342 Fix ".Experimental" VSIX renaming
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/Directory.Build.targets
Labels: needs-triage :mag:

#1344 Fix Installer singleton support. Don't try to copy obsolete .pri files to the TRansport package
  build/NuSpecs/build-nupkg.ps1
  installer/dev/windowsappruntime_definitions.h
Labels: needs-triage :mag:, area-Infrastructure, area-Installer

#1341 Lay foundation for VSIX localization and re-enable Single-project MSIX Packaging templates
  .gitignore
  dev/VSIX/Directory.Build.props
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/Cpp/Common/VSPackage.resx
  dev/VSIX/Extension/Cpp/Dev16/ExtensionPack.vsext
  dev/VSIX/Extension/Cpp/Dev16/VSPackage.cs
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/ExtensionPack.vsext
  dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/VSPackage.cs
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cpp/LICENSE
  dev/VSIX/Extension/Cs/Common/VSPackage.resx
  dev/VSIX/Extension/Cs/Dev16/ExtensionPack.vsext
  dev/VSIX/Extension/Cs/Dev16/VSPackage.cs
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/ExtensionPack.vsext
  dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/VSPackage.cs
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/LICENSE
  dev/VSIX/Extension/Directory.Build.targets
  dev/VSIX/Extension/Original/WindowsAppSDK.Extension.csproj
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
  dev/VSIX/WinUI3.ico
  dev/VSIX/WindowsAppSDK.Extension.sln
Labels: needs-triage :mag:
