Repository microsoft/WindowsAppSDK, pull requests merged in 2021-05, with the labels that each got.

#771 In C#/.NET projects, pick up image and resw files for PRI generation.
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#770 Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 4)
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#788 Publish stub intellisense files into transport package
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/NuSpecs/Intellisense/Microsoft.ApplicationModel.Activation.xml
  build/NuSpecs/Intellisense/Microsoft.ApplicationModel.DynamicDependency.xml
  build/publish-mrt.yml
  dev/MRTCore/packaging/Intellisense/Microsoft.ApplicationModel.Resources.Projection.xml
  dev/MRTCore/packaging/Intellisense/Microsoft.ApplicationModel.Resources.xml
Labels: needs-triage :mag:

#778 Debugging - MRT overwriting/removing previous include\* when published MRM.h?
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/ProjectReunion-Nuget-Native.C.props
  build/NuSpecs/ProjectReunion-Nuget-Native.WinRt.props
  build/NuSpecs/ProjectReunion-Nuget-Native.props
  build/publish-mrt.yml
  dev/Common/AppModel.Identity.h
  dev/DynamicDependency/MddLifetimeManagement.cpp
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.h
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/Test_LifetimeManagement.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest.xml
  test/TestApps/AppLifecycleTestApp/main.cpp
  test/inc/ProjectReunion.Test.Bootstrap.h
  tools/GenerateDynamicDependencyOverrides.ps1
Labels: area-DynamicDependencies, area-Infrastructure, needs-triage :mag:

#793 Update appxmanifest.xml inproc servers snippet
  build/AzurePipelinesTemplates/ProjectReunion-PublishProjectOutput-Steps.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
Labels: area-DynamicDependencies, area-Infrastructure, needs-triage :mag:

#796 Target MRTCore projection dll to any CPU
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#799 cherrypick: Target MRTCore projection dll to any CPU
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#798 Update MddBootstrapInitialize docs
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.h
  specs/dynamicdependencies/DynamicDependencies.md
Labels: area-DynamicDependencies, needs-triage :mag:

#804 Minor cleanups
  dev/DynamicDependency/MddLifetimeManagement.cpp
  dev/DynamicDependency/PackageGraphManager.cpp
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/winmain.cpp
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/winmain.cpp
  test/DynamicDependency/Test_Win32/TestPackages.cpp
  test/DynamicDependency/Test_WinRT/Create_FilePathLifetime_NoExist.cpp
  test/DynamicDependency/Test_WinRT/Create_RegistryLifetime_NoExist.cpp
Labels: area-DynamicDependencies, needs-triage :mag:

#811 [Cherry pick] Fixes for Preview VSIX (#809)
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
Labels: needs-triage :mag:

#815 Remove obsolete reference to file Microsoft.ProjectReunion.winmd which doesn't exist anymore
  build/NuSpecs/ProjectReunion-Nuget-Native.targets
Labels: area-Infrastructure, needs-triage :mag:

#800 Fix the versioning on Foundation nuspec
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/ProjectReunion-CommonVariables.yml
  build/ProjectReunion-PR.yml
  build/ProjectReunion-Versions.yml
Labels: needs-triage :mag:

#814 MRTCore will also search for [modulename].pri for unpackaged app
  build/build-mrt.yml
  dev/MRTCore/mrt/Core/src/MRM.cpp
  dev/MRTCore/mrt/Core/src/MRM.h
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/unittests/MrmTests.cpp
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/Properties/AssemblyInfo.cs
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/UnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/app.manifest
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/packages.config
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/resources.pri.standalone
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Helper.cpp
  dev/MRTCore/mrt/MrtCore.sln
Labels: needs-triage :mag:

#816 Update how test packages are copied in order to reconcile differences…
  test/AppLifecycle/AppLifecycle.vcxproj
  test/AppLifecycle/FunctionalTests.cpp
Labels: needs-triage :mag:

#827 Update Nuspecs for unpackaged consumption
  build/NuSpecs/ProjectReunion-Nuget-Native.C.props
  build/NuSpecs/ProjectReunion-Nuget-Native.WinRt.props
  build/NuSpecs/ProjectReunion-Nuget-Native.targets
Labels: area-Infrastructure, needs-triage :mag:

#830 Remove custom.props
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/custom.props
Labels: needs-triage :mag:

#831 Fix DynamicDependencies generated build overrides
  Directory.Build.props
  ProjectReunion.props
  build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/ProjectReunion-PublishProjectOutput-Steps.yml
  build/CopyFilesToStagingDir.ps1
  build/publish-mrt.yml
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
  tools/GenerateDynamicDependencyOverrides.ps1
Labels: area-DynamicDependencies, area-Infrastructure

#837 Update Bootstrap dll to match PRfwk
  Directory.Build.props
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
Labels: area-DynamicDependencies, area-Infrastructure, bug

#840 Add [experimental] tags to DynamicDependencies + AppLifecycle WinRT APIs
  dev/AppLifecycle/AppLifecycle.idl
  dev/DynamicDependency/M.AM.DynamicDependency.idl
Labels: area-DynamicDependencies, area-Lifecycle, needs-triage :mag:

#818 Cherrpick: Fix versioning to include branch and tag
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/ProjectReunion-CommonVariables.yml
  build/ProjectReunion-PR.yml
  build/ProjectReunion-Versions.yml
Labels: needs-triage :mag:

#841 DynamicDependencies: Change WinRT namespace to Microsoft.Windows.ApplicationModel.DynamicDependency
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.DynamicDependency.xml
  build/NuSpecs/ProjectReunion-Nuget-Native.WinRt.props
  build/NuSpecs/ProjectReunion-Nuget-Native.targets
  dev/DynamicDependency/M.AM.Converters.h
  dev/DynamicDependency/M.AM.DD.AddPackageDependencyOptions.cpp
  dev/DynamicDependency/M.AM.DD.AddPackageDependencyOptions.h
  dev/DynamicDependency/M.AM.DD.CreatePackageDependencyOptions.cpp
  dev/DynamicDependency/M.AM.DD.CreatePackageDependencyOptions.h
  dev/DynamicDependency/M.AM.DD.PackageDependency.cpp
  dev/DynamicDependency/M.AM.DD.PackageDependency.h
  dev/DynamicDependency/M.AM.DD.PackageDependencyContext.cpp
  dev/DynamicDependency/M.AM.DD.PackageDependencyContext.h
  dev/DynamicDependency/M.AM.DD.PackageDependencyRank.cpp
  dev/DynamicDependency/M.AM.DD.PackageDependencyRank.h
  dev/DynamicDependency/M.AM.DynamicDependency.idl
  dev/DynamicDependency/winrt_namespaces.h
  specs/dynamicdependencies/DynamicDependencies.md
  specs/dynamicdependencies/sample-1.md
  specs/dynamicdependencies/sample-3.md
  specs/dynamicdependencies/sample-4.md
  specs/dynamicdependencies/sample-5.md
  specs/dynamicdependencies/sample-6.md
  specs/dynamicdependencies/sample-7.md
  specs/dynamicdependencies/sample-8.md
  test/DynamicDependency/Test_WinRT/Create_FilePathLifetime_NoExist.cpp
  test/DynamicDependency/Test_WinRT/Create_RegistryLifetime_NoExist.cpp
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.h
  test/DynamicDependency/Test_WinRT/Test_WinRT_Add_Rank_A0_B10.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Add_Rank_B-10_A0.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Add_Rank_B0prepend_A0.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Create_Add_Architectures_Current.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Create_Add_Architectures_Explicit.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Create_DoNotVerifyDependencyResolution.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_FullLifecycle_FilePathLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_FullLifecycle_RegistryLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_WinRT/pch.h
  test/DynamicDependency/data/Microsoft.ProjectReunion.Framework/appxmanifest.xml
Labels: area-DynamicDependencies

#835 Convert MRT Core UnitTests from MSTest to TAEF
  build/Helix/ConvertWttLogToXUnit.ps1
  build/build-mrt.yml
  dev/MRTCore/mrt/Core/unittests/MrmTests.cpp
  dev/MRTCore/mrt/Core/unittests/UnitTest.vcxproj
  dev/MRTCore/mrt/Core/unittests/packages.config
Labels: needs-triage :mag:

#845 DynamicDependencies bug in AppxManifest'd winrt inprocserver handling
  dev/DynamicDependency/WinRTInprocModule.h
  dev/DynamicDependency/WinRTPackage.cpp
  dev/DynamicDependency/WinRTPackage.h
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.h
  test/DynamicDependency/data/Microsoft.ProjectReunion.Framework/appxmanifest.xml
Labels: area-DynamicDependencies, bug, needs-triage :mag:

#849 correct the path of Microsoft.ApplicationModel.Resources.winmd for native project
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
Labels: needs-triage :mag:

#846 Add framework deployment for DDLM, update output text
  installer/dev/console.cpp
  installer/dev/install.cpp
  installer/dev/main.cpp
  installer/dev/packages.h
  installer/dev/project_reunion_definitions.h
  installer/test/InstallerFunctionalTests/FunctionalTests.cpp
Labels: needs-triage :mag:

#855 Copy Microsoft.ProjectReunion.Bootstrap.dll to $(OutDir) for non-native projects.
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/NuSpecs/Microsoft.ProjectReunion.Bootstrap.targets
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.targets
Labels: area-DynamicDependencies

#843 Onboard Foundation to use Maestro
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/Maestro-PublishBuildToMaestro.yml
  eng/common/MaestroGetRequest.ps1
  eng/common/MaestroHelpers.ps1
  eng/common/MaestroPostRequest.ps1
  eng/common/README.md
  global.json
Labels: needs-triage :mag:

#870 Modify MRT Core UnpackagedTests clean-up, and reorganize test reporting
  build/build-mrt.yml
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
Labels: needs-triage :mag:

#872 DynamicDependencies: fix PCWSTR[] access
  dev/DynamicDependency/PackageDependency.cpp
  tools/DevCheck.ps1
Labels: area-DynamicDependencies, bug, needs-triage :mag:

#873 DynamicDependencies: fix PCWSTR[] access (#872)
  dev/DynamicDependency/PackageDependency.cpp
  tools/DevCheck.ps1
Labels: needs-triage :mag:

#881 Enable MRT Core Unpackaged Tests to work in Visual Studio Test Explorer
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/UnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/UnpackagedTests.runsettings
Labels: needs-triage :mag:

#882 Adding Suspend/Resume notification code()
  dev/PowerNotifications/PowerNotifications.cpp
  dev/PowerNotifications/PowerNotifications.h
  dev/PowerNotifications/PowerNotifications.idl
  test/PowerNotificationsTests/PowerTests.cpp
Labels: needs-triage :mag:
