Repository microsoft/WindowsAppSDK, pull requests merged in 2021-10, with the labels that each got.

#1515 Adding source link to Notifications projects not yet in main
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/PushNotificationsLongRunningTask.ProxyStub.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/PushNotificationsLongRunningTask.ProxyStub.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/packages.config
Labels: needs-triage :mag:, area-Notifications

#1517 Remove experimental tag from AppLifecycle feature.
  dev/AppLifecycle/AppLifecycle.idl
Labels: needs-triage :mag:

#1097 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: needs-triage :mag:

#1458 User/aeloros/fileencodefix
  dev/AppLifecycle/ActivationRegistrationManager.cpp
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/FileActivatedEventArgs.h
  dev/AppLifecycle/ValueMarshaling.h
  test/AppLifecycle/FunctionalTests.cpp
Labels: needs-triage :mag:

#1522 Unconditionally restore vsext to Dev16 VSIX
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#1512 Fix the DDLM package name in the spec
  specs/Deployment/MSIXPackages.md
Labels: area-Infrastructure

#1513 Refactored utf16->utf8 support from DynDep to common
  dev/Common/Microsoft.Utf8.h
  dev/DynamicDependency/API/DataStore.cpp
  dev/DynamicDependency/API/DynamicDependency.vcxitems
  dev/DynamicDependency/API/DynamicDependency.vcxitems.filters
  dev/DynamicDependency/API/PackageDependency.cpp
  dev/DynamicDependency/API/pch.h
  dev/DynamicDependency/API/utf8.h
  dev/WindowsAppRuntime_DLL/pch.h
Labels: needs-triage :mag:, area-DynamicDependencies

#1440 removed OS CRT/STL leftovers and added CX considerations to Hybrid CRT doc
  HybridCRT.props
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependency.DataStore.ProxyStub.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  docs/Coding-Guidelines/HybridCRT.md
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
Labels: needs-triage :mag:

#1511 Deployment API Fix for Singleton not having major.minor in the package name
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/PackageDefinitions.h
  test/Deployment/Deployment-Capabilities-AppxManifest.xml
  test/Deployment/Deployment-NoCapabilities-AppxManifest.xml
  test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
  test/Deployment/data/WindowsAppRuntime.Test.Main/appxmanifest.xml
  test/Deployment/data/WindowsAppRuntime.Test.Singleton/appxmanifest.xml
  test/inc/WindowsAppRuntime.Test.Package.h
Labels: needs-triage :mag:

#1534 (CherryPick) Use public pool and PAT for publishing public symbols #1267
  build/ProjectReunion-BuildFoundation.yml
Labels: area-Infrastructure

#1536 Update to the 22000 Microsoft.Windows.SDK.BuildTools nuget package
  dev/VSIX/Directory.Build.props
Labels: needs-triage :mag:

#1538 UndockedRegFreeWinRT reentrancy bug
  WindowsAppRuntime.sln
  dev/DynamicDependency/API/PackageDependencyManager.cpp
  dev/DynamicDependency/API/PackageGraphManager.cpp
  dev/DynamicDependency/API/PackageGraphManager.h
  dev/DynamicDependency/API/WinRTInprocModule.h
  dev/DynamicDependency/API/WinRTModuleManager.cpp
  dev/DynamicDependency/API/WinRTModuleManager.h
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj.filters
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestPackages.cpp
  test/DynamicDependency/Test_Win32/TestPackages.h
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_LifetimeManagement.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.h
  test/DynamicDependency/Test_Win32/Test_Win32_WinRTReentrancy.cpp
  test/DynamicDependency/Test_Win32/pch.h
  test/DynamicDependency/data/Framework.Widgets/Framework.Widgets.vcxproj
  test/DynamicDependency/data/Framework.Widgets/Framework.Widgets.vcxproj.filters
  test/DynamicDependency/data/Framework.Widgets/Microsoft.Test.DynamicDependency.Widgets.Widget1.cpp
  test/DynamicDependency/data/Framework.Widgets/Microsoft.Test.DynamicDependency.Widgets.Widget1.h
  test/DynamicDependency/data/Framework.Widgets/Microsoft.Test.DynamicDependency.Widgets.Widget2.cpp
  test/DynamicDependency/data/Framework.Widgets/Microsoft.Test.DynamicDependency.Widgets.Widget2.h
  test/DynamicDependency/data/Framework.Widgets/Widgets.idl
  test/DynamicDependency/data/Framework.Widgets/appxmanifest.template
  test/DynamicDependency/data/Framework.Widgets/dllmain.cpp
  test/DynamicDependency/data/Framework.Widgets/logo.png
  test/DynamicDependency/data/Framework.Widgets/module.def
  test/DynamicDependency/data/Framework.Widgets/packages.config
  test/DynamicDependency/data/Framework.Widgets/pch.cpp
  test/DynamicDependency/data/Framework.Widgets/pch.h
  test/DynamicDependency/data/Framework.Widgets/targetver.h
Labels: needs-triage :mag:, area-DynamicDependencies

#1521 Support foregroundtask registration for packaged applications
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationChannel.h
  dev/PushNotifications/PushNotificationUtility.cpp
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/externs.h
  test/TestApps/PushNotificationsDemoApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#1545 Fix incorrect winmd name in NuSpecs
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Labels: needs-triage :mag:
