Repository microsoft/WindowsAppSDK, pull requests merged in 2021-04, with the labels that each got.

#674 Set SDKVersion
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: needs-triage :mag:

#641 Cherry pick: Duplicate MSBuildProjectExtensionsPath was causing inconsistent nuget restore and broken vsix builds (#640)
  build/ProjectReunion-Create-VSIX.yml
  dev/VSIX/Directory.Build.props
Labels: needs-triage :mag:

#677 Port some OS code change
  dev/MRTCore/mrt/mrm/mrmmin/BaseFile.cpp
  dev/MRTCore/mrt/mrm/mrmmin/Util.cpp
Labels: needs-triage :mag:

#684 Set SDKVersion (#674)
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: needs-triage :mag:

#685 Move MrtCore up to cswinrt 1.2 to keep in sync with WinUI
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#689 cherry pick: Move MrtCore up to cswinrt 1.2 to keep in sync with WinUI
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#691 Fix some MRTCore build warnings
  dev/MRTCore/mrt/Core/unittests/UnitTest.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
  dev/MRTCore/mrt/MrtCore.sln
Labels: needs-triage :mag:

#690 Update faq.md
  docs/faq.md
Labels: needs-triage :mag:

#695 Suppress warning MSB8019
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
Labels: needs-triage :mag:

#696 Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 2)
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#697 remove subfolder for Microsoft.ApplicationModel.Resources.winmd
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
  dev/MRTCore/publish-mrt.yml
Labels: needs-triage :mag:

#703 Update MRTCore to .net 5.0.3
  dev/MRTCore/build-mrt.yml
  dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
Labels: needs-triage :mag:

#706 Switch to Open Helix Queues (#665)
  build/AzurePipelinesTemplates/ProjectReunion-ProcessTestResults-Job.yml
  build/AzurePipelinesTemplates/ProjectReunion-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
Labels: needs-triage :mag:

#704 Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 3)
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#705 Update MRTCore to .net 5.0.3 (#703)
  dev/MRTCore/build-mrt.yml
  dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
Labels: needs-triage :mag:

#681 Updated transport package for PRfwk/main/ddlm
  build/CopyFilesToStagingDir.ps1
Labels: area-Infrastructure, needs-triage :mag:

#707 Add PRI generation support for all .NET versions greater than 5.
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#715 update to cswinrt 1.2.1 and .NET 5.0.5
  dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#717 Fix impl of is-greater-than-dot-net-5 version check.
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#615 [Prototype] Implement CreateChannelAsync to request for channelURI from WNS
  build/NuSpecs/AppxManifest.xml
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  dev/ProjectReunion_DLL/packages.config
  dev/PushNotifications/ChannelResult.cpp
  dev/PushNotifications/ChannelResult.h
  dev/PushNotifications/PushManager.cpp
  dev/PushNotifications/PushManager.h
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationChannel.h
  dev/PushNotifications/PushNotificationCreateChannelResult.cpp
  dev/PushNotifications/PushNotificationCreateChannelResult.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
  dev/PushNotifications/PushNotifications.idl
  dev/PushNotifications/PushNotifications.vcxitems
Labels: needs-triage :mag:

#522 Prepare MRTCore binaries for scanning tools.
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
Labels: area-Resources

#702 User/benkuhn/vsix version
  build/ProjectReunion-Create-VSIX.yml
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#723 Remove other version references in props and targets
  dev/VSIX/Directory.Build.props
  dev/VSIX/Directory.Build.targets
Labels: needs-triage :mag:

#656 Update Installer to support main package install and DDLM
  installer/ProjectReunionInstall.sln
  installer/dev/ProjectReunionInstall.rc
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/packages.h
  installer/dev/project_reunion_definitions.h
  installer/test/CreateInstallerTestPackages/Assets/NonFunctioning.exe
  installer/test/CreateInstallerTestPackages/Assets/SplashScreen.png
  installer/test/CreateInstallerTestPackages/Assets/Square150x150Logo.png
  installer/test/CreateInstallerTestPackages/Assets/Square44x44Logo.png
  installer/test/CreateInstallerTestPackages/Assets/Wide310x150Logo.png
  installer/test/CreateInstallerTestPackages/Assets/logo.png
  installer/test/CreateInstallerTestPackages/CreateInstallerTestPackages.vcxproj
  installer/test/CreateInstallerTestPackages/CreateInstallerTestPackages.vcxproj.filters
  installer/test/CreateInstallerTestPackages/Makefile.mak
  installer/test/CreateInstallerTestPackages/appxmanifest_ddlm_arm64.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_ddlm_x64.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_ddlm_x86.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_fw_arm64.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_fw_x64.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_fw_x86.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_main_arm64.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_main_x64.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_main_x86.xml
  installer/test/CreateInstallerTestPackages/appxmanifest_x64.xml
  installer/test/CreateInstallerTestPackages/logo.png
  installer/test/InstallerFunctionalTests/FunctionalTests.cpp
  installer/test/InstallerFunctionalTests/constants.h
  installer/test/InstallerFunctionalTests/helpers.cpp
  installer/test/InstallerFunctionalTests/helpers.h
Labels: area-Installer, needs-triage :mag:

#725 Bring in VSIX Updates from release
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#727 Rewrite DynamicDependencies tests using TAEF
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/ProjectReunion_BootstrapDLL/ProjectReunion_BootstrapDLL.vcxproj
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  dev/ProjectReunion_DLL/packages.config
  test/AppLifecycle/AppLifecycle.vcxproj
  test/AppLifecycle/packages.config
  test/DynamicDependency/Test_Win32/Create_FilePathLifetime_NoExist.cpp
  test/DynamicDependency/Test_Win32/Create_RegistryLifetime_NoExist.cpp
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj.filters
  test/DynamicDependency/Test_Win32/TestCom.cpp
  test/DynamicDependency/Test_Win32/TestCom.h
  test/DynamicDependency/Test_Win32/TestFilesystem.cpp
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestPackages.cpp
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_LifetimeManagement.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.h
  test/DynamicDependency/Test_Win32/Test_Win32_Add_Rank_A0_B10.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_Add_Rank_B-10_A0.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_Add_Rank_B0prepend_A0.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_Create_Add_Architectures_Current.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_Create_Add_Architectures_Explicit.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_Create_DoNotVerifyDependencyResolution.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_FullLifecycle_FilePathLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_FullLifecycle_ProcessLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_Win32/Test_Win32_FullLifecycle_RegistryLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_Win32/packages.config
  test/DynamicDependency/Test_Win32/pch.h
  test/DynamicDependency/Test_WinRT/CppUnitTestX.h
  test/DynamicDependency/Test_WinRT/Create_FilePathLifetime_NoExist.cpp
  test/DynamicDependency/Test_WinRT/Create_RegistryLifetime_NoExist.cpp
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj.filters
  test/DynamicDependency/Test_WinRT/TestCom.cpp
  test/DynamicDependency/Test_WinRT/TestCom.h
  test/DynamicDependency/Test_WinRT/TestFilesystem.cpp
  test/DynamicDependency/Test_WinRT/TestPackages.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.h
  test/DynamicDependency/Test_WinRT/Test_WinRT_Add_Rank_A0_B10.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Add_Rank_B-10_A0.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Add_Rank_B0prepend_A0.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Create_Add_Architectures_Current.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Create_Add_Architectures_Explicit.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_Create_DoNotVerifyDependencyResolution.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_FullLifecycle_FilePathLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_FullLifecycle_ProcessLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT_FullLifecycle_RegistryLifetime_Frameworks_2.cpp
  test/DynamicDependency/Test_WinRT/packages.config
  test/DynamicDependency/Test_WinRT/pch.h
  test/TestApps/AppLifecycleTestApp/AppLifecycleTestApp.vcxproj
  test/TestApps/AppLifecycleTestApp/packages.config
Labels: area-DynamicDependencies

#672 Update AppLifecycle SingleMulti-Instancing.md
  specs/AppLifecycle/Instancing/AppLifecycle SingleMulti-Instancing.md
Labels: needs-triage :mag:

#721 append and remove from path
  ProjectReunion.sln
  dev/ChangeTracker/EnvironmentVariableChangeTracker.cpp
  dev/ChangeTracker/EnvironmentVariableChangeTracker.h
  dev/ChangeTracker/IChangeTracker.h
  dev/Microsoft.Process.Environment/EnvironmentManager.cpp
  dev/Microsoft.Process.Environment/EnvironmentManager.h
  dev/Microsoft.Process.Environment/EnvironmentManager.idl
  test/EnvironmentManagerTests/ChangeTrackerHelper.h
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.h
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj.filters
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.h
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.h
  test/EnvironmentManagerTests/EnvironmentVariableHelper.h
  test/EnvironmentManagerTests/TestCommon.h
  test/EnvironmentManagerTests/TestSetupAndTeardownHelper.h
  test/EnvironmentManagerTests/pch.h
Labels: needs-triage :mag:

#754 Lay groundwork for build/dyndep alignment
  .gitignore
  ProjectReunion.props
  build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
  build/BuildAll.proj
  dev/DynamicDependency/MddLifetimeManagement.cpp
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependencyDataStore.idl
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/winmain.cpp
  dev/DynamicDependencyDataStore/DynamicDependencyDataStore-Constants.h
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager-Constants.h
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.idl
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/winmain.cpp
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.h
  specs/dynamicdependencies/DynamicDependencies.md
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestPackages.h
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_LifetimeManagement.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_WinRT/TestPackages.cpp
  test/DynamicDependency/Test_WinRT/TestPackages.h
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/data/DynamicDependency.DataStore.Msix/DynamicDependencies.DataStore.Msix.vcxproj
  test/DynamicDependency/data/DynamicDependency.DataStore.Msix/Makefile.mak
  test/DynamicDependency/data/DynamicDependency.DataStore.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/DynamicDependencyLifetimeManager.Msix.vcxproj
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Makefile.mak
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest.xml
  test/TestApps/AppLifecycleTestApp/main.cpp
  test/inc/ProjectReunion.Test.Bootstrap.h
  test/inc/ProjectReunion.Test.Package.h
  tools/GenerateDynamicDependencyOverrides.ps1
  tools/MakeAppxManifestFromTemplate.cmd
  tools/MakeAppxManifestFromTemplate.ps1
Labels: area-DynamicDependencies, area-Infrastructure, needs-triage :mag:

#759 Move DynamicDependencies overrides to BuildOutput\override
  ProjectReunion.props
  build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
  build/CopyFilesToStagingDir.ps1
  tools/GenerateDynamicDependencyOverrides.ps1
Labels: area-DynamicDependencies, area-Infrastructure, needs-triage :mag:

#751 Merging release branch into main
  dev/MRTCore/build-mrt.yml
  dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
Labels: needs-attention :wave:

#760 Fix .h locations in Foundation NuGet. Fix .appx references to .msix. Move MRT build/publish-mrt.yml to build
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/build-nupkg.ps1
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/build-mrt.yml
  build/publish-mrt.yml
Labels: needs-triage :mag:

#761 Add property to toggle creation of preview VSIX
  .gitignore
  build/ProjectReunion-Create-VSIX.yml
  dev/VSIX/Directory.Build.targets
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
Labels: needs-triage :mag:

#764 Fix Installer Build Warnings
  installer/dev/install.cpp
  installer/dev/project_reunion_definitions.h
Labels: needs-triage :mag:

#747 Publish symbols to both public and internal servers
  build/AzurePipelinesTemplates/ProjectReunion-ProduceStrippedSymbols-Steps.yml
  build/Install-WindowsSdkISO.ps1
  build/ProjectReunion-BuildFoundation.yml
  build/StripSymbols.ps1
Labels: needs-triage :mag:

#783 Update frameworkUDK version
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Labels: needs-triage :mag:

#784 Update FrameworkUDK
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Labels: needs-triage :mag:
