Repository microsoft/WindowsAppSDK, pull requests merged in 2021-06, with the labels that each got.

#895 Remove survey
  README.md
Labels: needs-triage :mag:

#861 Update eng/common folder
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  eng/common/Maestro-PublishBuildToMaestro.yml
  eng/common/MaestroHelpers.ps1
Labels: needs-triage :mag:

#897 Add UseWinUI property
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/ProjectTemplate.vcxproj
Labels: needs-triage :mag:

#901 Enable publishToMaestro when build is scheduled
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#902 Add UseWinUI property (#897)
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/ProjectTemplate.vcxproj
Labels: needs-triage :mag:

#904 Reduce MRM.dll binary size by 37 KB by disabling RTTI.
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
Labels: needs-triage :mag:

#888 Use the Universal C Runtime
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependency.DataStore.ProxyStub.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/ProjectReunion_BootstrapDLL/ProjectReunion_BootstrapDLL.vcxproj
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
Labels: area-DynamicDependencies, area-Infrastructure, area-Lifecycle, needs-triage :mag:

#908 Replace custom path handling in MRT
  build/build-mrt.yml
  dev/MRTCore/mrt/Core/src/MRM.cpp
Labels: needs-triage :mag:

#910 Remove Config=Debug_test and Platform=ARM
  Directory.Build.props
  ProjectReunion.sln
  test/AppLifecycle/AppLifecycle.vcxproj
  test/DynamicDependency/data/DynamicDependency.DataStore.Msix/DynamicDependencies.DataStore.Msix.vcxproj
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/DynamicDependencyLifetimeManager.Msix.vcxproj
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/DynamicDependencyLifetimeManagerGC1000.Msix.vcxproj
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/DynamicDependencyLifetimeManagerGC1010.Msix.vcxproj
  test/DynamicDependency/data/Framework.Math.Add/Framework.Math.Add.vcxproj
  test/DynamicDependency/data/Framework.Math.Multiply/Framework.Math.Multiply.vcxproj
Labels: area-Infrastructure, needs-triage :mag:

#917 Fix copy xbf file
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: needs-triage :mag:

#825 fix typo in roadmap
  docs/roadmap.md
Labels: needs-triage :mag:

#932 Strip experimental bits and references from 0.8 release
  build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/Microsoft.ProjectReunion.Bootstrap.targets
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.targets
  build/NuSpecs/ProjectReunion-Nuget-Native.C.props
  build/NuSpecs/ProjectReunion-Nuget-Native.WinRt.props
  build/NuSpecs/ProjectReunion-Nuget-Native.props
  build/NuSpecs/ProjectReunion-Nuget-Native.targets
  build/NuSpecs/build-nupkg.ps1
Labels: area-DynamicDependencies, area-Infrastructure, area-Lifecycle

#929 Amending PowerMode Functions
  dev/PowerNotifications/ClosedSourceMock.cpp
  dev/PowerNotifications/PowerNotifications.cpp
  dev/PowerNotifications/PowerNotifications.h
  dev/PowerNotifications/PowerNotifications.idl
  dev/PowerNotifications/PowerNotificationsPal.h
  test/PowerNotificationsTests/PowerTests.cpp
Labels: needs-triage :mag:

#933 Adding Push Notifications to Roadmap
  README.md
  docs/README.md
  docs/roadmap.md
Labels: needs-triage :mag:
