Repository microsoft/WindowsAppSDK, pull requests merged in 2021-03, with the labels that each got.

#497 Change the props name
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.props
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
Labels: needs-triage :mag:

#506 Update roadmap (unpackaged apps to 0.8)
  docs/roadmap.md
Labels: needs-triage :mag:

#524 Tweaks for Reunion 0.5 Preview release
  dev/VSIX/Directory.Build.props
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
Labels: needs-triage :mag:

#525 Cherry Pick: Tweaks for Reunion 0.5 Preview release (#524)
  dev/VSIX/Directory.Build.props
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
Labels: needs-triage :mag:

#526 Revert naming of win32 apps' PRI to the project name.
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#509 User/ertorres/create vsix
  build/ProjectReunion-Create-VSIX.yml
  dev/VSIX/Directory.Build.props
  dev/VSIX/packages.config
Labels: draft

#530 address build/restore issues causing vsix pipeline failures
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#523 Replace PNG assets with lossless optimized variants
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/LockScreenLogo.scale-200.png
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/SplashScreen.scale-200.png
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/Square150x150Logo.scale-200.png
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/Square44x44Logo.scale-200.png
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/StoreLogo.png
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/Assets/Wide310x150Logo.scale-200.png
  dev/VSIX/Extension/Reunion.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/LockScreenLogo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/SplashScreen.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/Square150x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/Square44x44Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/StoreLogo.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/Wide310x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/LockScreenLogo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/SplashScreen.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/Square150x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/Square44x44Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/StoreLogo.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/Wide310x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.png
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/LockScreenLogo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/SplashScreen.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/Square150x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/Square44x44Logo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/StoreLogo.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/Assets/Wide310x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.png
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/LockScreenLogo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/SplashScreen.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/Square150x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/Square44x44Logo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/StoreLogo.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/Assets/Wide310x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.png
  docs/images/converged-apis-image-2.png
  docs/images/converged-apis-image.png
  docs/images/new-apis-image.png
  docs/images/proposal-flow.png
  installer/test/CreateInstallerTestPackages/logo.png
  test/TestApps/AppLifecycleTestPackage/Images/LockScreenLogo.scale-200.png
  test/TestApps/AppLifecycleTestPackage/Images/SplashScreen.scale-200.png
  test/TestApps/AppLifecycleTestPackage/Images/Square150x150Logo.scale-200.png
  test/TestApps/AppLifecycleTestPackage/Images/Square44x44Logo.scale-200.png
  test/TestApps/AppLifecycleTestPackage/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  test/TestApps/AppLifecycleTestPackage/Images/StoreLogo.png
  test/TestApps/AppLifecycleTestPackage/Images/Wide310x150Logo.scale-200.png
Labels: needs-triage :mag:

#537 Cherry pick: create VSIX pipeline (#509)
  build/ProjectReunion-Create-VSIX.yml
Labels: needs-triage :mag:

#531 Cherry pick: address build/restore issues causing vsix pipeline failures (#530)
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#538 Cherry-Pick: create VSIX pipeline fixes (#537)
  build/ProjectReunion-Create-VSIX.yml
  dev/VSIX/Directory.Build.props
  dev/VSIX/packages.config
Labels: needs-triage :mag:

#545 Remove checked-in test MSIX for the Installer
  .gitignore
  installer/dev/README.md
  installer/test/CreateInstallerTestPackages/Makefile.mak
  installer/test/CreateInstallerTestPackages/README.md
  installer/test/testpackages/framework_arm64.msix
  installer/test/testpackages/framework_x64.msix
  installer/test/testpackages/framework_x86.msix
Labels: needs-triage :mag:

#454 Startup activations, AppLifecycle updates, and activations.
  ProjectReunion.sln
  dev/AppLifecycle/ActivationRegistrationManager.cpp
  dev/AppLifecycle/ActivationRegistrationManager.h
  dev/AppLifecycle/AppLifecycle.cpp
  dev/AppLifecycle/AppLifecycle.idl
  dev/AppLifecycle/AppLifecycle.vcxitems
  dev/AppLifecycle/Association.cpp
  dev/AppLifecycle/Association.h
  dev/AppLifecycle/EncodedLaunchExecuteCommand.cpp
  dev/AppLifecycle/EncodedLaunchExecuteCommand.h
  dev/AppLifecycle/ExecuteCommandBase.h
  dev/AppLifecycle/ExtensionContract.h
  dev/AppLifecycle/FileActivatedEventArgs.h
  dev/AppLifecycle/LaunchActivatedEventArgs.h
  dev/AppLifecycle/ProtocolActivatedEventArgs.h
  dev/AppLifecycle/StartupActivatedEventArgs.h
  dev/ProjectReunion_DLL/COMExports.cpp
  dev/ProjectReunion_DLL/ProjectReunion.def
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj.filters
  dev/ProjectReunion_DLL/dllmain.cpp
  dev/ProjectReunion_DLL/pch.h
  test/AppLifecycle/APITests.cpp
  test/AppLifecycle/AppLifecycle.vcxitems
  test/AppLifecycle/AppLifecycle.vcxitems.filters
  test/AppLifecycle/AppLifecycle.vcxproj
  test/AppLifecycle/AppLifecycle.vcxproj.filters
  test/AppLifecycle/FunctionalTests.cpp
  test/AppLifecycle/Shared.cpp
  test/AppLifecycle/Shared.h
  test/AppLifecycle/packages.config
  test/AppLifecycle/pch.cpp
  test/AppLifecycle/pch.h
  test/CppShared/CppShared.vcxitems
  test/CppShared/TestMany.cpp
  test/TestApps/AppLifecycleTestApp/main.cpp
  test/inc/ProjectReunion.Test.AppModel.h
  test/inc/ProjectReunion.Test.Bootstrap.h
  test/inc/ProjectReunion.Test.FileSystem.h
  test/inc/ProjectReunion.Test.Package.h
  test/inc/TestDef.h
Labels: area-Lifecycle, area-Startup apps

#541 Add API design process notes
  docs/.prettierrc
  docs/Coding-Guidelines.md
  specs/.prettierrc
  specs/README.md
Labels: api-design

#569 Cherry pick: MRTCore will also lookup parent folder
  dev/MRTCore/mrt/Core/src/MRM.cpp
Labels: needs-triage :mag:

#434 Update AppLifecycle Activation.md
  specs/AppLifecycle/Activation/AppLifecycle Activation.md
  specs/AppLifecycle/Instancing/AppLifecycle SingleMulti-Instancing.md
Labels: api-design

#458 Reunion Push Notifications API spec
  specs/PushNotifications/Legacy.PNG
  specs/PushNotifications/Push.PNG
  specs/PushNotifications/PushNotifications-spec.md
Labels: api-design, area-Notifications

#576 Bump transport package version to 0.5
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
Labels: needs-triage :mag:

#578 simplify wap project templates to enable PackageReferences upgrades
  assets/Reunion128.png
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
Labels: needs-triage :mag:

#581 Bump transport package version to 0.5 (#576)
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
Labels: needs-triage :mag:

#548 cherry pick: always use internal feed
  build/ProjectReunion-Create-VSIX.yml
Labels: needs-triage :mag:

#580 cherry pick: simplify wap project templates to enable PackageReferences upgrades, ensure that ad hoc PackageReferences work for wapproj
  assets/Reunion128.png
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
Labels: needs-triage :mag:

#591 GA tweaks - VS 16.9 prereq, WinUI 3 rename, remove UWP templates, Suspending event
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.cpp
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
Labels: needs-triage :mag:

#595 cherry pick: GA tweaks - VS 16.9 prereq, WinUI 3 rename, remove UWP templates, Suspending event (#591)
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
  dev/VSIX/Extension/source.extension.vsixmanifest
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.cpp
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
Labels: needs-triage :mag:

#614 Update Framework UDK
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Labels: needs-triage :mag:

#617 Add temporary trap to block calling DynamicDependencies (or Bootstrap) APIs if Elevated
  dev/DynamicDependency/MsixDynamicDependency.cpp
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
  dev/ProjectReunion_BootstrapDLL/framework.h
Labels: area-DynamicDependencies, bug, needs-triage :mag:

#620 DynamicDependencies: Only Detour functions in not-packaged processes
  dev/DynamicDependency/PackageGraphManager.cpp
  dev/ProjectReunion_DLL/dllmain.cpp
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/pch.h
Labels: area-DynamicDependencies, needs-triage :mag:

#631 Remove unnecessary Pkg* defines and avoid bad vsix builds when nuget restore fails
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#577 API design for power state, activation, and instancing
  specs/AppLifecycle/.gitkeep
  specs/AppLifecycle/Activation/.gitkeep
  specs/AppLifecycle/Activation/AppLifecycle Activation.md
  specs/AppLifecycle/Instancing/.gitkeep
  specs/AppLifecycle/Instancing/AppLifecycle SingleMulti-Instancing.md
  specs/AppLifecycle/StateNotifications/.gitkeep
  specs/AppLifecycle/StateNotifications/AppLifecycle StateNotifications.md
Labels: needs-triage :mag:

#579 Implementation and tests for GetEnvironmentVariables
  dev/Microsoft.Process.Environment/EnvironmentManager.cpp
  dev/Microsoft.Process.Environment/EnvironmentManager.h
  dev/Microsoft.Process.Environment/EnvironmentManager.idl
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.h
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj.filters
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.h
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.h
  test/EnvironmentManagerTests/EnvironmentVariableHelper.h
  test/EnvironmentManagerTests/framework.h
  test/EnvironmentManagerTests/pch.cpp
  test/EnvironmentManagerTests/pch.h
Labels: needs-triage :mag:

#632 Adding tests
  ProjectReunion.sln
  dev/PowerNotifications/ClosedSourceMock.cpp
  dev/PowerNotifications/PowerNotifications.cpp
  dev/PowerNotifications/PowerNotifications.h
  dev/PowerNotifications/PowerNotifications.vcxitems
  dev/PowerNotifications/PowerNotificationsPal.h
  test/PowerNotificationsTests/PowerNotificationsTests.vcxproj
  test/PowerNotificationsTests/PowerNotificationsTests.vcxproj.filters
  test/PowerNotificationsTests/PowerTests.cpp
  test/PowerNotificationsTests/PowerTests.dll.manifest
  test/PowerNotificationsTests/packages.config
  test/PowerNotificationsTests/pch.cpp
  test/PowerNotificationsTests/pch.h
Labels: needs-triage :mag:

#640 Duplicate MSBuildProjectExtensionsPath was causing inconsistent nuget restore and broken vsix builds
  dev/VSIX/Directory.Build.props
Labels: needs-triage :mag:

#600 Enable running BinSkim on Foundation
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  dev/Detours/Detours.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependency.DataStore.ProxyStub.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/DynamicDependencyLifetimeManager/IDynamicDependencyLifetimeManager/IDynamicDependencyLifetimeManager.vcxproj
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/ProjectReunion.Build.cpp.props
  dev/ProjectReunion_BootstrapDLL/ProjectReunion_BootstrapDLL.vcxproj
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
Labels: needs-triage :mag:

#654 User/benkuhn/add vsix patch option
  build/ProjectReunion-Create-VSIX.yml
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#651 Readme updates for 0.5 release
  README.md
  docs/roadmap.md
Labels: needs-triage :mag:

#498 API spec template format updates
  specs/spec_template.md
Labels: api-design

#664 Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 1)
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Labels: area-Resources

#665 Switch to Open Helix Queues
  build/AzurePipelinesTemplates/ProjectReunion-ProcessTestResults-Job.yml
  build/AzurePipelinesTemplates/ProjectReunion-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
Labels: needs-triage :mag:

#659 #163 DynamicDependencies: AppLifecycleTests failure in WinRT activation (combase.dll) on >= 20H1 / May 2020 Update / 10.0.19041.0
  ProjectReunion.sln
  dev/Common/AppModel.Identity.h
  dev/Common/Common.vcxitems
  dev/Common/Security.IntegrityLevel.h
  dev/DynamicDependency/DynamicDependency.vcxitems
  dev/DynamicDependency/MddDetourPackageGraph.cpp
  dev/DynamicDependency/MsixDynamicDependency.cpp
  dev/DynamicDependency/PackageGraphManager.cpp
  dev/DynamicDependency/PackageGraphManager.h
  dev/DynamicDependency/PackageGraphNode.cpp
  dev/DynamicDependency/PackageGraphNode.h
  dev/DynamicDependency/appmodel_msixdynamicdependency.h
  dev/DynamicDependency/pch.h
  dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
  dev/ProjectReunion_BootstrapDLL/ProjectReunion_BootstrapDLL.vcxproj
  dev/ProjectReunion_BootstrapDLL/framework.h
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  dev/ProjectReunion_DLL/dllmain.cpp
  dev/ProjectReunion_DLL/pch.h
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj.filters
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_Win32/pch.h
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/data/Microsoft.ProjectReunion.Framework/appxmanifest.xml
Labels: area-DynamicDependencies, bug, needs-triage :mag:

#673 Update AppLifecycle Activation.md
  specs/AppLifecycle/Activation/AppLifecycle Activation.md
Labels: needs-triage :mag:
