Repository microsoft/WindowsAppSDK, pull requests merged in 2021-07, with the labels that each got.

#1013 Default values fix for BatteryStatus APIs
  dev/PowerNotifications/PowerNotifications.cpp
  dev/PowerNotifications/PowerNotifications.h
Labels: needs-triage :mag:

#1019 Adding StartupTask for PushNotifications
  ProjectReunion.sln
  build/CopyFilesToStagingDir.ps1
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotifications-Constants.h
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask/pch.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/pch.h
  dev/PushNotifications/PushNotificationsLongRunningTask/winmain.cpp
  test/PushNotificationTests/APITests.cpp
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/SplashScreen.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/Square150x150Logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/Square44x44Logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/Wide310x150Logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Makefile.mak
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/PushNotificationsLongRunningTask.Msix.vcxproj
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/PushNotificationsLongRunningTask.Msix.vcxproj.filters
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/appxmanifest.xml
  test/inc/ProjectReunion.Test.Package.h
  tools/GenerateDynamicDependencyOverrides.ps1
Labels: needs-triage :mag:

#1050 Fixed DynamicDependency-Override.json error
  tools/GenerateDynamicDependencyOverrides.ps1
Labels: needs-triage :mag:

#1016 Add 19h1 to Helix queues, plus minor pipeline clean up.
  build/AzurePipelinesTemplates/ProjectReunion-RunHelixTests-Job.yml
  build/DownloadDotNetRuntimeInstaller.ps1
  build/build-mrt.yml
  test/ProjectReunion.Helix.TestCommon/TestPass-OneTimeMachineSetup.ps1
Labels: needs-triage :mag:

#956 Microsoft.ApplicationModel.Resources.References.targets should not reference ProjectReunionFrameworkPackage
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.props
  build/NuSpecs/ProjectReunion-Nuget-Native.props
  dev/MRTCore/packaging/Microsoft.Windows.ApplicationModel.Resources.References.targets
  dev/MRTCore/packaging/native/Microsoft.Windows.ApplicationModel.Resources.props
Labels: needs-triage :mag:

#1060 fix path for unpackagedtests
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/UnpackagedTests.csproj
Labels: needs-triage :mag:

#1031 Switch to using private hosted pool for Project Reunion Foundation
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-Create-VSIX.yml
Labels: area-Infrastructure, needs-triage :mag:

#1066 Add source link to MRTCore
  Directory.Build.props
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/src/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
Labels: needs-triage :mag:

#1072 Revert the rename for the connection string
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
Labels: area-Infrastructure

#1074 Revert feed name
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
Labels: needs-triage :mag:

#1079 ProjectReunion -> WindowsAppSDK rename patch
  build/NuSpecs/WindowsAppSDK-Nuget-Native.props
Labels: area-Infrastructure, needs-triage :mag:

#1076 Microsoft.WindowsApp.Resources.Projection should be targeting 10.0.17763.0
  build/publish-mrt.yml
  dev/MRTCore/mrt/Microsoft.WindowsApp.Resources/projection/Microsoft.WindowsApp.Resources.Projection.csproj
Labels: needs-triage :mag:

#1075 Follow up: Renaming more ProjectReunion -> WindowsAppSDK
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-proposal.md
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
  test/WindowsAppSDK.Helix.Test.NetCore/Program.cs
Labels: needs-triage :mag:

#1059 Create AppLifecycle Environment Variables.md
  specs/AppLifecycle/EnvironmentVariables/AppLifecycle Environment Variables.md
Labels: needs-triage :mag:

#1093 Include buildPlatform & buildConfiguration on artifacts to prevent parallel publishing issues.
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#1080 Add winrt::resume_foreground helper header to C++/WinRT project templates
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/pch.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/pch.h
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/pch.h
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/pch.h
Labels: needs-triage :mag:

#1051 Update AppLifecycle StateNotifications.md
  specs/AppLifecycle/StateNotifications/AppLifecycle StateNotifications.md
Labels: needs-triage :mag:

#1099 Switch to using private hosted pool for Project Reunion Foundation (#…
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-Create-VSIX.yml
Labels: needs-triage :mag:

#1107 Shrink DDLM windows.appExtension Name to fit in the old <=39 maxlen
  dev/Common/AppModel.Identity.h
  dev/DynamicDependency/MddLifetimeManagement.cpp
  dev/WindowsAppSDK_BootstrapDLL/MddBootstrap.cpp
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest.xml
  tools/MakeAppxManifestFromTemplate.ps1
Labels: area-DynamicDependencies, area-Infrastructure, needs-triage :mag:

#1101 Add WindowsAppSDKTelemetryResource project
  dev/Common/WindowsAppSDKTelemetry.h
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource.sln
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource.vcxproj
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource.vcxproj.filters
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource/generaterc.ps1
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource/resource.h
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource/resource.templ
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResourceLib/WindowsAppSDKTelemetry.cpp
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResourceLib/WindowsAppSDKTelemetryResourceLib.vcxproj
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResourceLib/WindowsAppSDKTelemetryResourceLib.vcxproj.filters
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResourceLib/packages.config
Labels: needs-triage :mag:

#1112 Roadmap updates
  README.md
  docs/roadmap.md
Labels: needs-triage :mag:

#1085 Adding support for running tests unpackaged
  test/PushNotificationTests/APITests.cpp
  test/PushNotificationTests/PushNotificationTests.vcxproj
  test/PushNotificationTests/PushNotificationTests.vcxproj.filters
  test/TestApps/PushNotificationsTestApp/PushNotificationsTestApp.vcxproj
  test/TestApps/PushNotificationsTestApp/main.cpp
  test/TestApps/PushNotificationsTestApp/pch.h
Labels: needs-triage :mag:

#1125 MRTCore use CSWinRT 1.3.3
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#1126 Remove .NET installer script from repo (remove from Helix pipeline and MRT core pipeline)
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/DownloadDotNetRuntimeInstaller.ps1
  build/build-mrt.yml
Labels: needs-triage :mag:

#1127 MRTCore use CSWinRT 1.3.3 (#1125)
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#1129 Publish the Helix log artifacts on failure too.
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#1132 Update FrameworkUdk
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Labels: needs-triage :mag:

#1133 DynamicDependencies: Remove [experimental] tags
  dev/DynamicDependency/M.AM.DynamicDependency.idl
Labels: area-DynamicDependencies, needs-triage :mag:

#1128 Add YML files to build and publish WindowsAppSDKTelemetry library and headers
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishTelemetry-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResource.sln
  dev/WindowsAppSDKTelemetryResource/WindowsAppSDKTelemetryResourceLib/WindowsAppSDKTelemetryResourceLib.vcxproj
Labels: needs-triage :mag:

#1146 Disable MRTCore managed test
  build/build-mrt.yml
Labels: needs-triage :mag:
