Repository microsoft/WindowsAppSDK, pull requests merged in 2021-09, with the labels that each got.

#1336 Introducing unpackaged foreground activation for PushNotifications
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationChannel.h
  dev/PushNotifications/PushNotificationDummyDeferral.h
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask/ForegroundSinkManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/ForegroundSinkManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.h
  dev/PushNotifications/externs.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/appxmanifest.xml
  test/TestApps/PushNotificationsDemoApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#1356 Ensuring the LRP msix gets built after the framework
  WindowsAppRuntime.sln
Labels: needs-triage :mag:, area-Notifications

#1337 Add basic telemetry to Push Notifications
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationTelemetry.h
  dev/PushNotifications/PushNotifications.vcxitems
Labels: needs-triage :mag:, area-Notifications

#1347 Adding C# Projections for PushNotifications
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
Labels: needs-triage :mag:, area-Notifications

#1357 Remove DOWNLEVEL_PRIOR_TO_WIN8 flag
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/include/mrm/common/MrmTraceLogging.h
  dev/MRTCore/mrt/mrm/include/mrm/common/PlatformWin32.h
  dev/MRTCore/mrt/mrm/include/mrm/platform/MrmWnf.h
  dev/MRTCore/mrt/mrm/include/mrm/platform/MrmWnfHelpers.h
  dev/MRTCore/mrt/mrm/mrmex/StdAfx.h
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/BaseProviders.cpp
  dev/MRTCore/mrt/mrm/mrmmin/MrmWnf.cpp
  dev/MRTCore/mrt/mrm/mrmmin/StdAfx.h
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj.filters
Labels: needs-triage :mag:

#1290 Channel Request for unpackaged applications
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationChannel.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotifications.idl
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask/pch.h
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.h
  dev/PushNotifications/externs.h
  dev/WindowsAppRuntime_DLL/pch.h
  test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
  test/TestApps/PushNotificationsDemoPackage/Package.appxmanifest
  test/TestApps/PushNotificationsDemoPackage/PushNotificationsDemoPackage.wapproj
Labels: needs-triage :mag:, area-Notifications

#1366 Ensure order of WARfwk install to avoid a Deployment issue
  installer/dev/packages.h
Labels: bug, area-Infrastructure

#1358 Notification delivery + Protocol Activation
  dev/AppLifecycle/AppInstance.cpp
  dev/PushNotifications/GetRawNotificationEventArgs.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask/ForegroundSinkManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/ForegroundSinkManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask/pch.h
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.h
  dev/PushNotifications/PushNotificationsLongRunningTask/platformfactory.cpp
  test/PushNotificationTests/APITests.cpp
  test/TestApps/PushNotificationsDemoPackage/Package.appxmanifest
  test/TestApps/PushNotificationsDemoPackage/PushNotificationsDemoPackage.wapproj
Labels: needs-triage :mag:, area-Notifications

#1340 Unpackaged notification unit tests
  test/PushNotificationTests/APITests.cpp
Labels: needs-triage :mag:, area-Notifications

#1364 Workaround UDK include issue
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsRT.h
Labels: needs-triage :mag:, area-Notifications

#1346 Build Information spec
  specs/Deployment/BuildInformation.md
Labels: area-Infrastructure, area-DynamicDependencies, area-Installer

#1330 Add code in BuildProject-Steps.yml to replace TraceloggingConfig. Thi…
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/build-mrt.yml
Labels: needs-triage :mag:

#1339 Removed PushNotificationToken
  dev/PushNotifications/PushNotificationActivationInfo.cpp
  dev/PushNotifications/PushNotificationActivationInfo.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
  dev/PushNotifications/PushNotificationRegistrationToken.cpp
  dev/PushNotifications/PushNotificationRegistrationToken.h
  dev/PushNotifications/PushNotificationTelemetry.h
  dev/PushNotifications/PushNotifications.idl
  dev/PushNotifications/PushNotifications.vcxitems
  test/PushNotificationTests/APITests.cpp
  test/TestApps/PushNotificationsDemoApp/main.cpp
  test/TestApps/PushNotificationsTestApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#1376 Remove experimental-ness from GenerationId
  dev/Common/TerminalVelocityFeatures-DynamicDependency.xml
  dev/DynamicDependency/API/M.AM.DD.PackageDependency.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.h
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
Labels: needs-triage :mag:

#1379 Adding Telemetry to PowerNotifications
  dev/PowerNotifications/PowerNotifications.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
Labels: needs-triage :mag:

#1381 Add the NugetAuthenticate and Restore telemetry internal
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#1380 Fix DDLM package names per spec
  dev/DynamicDependency/API/MddLifetimeManagement.cpp
  specs/Deployment/MSIXPackages.md
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest.xml
Labels: needs-triage :mag:, area-DynamicDependencies

#1386 Update FrameworkUDK
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#1388 Microsoft.WindowsAppRuntime.Bootstrap.Net.dll not in Transport package
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage :mag:, area-DynamicDependencies

#1392 VSIX titles/descriptions mention templates and VS versions
  dev/VSIX/Extension/Cpp/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
Labels: needs-triage :mag:

#1393 Update FrameworkUDK to 10.0.22453.1002-210908-1649
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#1394 Rename MRTCore build filename
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.targets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.References.targets
  dev/MRTCore/packaging/MrtCore.targets
  dev/MRTCore/packaging/README.md
  dev/MRTCore/packaging/native/MrtCore.C.props
  dev/MRTCore/packaging/native/MrtCore.props
  dev/MRTCore/packaging/native/MrtCore.targets
Labels: needs-triage :mag:

#1395 Cherrypick Microsoft.WindowsAppRuntime.Bootstrap.Net.dll to 1.0-preview1
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage :mag:, area-DynamicDependencies

#1400 Fixing PATH\PATHEXT test bug and moving code location
  WindowsAppRuntime.sln
  dev/EnvironmentManager/API/Microsoft.Process.Environment.vcxitems
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.cpp
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.h
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.idl
  dev/EnvironmentManager/ChangeTracker/ChangeTracker.vcxitems
  dev/EnvironmentManager/ChangeTracker/EnvironmentVariableChangeTracker.cpp
  dev/EnvironmentManager/ChangeTracker/EnvironmentVariableChangeTracker.h
  dev/EnvironmentManager/ChangeTracker/IChangeTracker.h
  dev/EnvironmentManager/ChangeTracker/PathChangeTracker.cpp
  dev/EnvironmentManager/ChangeTracker/PathChangeTracker.h
  dev/EnvironmentManager/ChangeTracker/PathExtChangeTracker.cpp
  dev/EnvironmentManager/ChangeTracker/PathExtChangeTracker.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  test/EnvironmentManagerTests/ChangeTrackerHelper.h
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
  test/EnvironmentManagerTests/EnvironmentVariableHelper.h
Labels: needs-triage :mag:

#1396 Shorten VSIX DisplayName
  dev/VSIX/Extension/Cpp/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Directory.Build.targets
Labels: needs-triage :mag:

#1402 The vsext install gremlins have returned, so disable it again.
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#1403 TerminalVelocity docs + infrastructure support for PushNotifications
  dev/Common/TerminalVelocityFeatures-PushNotifications.h
  dev/Common/TerminalVelocityFeatures-PushNotifications.xml
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/TerminalVelocity.md
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
Labels: area-Infrastructure, area-Notifications

#1410 Use LOG_WIN32... for Win32 errors
  dev/DynamicDependency/API/MddLifetimeManagement.cpp
Labels: bug, area-DynamicDependencies

#1397 Remove import references to Get[Current]PackageInfo2 causing load failures on RS5
  dev/DynamicDependency/API/DynamicDependency.vcxitems
  dev/DynamicDependency/API/DynamicDependency.vcxitems.filters
  dev/DynamicDependency/API/MddDetourPackageGraph.cpp
  dev/DynamicDependency/API/MddDetourPackageGraph.h
  dev/DynamicDependency/API/PackageGraphNode.cpp
  dev/DynamicDependency/API/PackageInfo.h
  dev/DynamicDependency/API/appmodel_packageinfo.cpp
  dev/DynamicDependency/API/appmodel_packageinfo.h
  dev/PushNotifications/PushNotifications.idl
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.cpp
  test/EnvironmentManagerTests/EnvironmentVariableHelper.h
  test/PushNotificationTests/PushNotificationTests.vcxproj
Labels: area-DynamicDependencies

#1408 Update roadmap.md
  docs/roadmap.md
Labels: needs-triage :mag:

#1385 Telemetry Update for Unpackaged Apps
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationTelemetry.h
Labels: needs-triage :mag:, area-Notifications

#1413 Copy Bootstrap .NET dll. Don't copy Bootstrap DLL if OutputType=Library
  build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.targets
Labels: bug, area-DynamicDependencies

#1418 Fixed P/Invoke statements with corrected DLL filename
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Bootstrap.cs
Labels: needs-triage :mag:, area-DynamicDependencies

#1421 Update FrameworkUDK to 22453.1004-210914-1546
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#1420 Update to latest UDK and undo UDK hack
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/PushNotifications/PushNotificationsRT.h
Labels: needs-triage :mag:, area-Notifications

#1416 User/aeloros/crashandforeground
  dev/AppLifecycle/AppInstance.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  test/TestApps/ManualTestApp/main.cpp
Labels: needs-triage :mag:

#1409 Added velocity checks to PushNotifications for experimental features
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  dev/Common/TerminalVelocityFeatures-PushNotifications.h
  dev/PushNotifications/PushNotificationActivationInfo.cpp
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationCreateChannelResult.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
Labels: needs-triage :mag:, area-Notifications

#1401 Fixing WNP_LRP tests
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.cpp
  test/PushNotificationTests/APITests.cpp
  test/TestApps/PushNotificationsTestApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#1425 Disable single-project C# templates for preview 1
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#1417 Handle COM shutdown for static store
  dev/PushNotifications/GetRawNotificationEventArgs.h
Labels: needs-triage :mag:, area-Notifications

#1428 Fix signing pattern to capture all winmd and dll in the transport package
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#1424 Adding trace logging to Environment Manager
  dev/EnvironmentManager/API/Microsoft.Process.Environment.vcxitems
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.Insights.h
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.cpp
  dev/WindowsAppRuntime_DLL/pch.h
  test/EnvironmentManagerTests/EnvironmentVariableHelper.h
Labels: needs-triage :mag:

#1433 Move Bootstrap.Net assembly (dll) to lib\net5.0-windows10.0.17763.0
  build/CopyFilesToStagingDir.ps1
Labels: bug, area-DynamicDependencies

#1432 Add arm64 support for Installer
  installer/WindowsAppRuntimeInstall.sln
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/install.cpp
  installer/dev/windowsappruntime_definitions.h
  installer/test/InstallerFunctionalTests/FunctionalTests.cpp
  installer/test/InstallerFunctionalTests/InstallerFunctionalTests.vcxproj
  installer/test/InstallerFunctionalTests/constants.h
  installer/test/InstallerFunctionalTests/helpers.cpp
  installer/test/InstallerFunctionalTests/helpers.h
  installer/test/InstallerFunctionalTests/packages.config
  installer/test/InstallerFunctionalTests/pch.h
Labels: needs-triage :mag:, area-Installer

#1406 Protocol Activation bug fixes
  dev/PushNotifications/GetRawNotificationEventArgs.h
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask/utils.h
  dev/PushNotifications/utils.h
Labels: area-Notifications

#1435 Use remoteId as const value
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
Labels: needs-triage :mag:, area-Notifications

#1441 Add placeholder localized resx files
  dev/VSIX/Extension/Cpp/Common/cs-CZ/VSPackage.cs-CZ.resx
  dev/VSIX/Extension/Cpp/Common/de-DE/VSPackage.de-DE.resx
  dev/VSIX/Extension/Cpp/Common/en-US/VSPackage.en-US.resx
  dev/VSIX/Extension/Cpp/Common/es-ES/VSPackage.es-ES.resx
  dev/VSIX/Extension/Cpp/Common/fr-FR/VSPackage.fr-FR.resx
  dev/VSIX/Extension/Cpp/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cpp/Common/ja-JP/VSPackage.ja-JP.resx
  dev/VSIX/Extension/Cpp/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cpp/Common/pl-PL/VSPackage.pl-PL.resx
  dev/VSIX/Extension/Cpp/Common/pt-BR/VSPackage.pt-BR.resx
  dev/VSIX/Extension/Cpp/Common/ru-RU/VSPackage.ru-RU.resx
  dev/VSIX/Extension/Cpp/Common/tr-TR/VSPackage.tr-TR.resx
  dev/VSIX/Extension/Cpp/Common/zh-CN/VSPackage.zh-CN.resx
  dev/VSIX/Extension/Cpp/Common/zh-TW/VSPackage.zh-TW.resx
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Common/cs-CZ/VSPackage.cs-CZ.resx
  dev/VSIX/Extension/Cs/Common/de-DE/VSPackage.de-DE.resx
  dev/VSIX/Extension/Cs/Common/en-US/VSPackage.en-US.resx
  dev/VSIX/Extension/Cs/Common/es-ES/VSPackage.es-ES.resx
  dev/VSIX/Extension/Cs/Common/fr-FR/VSPackage.fr-FR.resx
  dev/VSIX/Extension/Cs/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cs/Common/ja-JP/VSPackage.ja-JP.resx
  dev/VSIX/Extension/Cs/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cs/Common/pl-PL/VSPackage.pl-PL.resx
  dev/VSIX/Extension/Cs/Common/pt-BR/VSPackage.pt-BR.resx
  dev/VSIX/Extension/Cs/Common/ru-RU/VSPackage.ru-RU.resx
  dev/VSIX/Extension/Cs/Common/tr-TR/VSPackage.tr-TR.resx
  dev/VSIX/Extension/Cs/Common/zh-CN/VSPackage.zh-CN.resx
  dev/VSIX/Extension/Cs/Common/zh-TW/VSPackage.zh-TW.resx
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#1452 Add Nuget.Config to installer directory
  installer/nuget.config
Labels: needs-triage :mag:

#1453 Move Installer Nuget.Config comment down one line
  installer/nuget.config
Labels: needs-triage :mag:

#1456 Update frameworkUDK to 10.0.22453.1006-210916-1712
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#1460 Switch to CsWinRT 1.3.5
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
Labels: needs-triage :mag:

#1455 Fix publishing of Deployment API winmd and C# projections
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.WindowsAppSDK.Projection.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.WindowsAppSDK.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppSDK/Microsoft.Windows.ApplicationModel.WindowsAppSDK.Projection.csproj
Labels: needs-triage :mag:, area-App deployment

#1442 Add PRI generation support for C++ libraries
  dev/MRTCore/packaging/MrtCore.PriGen.targets
Labels: area-Resources

#1462 For MRT Core, exclude file names and file paths from logging as they contain PII.
  dev/MRTCore/mrt/mrm/include/mrm/common/MrmTraceLogging.h
  dev/MRTCore/mrt/mrm/include/mrm/common/PlatformWin32.h
Labels: area-Resources

#1468 Reduce Microsoft.Windows.ApplicationModel.Resources.dll binary size by 70KB by disabling RTTI.
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
Labels: needs-triage :mag:

#1459 Upgrade LRP to latest UDK
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
Labels: needs-triage :mag:, area-Notifications

#1467 WindowsAppRuntime_MSIXInstallFromPath.exe
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  dev/Common/AppModel.Package.h
  dev/Common/Microsoft.Utf8.h
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.filters
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.vcxproj
  dev/WindowsAppRuntime_MSIXInstallFromPath/framework.h
  dev/WindowsAppRuntime_MSIXInstallFromPath/main.cpp
  dev/WindowsAppRuntime_MSIXInstallFromPath/packages.config
  dev/WindowsAppRuntime_MSIXInstallFromPath/pch.cpp
  dev/WindowsAppRuntime_MSIXInstallFromPath/pch.h
Labels: needs-triage :mag:, area-Infrastructure

#1473 Fix Bootstrap.net assembly support
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.targets
Labels: needs-triage :mag:, area-DynamicDependencies

#1475 Update CsWinRT to 1.3.5
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#1471 Various fixes for the project templates
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/LockScreenLogo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/SplashScreen.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/Square150x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/Square44x44Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/StoreLogo.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Assets/Wide310x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Package-managed.appxmanifest
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/launchSettings.json
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WapProjTemplate.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/pch.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/readme.txt
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/LockScreenLogo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/SplashScreen.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/Square150x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/Square44x44Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/StoreLogo.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Assets/Wide310x150Logo.scale-200.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Package-native.appxmanifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj.filters
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.csproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/pch.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/readme.txt
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/pch.h
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/readme.txt
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/pch.h
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/readme.txt
Labels: needs-triage :mag:

#1476 Removed redundant lines due to bad merge
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage :mag:, area-Infrastructure

#1482 Remove VSEXT from Component VSIX
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
  dev/VSIX/Extension/Original/WindowsAppSDK.Extension.csproj
Labels: needs-triage :mag:

#1389 Fix default file inclusion of .RESW and image files in .NET projects
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.props
  dev/MRTCore/packaging/MrtCore.targets
Labels: area-Resources

#1483 Update Deployment API Implementation
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.WindowsAppSDK.Projection.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.WindowsAppSDK.xml
  dev/Common/TerminalVelocityFeatures-DeploymentAPI.h
  dev/Deployment/Deployment.idl
  dev/Deployment/Deployment.vcxitems
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
  dev/Deployment/DeploymentResult.cpp
  dev/Deployment/DeploymentResult.h
  dev/Deployment/DeploymentStatus.cpp
  dev/Deployment/DeploymentStatus.h
  dev/Deployment/PackageDefinitions.h
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
  test/Deployment/APITests.cpp
  test/Deployment/Deployment-Capabilities-AppxManifest.xml
  test/Deployment/Deployment-NoCapabilities-AppxManifest.xml
  test/Deployment/Deployment-RealNameFramework-AppxManifest.xml
  test/Deployment/DeploymentTests.vcxproj
  test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
  test/Deployment/pch.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Labels: needs-triage :mag:

#1485 Remove Experimental-ness from Deployment API
  dev/Common/TerminalVelocityFeatures-DeploymentAPI.xml
  dev/Deployment/Deployment.idl
  dev/Deployment/DeploymentManager.cpp
  test/Deployment/APITests.cpp
Labels: needs-triage :mag:, area-App deployment

#1491 Fix Helix tests failing to build because Microsoft.WindowsAppRuntime.Bootstrap.Net.dll is in Amd64
  build/CopyFilesToStagingDir.ps1
  build/ProjectReunion-BuildFoundation.yml
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Microsoft.WindowsAppRuntime.Bootstrap.Net.csproj
Labels: needs-triage :mag:

#1494 Update versions in preview2
  build/WindowsAppSDK-Versions.yml
Labels: needs-triage :mag:

#1495 Update WindowsAppSDK Version for branch
  build/WindowsAppSDK-Versions.yml
Labels: needs-triage :mag:

#1470 New pipeline to call TDBuild for VSIX Localization
  build/AzurePipelinesTemplates/WindowsAppSDK-CallTouchDownBuild-Steps.yml
  build/WindowsAppSDK-TDBuild.yml
Labels: area-Infrastructure

#1502 Set TDBuild to commit by default and refactor parameters
  build/AzurePipelinesTemplates/WindowsAppSDK-CallTouchDownBuild-Steps.yml
  build/WindowsAppSDK-TDBuild.yml
Labels: needs-triage :mag:

#1508 Update frameworkUDK to 22467.1004-210928-1420
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#1466 Overview and extension manifest for VSIX marketplace
  dev/VSIX/extension.manifest.json
  dev/VSIX/overview-experimental.md
  dev/VSIX/overview-stable.md
Labels: needs-triage :mag:

#1516 Update the "Microsoft.Internal.WinUI.Helix" package version to 0.5.4
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/Helix/packages.config
  test/WindowsAppSDK.Helix.TestCommon/WindowsAppSDK.Helix.TestCommon.csproj
Labels: needs-triage :mag:
