Repository microsoft/WindowsAppSDK, pull requests merged in 2021-11, with the labels that each got.

#1682 Update the experimental emojis and some basic readme content
  README.md
  docs/roadmap.md
Labels: needs-triage :mag:

#1701 Fix typos
  README.md
Labels: needs-triage :mag:

#1676 Notify the Shell when association data changes.
  dev/AppLifecycle/ActivationRegistrationManager.cpp
  dev/AppLifecycle/Association.cpp
  dev/AppLifecycle/Association.h
  dev/WindowsAppRuntime_DLL/pch.h
Labels: needs-triage :mag:

#1681 Unpackaged Windows App SDK app doesn't run on RS5/19H1
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  dev/Common/IsWindowsVersion.h
  dev/DynamicDependency/API/MddDetourPackageGraph.cpp
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj.filters
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/packages.config
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/pch.cpp
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/pch.h
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/winmain.cpp
  dev/UndockedRegFreeWinRT/urfw.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/framework.h
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Makefile.mak
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Microsoft.WindowsAppRuntime.Release!4.1.0
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest.xml
Labels: area-DynamicDependencies

#1704 Remove experimental tag from AppLifecycle feature. (#1517)
  dev/AppLifecycle/AppLifecycle.idl
Labels: needs-triage :mag:

#1707 Update WIL and CppWinRT versions
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/winmain.cpp
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/src/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/UnitTests/packages.config
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmex/packages.config
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.vcxproj
  dev/WindowsAppRuntime_MSIXInstallFromPath/main.cpp
  dev/WindowsAppRuntime_MSIXInstallFromPath/packages.config
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/packages.config
  installer/test/InstallerFunctionalTests/InstallerFunctionalTests.vcxproj
  installer/test/InstallerFunctionalTests/packages.config
  test/AppLifecycle/AppLifecycle.vcxproj
  test/AppLifecycle/packages.config
  test/Deployment/DeploymentTests.vcxproj
  test/Deployment/packages.config
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
  test/DynamicDependency/data/Framework.Widgets/Framework.Widgets.vcxproj
  test/DynamicDependency/data/Framework.Widgets/packages.config
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
  test/EnvironmentManagerTests/packages.config
  test/PowerNotifications/PowerNotifications.vcxproj
  test/PowerNotifications/packages.config
  test/PushNotificationTests/PushNotificationTests.vcxproj
  test/PushNotificationTests/packages.config
  test/TestApps/AppLifecycleTestApp/AppLifecycleTestApp.vcxproj
  test/TestApps/AppLifecycleTestApp/packages.config
  test/TestApps/ManualTestApp/ManualTestApp.vcxproj
  test/TestApps/ManualTestApp/packages.config
  test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
  test/TestApps/PushNotificationsDemoApp/packages.config
  test/TestApps/PushNotificationsTestApp/PushNotificationsTestApp.vcxproj
  test/TestApps/PushNotificationsTestApp/packages.config
Labels: needs-triage :mag:, area-Infrastructure

#1685 feat: Added global:: to MddBootstrapAutoInitializer.
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
Labels: needs-triage :mag:

#1706 Fix inline PowerShell to support multiple traceloggingconfig.h files from different WIL versions.
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
Labels: area-Infrastructure

#1672 Update bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#1544 Update Maestro eng/common
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  eng/common/AzurePipelinesTemplates/Maestro-EnforceDependencyMatching-Steps.yml
  eng/common/AzurePipelinesTemplates/Maestro-PublishBuildToMaestro-Steps.yml
  eng/common/MaestroHelpers.ps1
  eng/common/Scripts/ConvertVersionDetailsToPackageConfig.ps1
  eng/common/Scripts/MaestroGetRequest.ps1
  eng/common/Scripts/MaestroHelpers.ps1
  eng/common/Scripts/MaestroPostRequest.ps1
  eng/common/nuget.config
Labels: needs-triage :mag:

#1716 Unpackaged Windows App SDK app doesn't run on RS5/19H1 (#1681)
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  dev/Common/IsWindowsVersion.h
  dev/DynamicDependency/API/MddDetourPackageGraph.cpp
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj.filters
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/packages.config
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/pch.cpp
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/pch.h
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/winmain.cpp
  dev/UndockedRegFreeWinRT/urfw.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/framework.h
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Makefile.mak
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Microsoft.WindowsAppRuntime.Release!4.1.0
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest.xml
Labels: needs-triage :mag:, area-DynamicDependencies

#1718 Update CSWinRT
  dev/MRTCore/build/versions.props
  dev/MRTCore/global.json
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#1724 Update NuGet from 5.2.0 to 5.11.0
  build/AzurePipelinesTemplates/WindowsAppSDK-InstallNuget-Steps.yml
  build/build-mrt.yml
  build/publish-mrt.yml
Labels: needs-triage :mag:

#1728 Cherry pick: Unconditionally restore vsext to Dev16 VSIX (#1522)
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#1711 [Cherry-pick] Updating WinUI C# project templates to target .NET 6 when building in Dev17 (#1581)
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
  dev/VSIX/Extension/Directory.Build.targets
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
Labels: needs-triage :mag:

#1737 Fix x86 instancing appId generation.
  dev/AppLifecycle/Association.cpp
Labels: area-Lifecycle

#1736 [Cherry-Pick] Reunion VSIX: Update title of "Blank App, Packaged with WAP" project type (#1622)
  dev/VSIX/Extension/Cpp/Common/VSPackage.resx
  dev/VSIX/Extension/Cpp/Common/cs-CZ/VSPackage.cs-CZ.resx
  dev/VSIX/Extension/Cpp/Common/de-DE/VSPackage.de-DE.resx
  dev/VSIX/Extension/Cpp/Common/es-ES/VSPackage.es-ES.resx
  dev/VSIX/Extension/Cpp/Common/fr-FR/VSPackage.fr-FR.resx
  dev/VSIX/Extension/Cpp/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cpp/Common/ja-JP/VSPackage.ja-JP.resx
  dev/VSIX/Extension/Cpp/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cpp/Common/pl-PL/VSPackage.pl-PL.resx
  dev/VSIX/Extension/Cpp/Common/pt-BR/VSPackage.pt-BR.resx
  dev/VSIX/Extension/Cpp/Common/ru-RU/VSPackage.ru-RU.resx
  dev/VSIX/Extension/Cpp/Common/tr-TR/VSPackage.tr-TR.resx
  dev/VSIX/Extension/Cpp/Common/zh-CN/VSPackage.zh-CN.resx
  dev/VSIX/Extension/Cpp/Common/zh-TW/VSPackage.zh-TW.resx
  dev/VSIX/Extension/Cs/Common/VSPackage.resx
  dev/VSIX/Extension/Cs/Common/cs-CZ/VSPackage.cs-CZ.resx
  dev/VSIX/Extension/Cs/Common/de-DE/VSPackage.de-DE.resx
  dev/VSIX/Extension/Cs/Common/es-ES/VSPackage.es-ES.resx
  dev/VSIX/Extension/Cs/Common/fr-FR/VSPackage.fr-FR.resx
  dev/VSIX/Extension/Cs/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cs/Common/ja-JP/VSPackage.ja-JP.resx
  dev/VSIX/Extension/Cs/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cs/Common/pl-PL/VSPackage.pl-PL.resx
  dev/VSIX/Extension/Cs/Common/pt-BR/VSPackage.pt-BR.resx
  dev/VSIX/Extension/Cs/Common/ru-RU/VSPackage.ru-RU.resx
  dev/VSIX/Extension/Cs/Common/tr-TR/VSPackage.tr-TR.resx
  dev/VSIX/Extension/Cs/Common/zh-CN/VSPackage.zh-CN.resx
  dev/VSIX/Extension/Cs/Common/zh-TW/VSPackage.zh-TW.resx
Labels: needs-triage :mag:

#1742 Update to use new Main package Name MicrosoftCorporationII.WinAppRuntime.Main
  dev/Deployment/PackageDefinitions.h
Labels: needs-triage :mag:, area-App deployment

#1739 fix Hot Reload regression, incompatible with PublishReadyToRun
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-x86.pubxml
Labels: needs-triage :mag:

#1745 fix Hot Reload regression, incompatible with PublishReadyToRun (#1739)
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-x86.pubxml
Labels: needs-triage :mag:

#1751 IsLifetimeManagerViaEnumeration() always returned true
  dev/Common/IsWindowsVersion.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: area-DynamicDependencies

#1758 Update GetEnvironmentVariable()-succeeeded check
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: needs-triage :mag:, area-DynamicDependencies

#1764 Update bug report template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#1759 Update installer to support both publishing IDs used in App SDK.
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/PackageDefinitions.h
Labels: needs-triage :mag:

#1779 README / docs updates for productboard
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-proposal.md
  README.md
  docs/README.md
  docs/contributor-guide.md
  docs/roadmap.md
  specs/PushNotifications/PushNotifications-spec.md
Labels: needs-triage :mag:

#1783 Added MSIX license support
  installer/dev/WindowsAppRuntime-License.h
  installer/dev/WindowsAppRuntimeInstall.rc
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/WindowsAppRuntimeInstall.vcxproj.filters
  installer/dev/console.cpp
  installer/dev/console.h
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/main.cpp
  installer/dev/packages.h
  installer/dev/pch.cpp
  installer/dev/pch.h
  installer/dev/resource.h
  installer/dev/windowsappruntime_definitions.h
  installer/test/CreateInstallerTestPackages/Makefile.mak
  installer/test/CreateInstallerTestPackages/main_license.xml
Labels: needs-triage :mag:, area-App deployment, area-Infrastructure, area-Installer

#1793 Add Licensing API
  build/CopyFilesToStagingDir.ps1
  dev/Licensing/MsixLicensing.cpp
  dev/Licensing/MsixLicensing.h
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime-Licensing.cpp
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime-Licensing.h
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime.Bootstrap.def
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/framework.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
Labels: needs-triage :mag:, area-App deployment, area-Infrastructure, area-DynamicDependencies

#1799 conditionally reference experimental metadata
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Labels: needs-triage :mag:

#1798 Update README.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  README.md
Labels: needs-triage :mag:
