Repository microsoft/WindowsAppSDK, pull requests merged in 2021-02, with the labels that each got.

#417 Update roadmap.md
  docs/roadmap.md
Labels: needs-triage :mag:

#423 Updates requested by Andrew Clinick
  docs/roadmap.md
Labels: needs-triage :mag:

#425 Update roadmap.md
  docs/roadmap.md
Labels: needs-triage :mag:

#442 Add PushNotifications folder to the project
  ProjectReunion.sln
  dev/PushNotifications/PushNotifications.vcxitems
Labels: needs-triage :mag:

#451 Update README.md
  README.md
Labels: needs-triage :mag:

#463 Update FWP version registration
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
Labels: needs-triage :mag:

#460 add appx manifest to foundation transport package
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/NuSpecs/AppxManifest.xml
Labels: needs-triage :mag:

#459 Stop building ARM for ProjectReunion Foundation
  .github/workflows/build.yml
  build/AzurePipelinesTemplates/ProjectReunion-NugetReleaseTest-Job.yml
  build/AzurePipelinesTemplates/ProjectReunion-WACKTests-Job.yml
  build/NuSpecs/build-nupkg.ps1
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  dev/MRTCore/azure-pipelines.yml
Labels: needs-triage :mag:

#471 Introduce channel APIs
  dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
  dev/PushNotifications/ChannelResult.cpp
  dev/PushNotifications/ChannelResult.h
  dev/PushNotifications/PushManager.cpp
  dev/PushNotifications/PushManager.h
  dev/PushNotifications/PushNotifications.idl
  dev/PushNotifications/PushNotifications.vcxitems
Labels: needs-triage :mag:

#472 Use Framework UDK to get default resource path
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Helper.cpp
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
  dev/MRTCore/mrt/MrtCore.sln
Labels: needs-triage :mag:

#477 Make MRTCore work in framework package
  dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.References.targets
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
Labels: needs-triage :mag:

#480 Fix flakey builds on nuget restore
  build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
  dev/MRTCore/build-mrt.yml
  nuget.config
Labels: bug, infrastructure

#481 FWP for C#
  build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.props
  build/NuSpecs/ProjectReunion-Nuget-Native.props
  dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
Labels: needs-triage :mag:

#483 remove a condition
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.targets
Labels: needs-triage :mag:

#490 Update MRTCore to use the newest UDK
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Helper.cpp
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Labels: area-Resources

#487 Add project capability for VS telemtry
  build/NuSpecs/Microsoft.ProjectReunion.Foundation.targets
Labels: needs-triage :mag:

#484 Add CredScan and PostAnalysis for the Foundation Pipelines
  build/MSTest.cer
  build/MSTest.pfx
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
Labels: area-Security

#494 Add PR dependencies feed for Taef Nuget
  build/AzurePipelinesTemplates/ProjectReunion-RunHelixTests-Job.yml
  build/Helix/NuGet.config
  build/ProjectReunion-CI.yml
  dev/MRTCore/build-mrt.yml
  nuget.config
Labels: area-Infrastructure, needs-triage :mag:
