Repository microsoft/WindowsAppSDK, pull requests merged in 2022-09, with the labels that each got.

#2893 Runtime query'able version information API spec
  specs/VersionInfo/VersionInfo.md
Labels: needs-triage :mag:, area-App deployment

#2889 Runtime query'able version information
  WindowsAppRuntime.sln
  build/NuSpecs/AppxManifest.xml
  dev/Common/WindowsAppRuntime.VersionInfo.cpp
  dev/Common/WindowsAppRuntime.VersionInfo.h
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.ReleaseInfo.h
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.h
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  dev/VersionInfo/VersionInfo.vcxitems.filters
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  specs/VersionInfo/VersionInfo.md
  test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/VersionInfoTests.vcxproj.filters
  test/VersionInfo/packages.config
  test/VersionInfo/pch.cpp
  test/VersionInfo/pch.h
Labels: area-App deployment

#2907 Update for CsWinRT 2 - net6.0 and ILTrimming
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndPublishPGONuGet-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-MergePGD-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
  build/publish-mrt.yml
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Microsoft.WindowsAppRuntime.Bootstrap.Net.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  eng/Version.Details.xml
  eng/Versions.props
  test/Deployment/Test_DeploymentManagerAutoInitialize/CS/Test_DeploymentManagerAutoInitialize_CS_Default/Test_DeploymentManagerAutoInitialize_CS_Default.csproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CS/Test_DeploymentManagerAutoInitialize_CS_Options_Default/Test_DeploymentManagerAutoInitialize_CS_Options_Default.csproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CS/Test_DeploymentManagerAutoInitialize_CS_Options_Defined/Test_DeploymentManagerAutoInitialize_CS_Options_Defined.csproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CS/Test_DeploymentManagerAutoInitialize_CS_Options_None/Test_DeploymentManagerAutoInitialize_CS_Options_None.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Default/Test_BootstrapAutoInitialize_CS_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Default/Test_BootstrapAutoInitialize_CS_Options_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Defined/Test_BootstrapAutoInitialize_CS_Options_Defined.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_None/Test_BootstrapAutoInitialize_CS_Options_None.csproj
  test/WindowsAppSDK.Helix.Test.NetCore/WindowsAppSDK.Helix.Test.NetCore.csproj
  test/WindowsAppSDK.Helix.TestCommon/TestAssembly.cs
  test/WindowsAppSDK.Helix.TestCommon/WindowsAppSDK.Helix.TestCommon.csproj
Labels: needs-triage :mag:

#2947 Fix Duplicate ActivatableClass entries in appxmanifest
  build/NuSpecs/AppxManifest.xml
Labels: needs-triage :mag:

#2948 Checkout PRInternal Main instead of release/1.2-preview1
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
Labels: needs-triage :mag:

#2951 Fix whitespaces on previous merge
  dev/AppNotifications/AppNotificationActivatedEventArgs.h
  test/VersionInfo/pch.cpp
Labels: needs-triage :mag:

#2885 DeploymentInitializeOptions spec update
  specs/Deployment/DeploymentAPI.md
Labels: area-App deployment

#2769 Making EM fire events.
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.Insights.h
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.cpp
Labels: needs-triage :mag:

#2957 DeploymentManager Auto-Initializer: Incorporate API Review feedback
  build/NuSpecs/Microsoft.WindowsAppSDK.DeploymentManager.CS.targets
  build/NuSpecs/Microsoft.WindowsAppSDK.DeploymentManagerCommon.targets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.DeploymentManager.targets
  dev/Deployment/Deployment.idl
  dev/Deployment/DeploymentInitializeOptions.cpp
  dev/Deployment/DeploymentInitializeOptions.h
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManagerAutoInitializer.cpp
  dev/Deployment/DeploymentManagerAutoInitializer.cs
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Defined/Test_DeploymentManagerAutoInitialize_CPP_Options_Defined.vcxproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CS/Test_DeploymentManagerAutoInitialize_CS_Options_Defined/Test_DeploymentManagerAutoInitialize_CS_Options_Defined.csproj
Labels: area-App deployment

#2900 Refactor LRP tests for notifications
  WindowsAppRuntime.sln
  test/DynamicDependency/data/WindowsAppRuntime.Test.Singleton.Msix/appxmanifest.xml
  test/LRPTests/APITests.cpp
  test/LRPTests/LRPTests.vcxproj
  test/LRPTests/LRPTests.vcxproj.filters
  test/LRPTests/packages.config
  test/LRPTests/pch.cpp
  test/LRPTests/pch.h
  test/PushNotificationTests/PushNotification-Test-Constants.h
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/SplashScreen.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/Square150x150Logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/Square44x44Logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/Wide310x150Logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/Assets/logo.png
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/PushNotificationsLongRunningTask.Msix.vcxproj
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/appxmanifest.xml
  test/ToastNotificationTests/APITests.cpp
  test/ToastNotificationTests/ToastNotificationTests.vcxproj
  test/ToastNotificationTests/ToastNotificationTests.vcxproj.filters
  test/inc/TestDef.h
  test/inc/WindowsAppRuntime.Test.Package.h
Labels: needs-triage :mag:, area-Notifications

#2956 Adding product version info to WindowsAppRuntime.BootStrap.dll
  dev/Common/WindowsAppSDK-ProductInfo.h
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime.Bootstrap.rc
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj.filters
Labels: needs-triage :mag:

#2974 Fix WindowsAppSdkDeploymentManagerInitialize to default to true when WindowsPackageType=MSIX
  build/NuSpecs/Microsoft.WindowsAppSDK.DeploymentManagerCommon.targets
Labels: needs-triage :mag:, area-App deployment

#2979 Add SDK Build Tools package reference, for when full Windows SDK isn't installed
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
Labels: needs-triage :mag:

#2955 WinUI 3 new project templates have incorrect comment about OnLaunched
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.cpp
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/App.cpp
Labels: needs-triage :mag:

#2969 Unpackaged Custom Titlebar template Fix
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/app.manifest
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/app.manifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/app.manifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/app.manifest
Labels: needs-triage :mag:

#2954 Deployment Manager Repair API
  dev/Deployment/Deployment.idl
  dev/Deployment/DeploymentActivityContext.cpp
  dev/Deployment/DeploymentActivityContext.h
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
  dev/Deployment/DeploymentTraceLogging.h
  dev/Deployment/PackageDefinitions.h
  dev/DeploymentAgent/main.cpp
  dev/DeploymentAgent/tracelogging.h
Labels: feature, area-App deployment

#2849 Add Repair option to WinAppSDK Installer
  installer/dev/InstallActivityContext.cpp
  installer/dev/InstallActivityContext.h
  installer/dev/console.cpp
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/main.cpp
  installer/dev/tracelogging.cpp
  installer/dev/tracelogging.h
  installer/dev/windowsappruntime_definitions.h
  installer/test/CreateInstallerTestPackages/Makefile.mak
  installer/test/CreateTestPackages/TestPackage_Framework/TestPackage_Framework.vcxproj
  installer/test/CreateTestPackages/TestPackage_Framework/TestPackage_Framework.vcxproj.filters
  installer/test/CreateTestPackages/TestPackage_Framework/singleton_license.xml
  installer/test/CreateTestPackages/TestPackage_Singleton/TestPackage_Singleton.vcxproj
Labels: bug, area-Installer

#2975 Make the directory structure under specs match the directory structure under dev
  specs/AppNotifications/AppNotificationBuider/AppLogoOverrideImageExample.png
  specs/AppNotifications/AppNotificationBuider/AppNotificationBuilder-spec.md
  specs/AppNotifications/AppNotificationBuider/AppNotificationExample.png
  specs/AppNotifications/AppNotificationBuider/AppNotificationTextExample.png
  specs/AppNotifications/AppNotificationBuider/AppNotificationWithAvatarImage.png
  specs/AppNotifications/AppNotificationBuider/ButtonContextMenuExample.png
  specs/AppNotifications/AppNotificationBuider/ButtonExample.png
  specs/AppNotifications/AppNotificationBuider/ButtonSuccessExample.png
  specs/AppNotifications/AppNotificationBuider/ButtonToolTipExample.png
  specs/AppNotifications/AppNotificationBuider/ComboBoxExample.png
  specs/AppNotifications/AppNotificationBuider/CroppedAppLogoOverrideExample.png
  specs/AppNotifications/AppNotificationBuider/HeroImageExample.png
  specs/AppNotifications/AppNotificationBuider/IncomingCallExample.png
  specs/AppNotifications/AppNotificationBuider/IncomingCallSimpleExample.png
  specs/AppNotifications/AppNotificationBuider/InlineImageExample.png
  specs/AppNotifications/AppNotificationBuider/ProgressBarExample1.png
  specs/AppNotifications/AppNotificationBuider/ProgressBarExample2.png
  specs/AppNotifications/AppNotificationBuider/TextBoxExample.png
  specs/AppNotifications/AppNotificationBuider/TextExample.png
Labels: needs-triage :mag:, area-Notifications
