Repository microsoft/WindowsAppSDK, pull requests merged in 2022-07, with the labels that each got.

#2383 Process doc for develop branch
  docs/develop-branch.md
  docs/images/develop-branch-example.jpg
Labels: needs-triage :mag:

#2658 [AppLifecycle] Properly ignore cleanup event if it can't be opened.
  dev/AppLifecycle/AppInstance.cpp
Labels: needs-triage :mag:

#2723 WindowsAppRuntimeInstaller.exe fails if newer version present
  installer/dev/install.cpp
Labels: bug, area-Installer, servicing-consider-1.1

#2726 WindowsAppRuntimeInstaller.exe fails if newer version present
  installer/dev/install.cpp
Labels: bug, needs-triage :mag:, area-Installer, servicing-consider-1.1

#2737 Update Newtonsoft.Json explicit reference
  dev/VSIX/Extension/ProjectReunion.Extension.csproj
Labels: needs-triage :mag:

#2732 WindowsAppRuntimeInstaller.exe fails if newer version present
  installer/dev/install.cpp
Labels: bug, needs-triage :mag:, servicing-consider-1.0

#2734 XCOPY command should be <COPY> to ensure execution
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: bug, area-Infrastructure

#2751 Put AccessControl files into transport package
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
Labels: needs-triage :mag:

#2750 Remove noexcept from Bootstrapper API so it can be used from C
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
Labels: needs-triage :mag:, area-DynamicDependencies

#2757 Update bug version to 1.1.3
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#2758 <Copy> vs XCOPY.EXE -- Unbreak WindowsAppSDK-Nuget-Native.C.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: bug, needs-triage :mag:, area-Infrastructure

#2764 Updating reference to pick up license installation fix. (#2531)
  eng/Version.Details.xml
Labels: needs-triage :mag:

#2770 Update 0.8.11 tag in bug report
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#2733 FI develop into notification feature branch
  .github/ISSUE_TEMPLATE/bug-report.yaml
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/AppLifecycle/AppInstance.cpp
  dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
  eng/Version.Details.xml
  installer/dev/install.cpp
Labels: needs-triage :mag:

#2752 Fix AppNotification contract issues for IsSupported
  dev/AppNotifications/AppNotifications.idl
Labels: bug, needs-triage :mag:, area-Notifications

#2724 [1.1][AppLifecycle] Properly ignore cleanup event if it can't be opened.
  dev/AppLifecycle/AppInstance.cpp
Labels: needs-triage :mag:

#2794 Remove unused legacy VSIX and set IsProductComponent=true
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
  dev/VSIX/Extension/Directory.Build.targets
  dev/VSIX/Extension/Original/LICENSE
  dev/VSIX/Extension/Original/WindowsAppSDK.Extension.csproj
  dev/VSIX/Extension/Original/source.extension.vsixmanifest
  dev/VSIX/WindowsAppSDK.Extension.sln
Labels: needs-triage :mag:

#2798 Cherry Pick "User/sachinta/fix DeploymentManager's GetStatus (#2753)" to release/1.1-stable
  dev/Deployment/DeploymentManager.cpp
Labels: area-App deployment

#2786 AppNotificationBuilder features
  WindowsAppRuntime.sln
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.h
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.idl
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.vcxitems
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilderUtility.h
  dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.h
  dev/AppNotifications/AppNotificationBuilder/AppNotificationTextProperties.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationTextProperties.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  test/AppNotificationBuilderTests/APITests.cpp
  test/AppNotificationBuilderTests/AppNotificationBuilderTests.cpp
  test/AppNotificationBuilderTests/AppNotificationBuilderTests.h
  test/AppNotificationBuilderTests/AppNotificationBuilderTests.vcxproj
  test/AppNotificationBuilderTests/AppNotificationBuilderTests.vcxproj.filters
  test/AppNotificationBuilderTests/packages.config
  test/AppNotificationBuilderTests/pch.cpp
  test/AppNotificationBuilderTests/pch.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Labels: needs-triage :mag:, area-Notifications

#2648 AppNotificationContent Builder 1.2 spec
  specs/AppNotifications/AppNotificationContentSpec/AppLogoOverrideImageExample.png
  specs/AppNotifications/AppNotificationContentSpec/AppNotificationBuilder-spec.md
  specs/AppNotifications/AppNotificationContentSpec/AppNotificationExample.png
  specs/AppNotifications/AppNotificationContentSpec/AppNotificationTextExample.png
  specs/AppNotifications/AppNotificationContentSpec/AppNotificationWithAvatarImage.png
  specs/AppNotifications/AppNotificationContentSpec/ButtonContextMenuExample.png
  specs/AppNotifications/AppNotificationContentSpec/ButtonExample.png
  specs/AppNotifications/AppNotificationContentSpec/ButtonSuccessExample.png
  specs/AppNotifications/AppNotificationContentSpec/ButtonToolTipExample.png
  specs/AppNotifications/AppNotificationContentSpec/ComboBoxExample.png
  specs/AppNotifications/AppNotificationContentSpec/CroppedAppLogoOverrideExample.png
  specs/AppNotifications/AppNotificationContentSpec/HeroImageExample.png
  specs/AppNotifications/AppNotificationContentSpec/IncomingCallExample.png
  specs/AppNotifications/AppNotificationContentSpec/IncomingCallSimpleExample.png
  specs/AppNotifications/AppNotificationContentSpec/InlineImageExample.png
  specs/AppNotifications/AppNotificationContentSpec/ProgressBarExample1.png
  specs/AppNotifications/AppNotificationContentSpec/ProgressBarExample2.png
  specs/AppNotifications/AppNotificationContentSpec/TextBoxExample.png
  specs/AppNotifications/AppNotificationContentSpec/TextExample.png
Labels: needs-triage :mag:, area-Notifications, api-design
