Repository microsoft/WindowsAppSDK, pull requests merged in 2022-03, with the labels that each got.

#2184 Remove the Handled property from PushNotificationReceivedEventArgs
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotifications.idl
  test/TestApps/PushNotificationsDemoApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#2135 IsSelfContained()
  WindowsAppRuntime.sln
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/Microsoft.Utf8.h
  dev/Common/WindowsAppRuntime.SelfContained.cpp
  dev/Common/WindowsAppRuntime.SelfContained.h
  dev/DynamicDependency/API/DynamicDependency.vcxitems.filters
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTest.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_DLL/pch.h
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/SelfContained.md
  test/Common/Common.vcxproj
  test/Common/Common.vcxproj.filters
  test/Common/Test_SelfContained.cpp
  test/Common/Test_Utf8.cpp
  test/Common/packages.config
  test/Common/pch.cpp
  test/Common/pch.h
Labels: needs-triage :mag:, area-App deployment

#2189 FI main into WNP_ToastNotifications_L1
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/ProjectReunion-CI.yml
  build/build-mrt.yml
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/Microsoft.Utf8.h
  dev/Common/WindowsAppRuntime.SelfContained.cpp
  dev/Common/WindowsAppRuntime.SelfContained.h
  dev/DynamicDependency/API/DynamicDependency.vcxitems.filters
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTest.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_DLL/pch.h
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/SelfContained.md
  eng/Version.Details.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
  global.json
  test/Common/Common.vcxproj
  test/Common/Common.vcxproj.filters
  test/Common/Test_SelfContained.cpp
  test/Common/Test_Utf8.cpp
  test/Common/packages.config
  test/Common/pch.cpp
  test/Common/pch.h
Labels: needs-triage :mag:

#2193 install Windows SDK in build MRT
  build/build-mrt.yml
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
Labels: needs-triage :mag:

#2194 FI main into RI_WNP_ToastNotifications_L1
  build/build-mrt.yml
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
Labels: needs-triage :mag:

#2203 Address Bug in Registry access Read/Write operations
  build/NuSpecs/AppxManifest.xml
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationUtility.cpp
  dev/AppNotifications/AppNotificationUtility.h
  test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Labels: needs-triage :mag:, area-Notifications

#2201 DynamicDependencies: Added apicontract to WinRT types
  dev/DynamicDependency/API/M.AM.DynamicDependency.idl
Labels: feature, needs-triage :mag:, area-DynamicDependencies

#2199 Removing attribute to make EM non-experimental
  dev/Common/TerminalVelocityFeatures-EnvironmentManager.h
  dev/Common/TerminalVelocityFeatures-EnvironmentManager.xml
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.idl
Labels: needs-triage :mag:

#2069 Make IResourceManager and IResourceContext non-exclusive to the runtime classes
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.idl
Labels: needs-triage :mag:

#2131 publish MRTCore idl
  build/publish-mrt.yml
Labels: needs-triage :mag:

#2210 Try to fix Integration test breaking on nuspec version being invalid
  build/ProjectReunion-BuildFoundation.yml
  build/WindowsAppSDK-Versions.yml
Labels: needs-triage :mag:

#1675 Add Public API spec for Toast Notifications
  specs/PushNotifications/ToastNotifications-spec.md
Labels: needs-triage :mag:, area-Notifications

#2191 Add C++savvy API over Bootstrap's Flat-C API
  dev/Common/TerminalVelocityFeatures-DynamicDependency.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
  specs/dynamicdependencies/DynamicDependencies.md
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj.filters
  test/DynamicDependency/Test_Win32/TestMddBootstrapCppInitialize.cpp
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
Labels: feature, area-DynamicDependencies

#2211 Fix race condition and crash in AppInstance.FindOrRegisterForKey("key")
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/SharedMemory.h
Labels: needs-triage :mag:

#2196 Update PushNotifications-spec.md
  specs/PushNotifications/PushNotifications-spec.md
Labels: needs-triage :mag:, area-Notifications

#2046 Add telemetry to Installer
  installer/dev/InstallActivityContext.cpp
  installer/dev/InstallActivityContext.h
  installer/dev/Telemetry/MicrosoftTelemetry.h
  installer/dev/WindowsAppRuntime-License.h
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/WindowsAppRuntimeInstall.vcxproj.filters
  installer/dev/console.cpp
  installer/dev/console.h
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/main.cpp
  installer/dev/pch.h
  installer/dev/tracelogging.cpp
  installer/dev/tracelogging.h
Labels: feature, area-Installer

#2236 Fix missing quote in Installer vcxproj
  installer/dev/WindowsAppRuntimeInstall.vcxproj
Labels: needs-triage :mag:

#2145 Add basic telemetry to toast notification APIs
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationManager.h
  dev/AppNotifications/AppNotificationTelemetry.h
  dev/AppNotifications/AppNotifications.vcxitems
  dev/PushNotifications/PushNotificationTelemetry.h
Labels: needs-triage :mag:, area-Notifications

#2240 Fix LaunchLRP_FromCoCreateInstance test
  test/PushNotificationTests/LRPTests.cpp
Labels: needs-triage :mag:, area-Notifications

#2241 Remove an erroneous dangling Condition check from vcproj file
  installer/dev/WindowsAppRuntimeInstall.vcxproj
Labels: bug, area-Installer

#2243 Define RootRepo for the Installer Solution
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/pch.h
Labels: needs-triage :mag:

#2238 Default display name when no window handle available in Notifications
  dev/AppNotifications/AppNotificationUtility.cpp
  dev/AppNotifications/AppNotificationUtility.h
Labels: needs-triage :mag:, area-Notifications

#2134 Deployment API: Add DeploymentInitializeOptions with an option to force update WinAppSDK packages
  specs/Deployment/DeploymentAPI.md
Labels: area-App deployment, api-design

#2247 Add dtor to PushNotificationManager
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
Labels: needs-triage :mag:

#2205 Rename unique_package_dependency_context
  dev/DynamicDependency/API/M.AM.DD.PackageDependency.cpp
  dev/DynamicDependency/API/wil_msixdynamicdependency.h
  dev/WindowsAppRuntime_BootstrapDLL/wil_msixdynamicdependency.h
Labels: bug, needs-triage :mag:, area-DynamicDependencies

#2245 Revert try_create use as it breaks single instancing.
  dev/AppLifecycle/AppInstance.cpp
Labels: needs-triage :mag:

#2226 [MRT Core] Add support for VS's FastUpToDate check in MRT Core.
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/ProjectItemsSchema.xaml
Labels: area-MRTCore

#2248 Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: bug, area-DynamicDependencies, servicing-consider-1.0

#2187 Move wait handles to statics in class, add singleuse in the case of no handlers
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/ExtensionContract.h
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationManager.h
  dev/PushNotifications/GetNotificationEventArgs.h
  dev/PushNotifications/PushNotificationBackgroundTask.cpp
  dev/PushNotifications/PushNotificationBackgroundTask.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/externs.h
  specs/PushNotifications/ToastNotifications-spec.md
  specs/ToastNotifications/ToastNotifications-spec.md
  test/TestApps/PushNotificationsDemoApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#2256 Disable SBOM generation in the public builds
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/build-mrt.yml
Labels: needs-triage :mag:

#2255 [1.1-preview1] Revert try_create use as it breaks single instancing. (#2245)
  dev/AppLifecycle/AppInstance.cpp
Labels: needs-triage :mag:

#2258 Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0 (#2248)
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: area-DynamicDependencies, servicing-1.0.1

#2259 [CherryPick] Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: needs-triage :mag:

#2260 User/sachinta/add microsoft internal telemetry nuget package config
  installer/dev/Telemetry/MicrosoftTelemetry.h
  installer/dev/Telemetry/packages.config
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/WindowsAppRuntimeInstall.vcxproj.filters
  installer/dev/tracelogging.h
Labels: bug, needs-triage :mag:, area-Installer

#2257 Enabling projections for Environment Manager.
  dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
Labels: needs-triage :mag:

#2268 Fix bug in GetExeNameFromFilePath
  dev/PushNotifications/PushNotificationUtility.h
Labels: needs-triage :mag:

#2267 Add Selfcontained checks and misc fixes for race condition in AppNoti…
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationManager.h
  dev/AppNotifications/NotificationProperties.cpp
  dev/PushNotifications/PushNotificationCreateChannelResult.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/PushNotifications.idl
  specs/PushNotifications/PushNotifications-spec.md
  specs/ToastNotifications/ToastNotifications-spec.md
  test/TestApps/PushNotificationsTestApp/PushNotificationsTestApp.vcxproj
  test/TestApps/PushNotificationsTestApp/main.cpp
  test/TestApps/PushNotificationsTestApp/pch.h
Labels: needs-triage :mag:

#2110 User/dahoehna/api contracts
  specs/WinRT/WinRTAPIContracts.md
Labels: feature, area-Infrastructure, api-design

#2284 [0.8] Update to CsWinRT 1.6.1
  build/build-mrt.yml
  dev/MRTCore/build/DevCmd.cmd
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/UnpackagedTests/UnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
Labels: needs-triage :mag:

#2274 Use internal nuget feed for develop branch
  NuGet.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
  docs/pull_request_template.md
Labels: needs-triage :mag:

#2292 Add AppLifecycle contract
  dev/AppLifecycle/AppLifecycle.idl
Labels: needs-triage :mag:

#2289 Prevent WinUI item templates from showing up in other project types
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
Labels: needs-triage :mag:

#2306 Remove [experimental] tags take 2
  dev/AppNotifications/AppNotification.cpp
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationProgressData.cpp
  dev/AppNotifications/AppNotifications.idl
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationChannel.h
  dev/PushNotifications/PushNotificationCreateChannelResult.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotifications.idl
Labels: bug, needs-triage :mag:, area-Notifications

#2310 Add AppLifecycle contract (#2292)
  dev/AppLifecycle/AppLifecycle.idl
Labels: needs-triage :mag:

#2308 Remove [experimental] tags take 2 (#2306)
  dev/AppNotifications/AppNotification.cpp
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationProgressData.cpp
  dev/AppNotifications/AppNotifications.idl
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationChannel.h
  dev/PushNotifications/PushNotificationCreateChannelResult.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotifications.idl
Labels: bug, needs-triage :mag:, area-Notifications

#2309 Add contracts for PushNotifications
  dev/AppNotifications/AppNotifications.idl
  dev/PushNotifications/PushNotifications.idl
Labels: needs-triage :mag:, area-Notifications

#2279 Add ForceDeploy option to Installer and to Deployment API via the new DeploymentInitializeOptions runtime class
  dev/Deployment/Deployment.idl
  dev/Deployment/Deployment.vcxitems
  dev/Deployment/DeploymentInitializeOptions.cpp
  dev/Deployment/DeploymentInitializeOptions.h
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
  dev/PushNotifications/PushNotifications-Constants.h
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningPlatform-Startup.h
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/winmain.cpp
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.vcxproj
  dev/WindowsAppRuntime_MSIXInstallFromPath/main.cpp
  installer/dev/InstallActivityContext.cpp
  installer/dev/InstallActivityContext.h
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/console.cpp
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/main.cpp
  installer/dev/pch.h
  installer/dev/tracelogging.cpp
  installer/dev/tracelogging.h
  tools/GeneratePushNotificationsOverrides.ps1
Labels: feature, area-Installer

#2327 Add PRIResource build action to WPF projects.
  dev/MRTCore/packaging/MrtCore.PriGen.targets
Labels: area-MRTCore

#2318 Project template updates (Single-project MSIX Packaging and C++ toolset)
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
  dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/ProjectTemplate.vcxproj
Labels: needs-triage :mag:

#2330 Get Icon from process
  WindowsAppRuntime.sln
  dev/AppNotifications/AppNotificationUtility.cpp
  dev/AppNotifications/AppNotificationUtility.h
  dev/AppNotifications/AppNotifications.vcxitems
  dev/AppNotifications/WICUtility.cpp
  dev/AppNotifications/WICUtility.h
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.rc
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.vcxproj
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.vcxproj.filters
  test/TestApps/ToastNotificationsDemoApp/icon1.ico
  test/TestApps/ToastNotificationsDemoApp/main.cpp
  test/TestApps/ToastNotificationsDemoApp/resource.h
Labels: needs-triage :mag:, area-Notifications
