Repository microsoft/WindowsAppSDK, pull requests merged in 2022-10, with the labels that each got.

#3016 Fix Nuget Authentication Issues by forcing Nuget Update
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildSolution-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
Labels: needs-triage :mag:

#2898 Add MddGetPackageGraphRevisionId() + M.W.AM.DynamicDependency.PackageDependency.PackageGraphRevisionId API Spec
  specs/dynamicdependencies/DynamicDependencies.md
Labels: feature, area-DynamicDependencies, api-design

#3017 Use Maestro to Update FrameworkUDK
  NuGet.config
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/build-mrt.yml
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/MRTCore/mrt/MrtCore.sln
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
  eng/PackageReference/FrameworkUdk/Microsoft.FrameworkUdk.PackageReference.csproj
  eng/Version.Details.xml
  eng/Versions.props
Labels: needs-triage :mag:

#2986 Bug template tag updates for 1.1.5, 1.2-preview1, and 1.2-experimental2
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#3010 Add Repair option to WinAppSDK Installer (#2849)
  dev/Common/AppModel.Package.h
  installer/dev/InstallActivityContext.cpp
  installer/dev/InstallActivityContext.h
  installer/dev/console.cpp
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/main.cpp
  installer/dev/pch.h
  installer/dev/tracelogging.cpp
  installer/dev/tracelogging.h
  installer/dev/windowsappruntime_definitions.h
  installer/test/CreateInstallerTestPackages/Makefile.mak
  installer/test/CreateTestPackages/TestPackage_Framework/TestPackage_Framework.vcxproj
  installer/test/CreateTestPackages/TestPackage_Framework/TestPackage_Framework.vcxproj.filters
  installer/test/CreateTestPackages/TestPackage_Framework/singleton_license.xml
  installer/test/CreateTestPackages/TestPackage_Singleton/TestPackage_Singleton.vcxproj
Labels: bug, area-Installer

#2971 Adding mrtcore publishing to BuildTransportPackage.ps1
  BuildTransportPackage.ps1
Labels: needs-triage :mag:

#2909 Add MddGetPackageGraphRevisionId() and PackageGraphRevisionId property
  dev/Common/IsWindowsVersion.h
  dev/DynamicDependency/API/M.AM.DD.PackageDependency.cpp
  dev/DynamicDependency/API/M.AM.DD.PackageDependency.h
  dev/DynamicDependency/API/M.AM.DynamicDependency.idl
  dev/DynamicDependency/API/MddDetourPackageGraph.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/DynamicDependency/API/PackageGraphManager.cpp
  dev/DynamicDependency/API/PackageGraphManager.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.h
Labels: area-DynamicDependencies

#2938 Environment Manager is now RS5+. Tracking Registry writes is Windows 11+ and with better checks.
  BuildTransportPackage.ps1
  WindowsAppRuntime.sln
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.cpp
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.h
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.idl
  dev/EnvironmentManager/ChangeTracker/ChangeTracker.vcxitems
  dev/EnvironmentManager/ChangeTracker/EnvironmentVariableChangeTrackerHelper.h
  test/EnvironmentManagerTests/CentennialAppxManifest.pkg.xml
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.h
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj.filters
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerUWPTests.h
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.cpp
  test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.h
  test/PushNotificationTests/PushNotificationTests.vcxproj
Labels: needs-triage :mag:

#3048 Remove nuget.org from nuget.configs
  NuGet.config
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  installer/nuget.config
Labels: needs-triage :mag:

#2958 Unify payload RawNotification delivery object for packaged/unpackaged apps
  dev/PushNotifications/LongRunningProcessSourcedRawNotification.h
  dev/PushNotifications/LongRunningProcessSourcedTaskInstance.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
  dev/PushNotifications/PushNotificationReceivedEventArgs.h
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/PushNotifications.vcxitems
  test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
  test/TestApps/PushNotificationsDemoApp/main.cpp
  test/TestApps/PushNotificationsDemoApp/pch.h
Labels: needs-triage :mag:, area-Notifications

#3004 UrfwInitialize() fails if exe lacks a Fusion manifest
  dev/UndockedRegFreeWinRT/urfw.cpp
Labels: needs-triage :mag:, area-UndockedRegFreeWinRT

#3029 MRTCore take ms-resource URI
  dev/MRTCore/mrt/Core/src/MRM.cpp
  dev/MRTCore/mrt/Core/unittests/MrmTests.cpp
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/TestCommon/CommonTestCode.cs
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/UnitTest.cs
Labels: needs-triage :mag:

#3024 Fix Deployment when existing package is higher version and also telem…
  dev/Deployment/DeploymentActivityContext.cpp
  dev/Deployment/DeploymentActivityContext.h
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
  dev/Deployment/DeploymentTraceLogging.h
  dev/Deployment/PackageDefinitions.h
  dev/DeploymentAgent/main.cpp
  dev/DeploymentAgent/tracelogging.h
Labels: bug

#2359 Doc WinAppSDK's WinRT registration choice
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/WinRT-Registration.md
Labels: documentation, needs-triage :mag:, area-Infrastructure

#3062 Update pipelines to use BuildTransportPackage.ps1
  BuildTransportPackage.ps1
  DevCheck.cmd
  DevCheck.ps1
  Directory.Build.props
  MakeMsix.targets
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildDevProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateHelixProjFile-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-InstallNuget-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-MergePGD-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/build-mrt.yml
  build/publish-mrt.yml
  build/scripts/ConvertVersionDetailsToPackageConfig.ps1
  docs/Coding-Guidelines/GettingStarted.md
  tools/DevCheck.cmd
Labels: needs-triage :mag:

#3067 Authenticate NuGet Fix
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-InstallNuget-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
Labels: needs-triage :mag:

#3072 Make the VersionInfo API experimental
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/Common/TerminalVelocityFeatures-VersionInfo.h
  dev/Common/TerminalVelocityFeatures-VersionInfo.xml
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/pch.h
Labels: area-VersionInfo

#3073 User/mikehill/cp version info experimental
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  dev/Common/TerminalVelocityFeatures-VersionInfo.h
  dev/Common/TerminalVelocityFeatures-VersionInfo.xml
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/pch.h
Labels: needs-triage :mag:

#3075 Fix [experimental] should be [feature(Feature_Blah)]
  dev/VersionInfo/VersionInfo.idl
Labels: needs-triage :mag:, area-VersionInfo

#3077 [1.2-stable] Fix [experimental] should be [feature(Feature_Blah)]
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  dev/VersionInfo/VersionInfo.idl
Labels: needs-triage :mag:

#3027 Enable elevation for PushNotifications
  build/NuSpecs/AppxManifest.xml
  dev/AppNotifications/AppNotificationManager.cpp
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/Microsoft.RoApi.h
  dev/Deployment/DeploymentManager.cpp
  dev/PushNotifications/NotificationPlatformActivation.h
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/PushNotifications-Constants.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/PushNotificationsLongRunningTask.ProxyStub.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningPlatform-Startup.h
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/winmain.cpp
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.vcxproj
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/Microsoft.WindowsAppRuntime.Framework.vcxproj
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/DynamicDependency/data/WindowsAppRuntime.Test.Singleton.Msix/appxmanifest.xml
  test/LRPTests/APITests.cpp
  test/LRPTests/LRPTests.vcxproj
  test/TestApps/PushNotificationsDemoApp/main.cpp
  test/TestApps/PushNotificationsDemoApp/pch.h
Labels: needs-triage :mag:

#2906 Request from Rebecca Penick to update "ApplicationId" to "ObjectId"
  specs/PushNotifications/PushNotifications-spec.md
Labels: documentation, area-Notifications

#3084 FrameworkUDK 1.2.3-CI-25233.1000.221026-1354.0
  eng/Version.Details.xml
  eng/Versions.props
Labels: needs-triage :mag:

#3085 skip checks on bug template
  .github/workflows/build.yml
Labels: needs-triage :mag:

#3086 Remove en-us from links in README
  README.md
  docs/pull_request_template.md
Labels: needs-triage :mag:
