Repository microsoft/WindowsAppSDK, pull requests merged in 2022-12, with the labels that each got.

#3194 Revert "Make the VersionInfo API experimental (#3072)"
  dev/Common/TerminalVelocityFeatures-VersionInfo.h
  dev/Common/TerminalVelocityFeatures-VersionInfo.xml
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/pch.h
Labels: needs-triage :mag:

#3206 Add phone id to unblock store submission
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/Package-managed.appxmanifest
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Package-managed.appxmanifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/Package-managed.appxmanifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/Package-native.appxmanifest
Labels: needs-triage :mag:

#2545 Added 4+5 to preview/stable process
  docs/Coding-Guidelines/GitCheckinToMainPolicy.md
Labels: documentation

#3229 Update Newtonsoft.Json to 13.0.2
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#3231 [Cherrypick] Update Newtonsoft.Json to 13.0.2 (#3229)
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#3237 Update VSIX projects to specify Newtonsoft.Json Version
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#3238 [Cherrypick] Update VSIX projects to specify Newtonsoft.Json Version (#3237)
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#3171 Update to C++20
  WindowsAppSDK.Build.Cpp.props
Labels: area-Infrastructure

#3135 Plumbing CV from the LRP to the SDK
  build/NuSpecs/AppxManifest.xml
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.h
  dev/PushNotifications/PushNotificationTelemetry.h
  dev/PushNotifications/PushNotifications-Constants.h
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask/ForegroundSinkManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/ForegroundSinkManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationLongRunningTaskTelemetry.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/DynamicDependency/data/WindowsAppRuntime.Test.Singleton.Msix/appxmanifest.xml
  tools/GeneratePushNotificationsOverrides.ps1
Labels: area-Notifications

#3262 Cherry Pick Fixes to Main
  BuildAll.cmd
  BuildAll.ps1
  BuildTransportPackage.cmd
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build_all.cmd
  eng/Version.Details.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-CompilerImage.yml
  eng/common/DevCheck.cmd
  eng/common/DevCheck.ps1
  eng/common/README.md
  global.json
Labels: needs-triage :mag:

#3261 PR workflow was left behind with rename of solution and main branch
  .github/workflows/build.yml
Labels: needs-triage :mag:

#3279 Update Newtonsoft.Json explicit reference in VSIX projects
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#3271 Rename all references of ProjectReunionInternal to WindowsAppSDK Aggregator except for service connections
  eng/Version.Details.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
  eng/common/README.md
Labels: needs-triage :mag:

#3273 Rename all references of ProjectReunionInternal to WindowsAppSDK Aggregator except for service connections
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
Labels: needs-triage :mag:

#3272 Rename all references of ProjectReunionInternal to WindowsAppSDK Aggregator except for service connections
  eng/Version.Details.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
Labels: needs-triage :mag:

#3280 Rename references of ProjectReuionClosed to WindowsAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage :mag:

#3281 [Cherrypick] Rename references of ProjectReuionClosed to WindowsAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage :mag:

#3282 [Cherrypick] Rename references of ProjectReuionClosed to WindowsAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage :mag:

#3283 [Cherrypick] Rename references of ProjectReuionClosed to WindowsAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage :mag:
