Repository microsoft/WindowsAppSDK, pull requests merged in 2022-01, with the labels that each got.

#1947 Added header to MddBootstrapAutoInitializer.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
Labels: needs-triage :mag:, area-DynamicDependencies

#1963 Run the Foundation test suite from the Internal Integraiton tests
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#1964 FI main into WNP_ToastNotifications
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
  global.json
Labels: needs-triage :mag:

#1970 Forward integrate main into WNP_ToastNotifications
  build/ProjectReunion-BuildFoundation.yml
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
  global.json
Labels: needs-triage :mag:

#1983 User/erlangl/purifoypaul/arm64 build fix
  WindowsAppRuntime.sln
  test/TestApps/ToastNotificationsTestApp/ToastNotificationsTestApp.vcxproj
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/TestApps/ToastNotificationsTestApp/pch.cpp
  test/ToastNotificationTests/ToastNotificationTests.vcxproj
Labels: needs-triage :mag:, area-Notifications

#1979 Enable SBOM generation for WindowsAppSDK
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
Labels: needs-triage :mag:

#1984 Add ToastNotificationManger::Setting API
  dev/ToastNotifications/ToastNotificationManager.cpp
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/ToastNotificationTests/APITests.cpp
Labels: needs-triage :mag:

#1995 MddBootstrapInitialize package enumeration if release Minor version >0
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: needs-triage :mag:, area-DynamicDependencies

#1973 Add Foreground/Background handlers for ToastActivation
  dev/AppLifecycle/ActivationRegistrationManager.h
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/AppLifecycle.idl
  dev/AppLifecycle/ExtensionContract.h
  dev/PushNotifications/GetNotificationEventArgs.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/externs.h
  dev/ToastNotifications/ToastActivationCallback.h
  dev/ToastNotifications/ToastNotificationManager.cpp
  dev/ToastNotifications/ToastNotificationUtility.h
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/TestApps/ToastNotificationsTestAppPackage/Package.appxmanifest
  test/ToastNotificationTests/APITests.cpp
  test/inc/TestDef.h
Labels: needs-triage :mag:, area-Notifications

#1993 FI main into WNP_ToastNotifications_L1
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
  dev/VSIX/Extension/Cpp/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cpp/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cpp/Common/pt-BR/VSPackage.pt-BR.resx
  dev/VSIX/Extension/Cs/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cs/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cs/Common/pt-BR/VSPackage.pt-BR.resx
  eng/Version.Details.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
  global.json
Labels: needs-triage :mag:

#1997 FI WNP_ToastNotifications_L1into WNP_ToastNotifications_L2
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/build-mrt.yml
  dev/VSIX/Extension/Cpp/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cpp/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cpp/Common/pt-BR/VSPackage.pt-BR.resx
  dev/VSIX/Extension/Cs/Common/it-IT/VSPackage.it-IT.resx
  dev/VSIX/Extension/Cs/Common/ko-KR/VSPackage.ko-KR.resx
  dev/VSIX/Extension/Cs/Common/pt-BR/VSPackage.pt-BR.resx
  eng/Version.Details.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
  global.json
Labels: needs-triage :mag:

#1967 Add new font selection APIs to DWrite API spec
  specs/dwritecore/DWriteCore.md
Labels: needs-triage :mag:

#1134 AppLifecycle Restart API
  specs/AppLifecycle/Restart/restartApi.markdown
Labels: needs-triage :mag:

#1996 Implemented ToastNotification + unit tests
  dev/ToastNotifications/ToastNotification.cpp
  dev/ToastNotifications/ToastNotification.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/TestApps/ToastNotificationsTestApp/pch.h
  test/ToastNotificationTests/APITests.cpp
Labels: needs-triage :mag:, area-Notifications

#1989 Add MRTCore interface name and id
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.idl
Labels: needs-triage :mag:

#1976 Add ToastRegistration functions to PushNotificationsLongRunningTask
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask/ToastRegistrationManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/ToastRegistrationManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/pch.h
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.h
  dev/ToastNotifications/ToastNotificationManager.cpp
  dev/ToastNotifications/ToastNotificationUtility.cpp
  dev/ToastNotifications/ToastNotificationUtility.h
  test/PushNotificationTests/LRPTests.cpp
  test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
  test/TestApps/PushNotificationsDemoApp/main.cpp
  test/inc/TestDef.h
Labels: needs-triage :mag:, area-Notifications

#2012 Merge/Port 1.0 license support into main/1.1
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildDevProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/licensing.nuget.config
  build/scripts/ConvertVersionDetailsToPackageConfig.ps1
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
  dev/Deployment/PackageDefinitions.h
  dev/Licensing/Licensing.vcxitems
  dev/Licensing/MsixLicensing.cpp
  dev/Licensing/MsixLicensing.h
  dev/Licensing/WindowsAppRuntime-License.h
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime-Licensing.cpp
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime-Licensing.h
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj.filters
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  eng/Version.Details.xml
  installer/dev/WindowsAppRuntime-License.h
  installer/dev/WindowsAppRuntimeInstall.rc
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/WindowsAppRuntimeInstall.vcxproj.filters
  installer/dev/console.cpp
  installer/dev/console.h
  installer/dev/install.cpp
  installer/dev/install.h
  installer/dev/main.cpp
  installer/dev/packages.h
  installer/dev/pch.cpp
  installer/dev/pch.h
  installer/dev/resource.h
  installer/dev/windowsappruntime_definitions.h
  installer/test/CreateInstallerTestPackages/Makefile.mak
  installer/test/CreateTestPackages/TestPackage_Framework/TestPackage_Framework.vcxproj
  installer/test/CreateTestPackages/TestPackage_Framework/main_license.xml
Labels: needs-triage :mag:, area-Installer

#2019 Update to FrameworkUDK 1.1.0-CI-22541.1000.220124-0934.0
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#2021 Exclude "CsWinRT.Dependency*" in version.details.xml from converting to package.config
  build/ProjectReunion-BuildFoundation.yml
  build/scripts/ConvertVersionDetailsToPackageConfig.ps1
Labels: needs-triage :mag:

#2025 Bad merge fix missed copying main_license.xml to the testpackages directory
  installer/test/CreateTestPackages/TestPackage_Framework/TestPackage_Framework.vcxproj
Labels: needs-triage :mag:, area-Installer

#2015 Correct CsWinRTWindowsMetadata
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
  eng/Versions.props
Labels: needs-triage :mag:

#2005 Feature for sharing security descriptors (take 2)
  WindowsAppRuntime.sln
  build/NuSpecs/AppxManifest.xml
  dev/AccessControl/AccessControl.idl
  dev/AccessControl/AccessControl.vcxitems
  dev/AccessControl/GetSecurityDescriptorForAppContainerNames.cpp
  dev/AccessControl/Microsoft.Windows.Security.AccessControl.cpp
  dev/AccessControl/Microsoft.Windows.Security.AccessControl.h
  dev/AccessControl/Security.AccessControl.h
  dev/AccessControl/SecurityDescriptorHelpers.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  specs/GetSecurityDescriptorForAppContainerNames/GetSecurityDescriptorForAppContainerNames.md
  test/AccessControlTests/APITests.cpp
  test/AccessControlTests/AccessControlTests.vcxproj
  test/AccessControlTests/AccessControlTests.vcxproj.filters
  test/AccessControlTests/packages.config
  test/AccessControlTests/pch.cpp
  test/AccessControlTests/pch.h
  test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/TestApps/AccessControlTestApp/AccessControlTestApp.filters
  test/TestApps/AccessControlTestApp/AccessControlTestApp.vcxproj
  test/TestApps/AccessControlTestApp/main.cpp
  test/TestApps/AccessControlTestApp/packages.config
  test/TestApps/AccessControlTestApp/pch.cpp
  test/TestApps/AccessControlTestApp/pch.h
  test/TestApps/AccessControlTestAppPackage/AccessControlTestAppPackage.wapproj
  test/TestApps/AccessControlTestAppPackage/Images/LockScreenLogo.scale-200.png
  test/TestApps/AccessControlTestAppPackage/Images/SplashScreen.scale-200.png
  test/TestApps/AccessControlTestAppPackage/Images/Square150x150Logo.scale-200.png
  test/TestApps/AccessControlTestAppPackage/Images/Square44x44Logo.scale-200.png
  test/TestApps/AccessControlTestAppPackage/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  test/TestApps/AccessControlTestAppPackage/Images/StoreLogo.png
  test/TestApps/AccessControlTestAppPackage/Images/Wide310x150Logo.scale-200.png
  test/TestApps/AccessControlTestAppPackage/Package.appxmanifest
  test/inc/WindowsAppRuntime.Test.Package.h
Labels: needs-triage :mag:

#2033 [0.8] Update to CsWinRT 1.5.0-prerelease.220124.4
  dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
Labels: needs-triage :mag:

#2035 Reworded a password prompt for clarity
  tools/DevCheck.ps1
Labels: needs-triage :mag:, area-Infrastructure

#2038 Remove 19h1 and add 21H1 to Helix test queue.
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#2043 Update the Windows SDK version for RestartAgent
  dev/RestartAgent/RestartAgent.vcxproj
Labels: needs-triage :mag:

#2041 Fix push demo so packaged and unpackaged projects run properly
  test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
  test/TestApps/PushNotificationsDemoApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#2028 Moving Intellisense files to single location
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/NuSpecs/Intellisense/Microsoft.Windows.AppLifecycle.Projection.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.AppLifecycle.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.DynamicDependency.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.WindowsAppSDK.Projection.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.ApplicationModel.WindowsAppSDK.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.PushNotifications.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.System.Power.Projection.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.System.Power.xml
  build/NuSpecs/Intellisense/Microsoft.Windows.System.xml
  build/publish-mrt.yml
  dev/MRTCore/packaging/Intellisense/Microsoft.Windows.ApplicationModel.Resources.Projection.xml
  dev/MRTCore/packaging/Intellisense/Microsoft.Windows.ApplicationModel.Resources.xml
Labels: needs-triage :mag:

#2037 RI WNP_ToastNotifications_L2 into WNP_ToastNotifications_L1
  dev/AppLifecycle/ActivationRegistrationManager.h
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/AppLifecycle.idl
  dev/AppLifecycle/ExtensionContract.h
  dev/PushNotifications/GetNotificationEventArgs.h
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/PushNotifications.vcxitems
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/NotificationsLongRunningProcess.idl
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
  dev/PushNotifications/PushNotificationsLongRunningTask/ToastRegistrationManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/ToastRegistrationManager.h
  dev/PushNotifications/PushNotificationsLongRunningTask/pch.h
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/platform.h
  dev/PushNotifications/externs.h
  dev/ToastNotifications/ToastNotification.cpp
  dev/ToastNotifications/ToastNotification.h
  dev/ToastNotifications/ToastNotificationManager.cpp
  dev/ToastNotifications/ToastNotificationUtility.cpp
  dev/ToastNotifications/ToastNotificationUtility.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/PushNotificationTests/LRPTests.cpp
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/TestApps/ToastNotificationsTestApp/pch.h
  test/ToastNotificationTests/APITests.cpp
  test/inc/TestDef.h
Labels: needs-triage :mag:, area-Notifications
