Repository microsoft/WindowsAppSDK, pull requests merged in 2022-04, with the labels that each got.

#2293 List of contracts across WinApSDK
  specs/WinRT/WinRTAPIContracts.md
Labels: feature, needs-triage :mag:

#2316 Rich information on Bootstrap initalization failure
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.CS.targets
  build/NuSpecs/Microsoft.WindowsAppSDK.BootstrapCommon.targets
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.targets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.Bootstrap.targets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Bootstrap.cs
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime.Bootstrap.def
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestMddBootstrapCppInitialize.cpp
Labels: needs-triage :mag:, area-DynamicDependencies

#2344 Add Agile flag
  dev/AppNotifications/AppNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.cpp
Labels: bug, needs-triage :mag:, area-Notifications

#2350 Return the payload if it was processed already.
  dev/AppNotifications/AppNotificationManager.cpp
  dev/PushNotifications/PushNotificationManager.cpp
Labels: bug, needs-triage :mag:, area-Notifications

#2295 Notifications assets full support
  WindowsAppRuntime.sln
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationUtility.cpp
  dev/AppNotifications/AppNotificationUtility.h
  dev/AppNotifications/AppNotifications.vcxitems
  dev/AppNotifications/ShellLocalization.cpp
  dev/AppNotifications/ShellLocalization.h
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/Microsoft.Foundation.String.h
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.rc
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.vcxproj
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.vcxproj.filters
  test/TestApps/ToastNotificationsDemoApp/icon1.ico
  test/TestApps/ToastNotificationsDemoApp/main.cpp
  test/TestApps/ToastNotificationsDemoApp/resource.h
Labels: needs-triage :mag:, area-Notifications

#2354 App considerations for Hybrid CRT - xcopyability
  docs/Coding-Guidelines/HybridCRT.md
Labels: needs-triage :mag:

#2357 Bootstrap: Fix doccomment
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
Labels: documentation, needs-triage :mag:, area-DynamicDependencies

#2358 Add missing '>' to Microsoft.WindowsAppSDK.Bootstrap.CS.targets
  build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.CS.targets
  build/ProjectReunion-CI.yml
Labels: needs-triage :mag:

#2351 Fix `Package.appxmanifest` not appearing in Solution Explorer when creating a new C++ project
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
Labels: needs-triage :mag:

#2368 Bootstrap AutoInitialize - Fix typos due to bad merge
  WindowsAppRuntime.sln
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/WindowsAppSDK-VersionInfo.h
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Default/Test_BootstrapAutoInitialize_CS_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Default/Test_BootstrapAutoInitialize_CS_Options_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Defined/Test_BootstrapAutoInitialize_CS_Options_Defined.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_None/Test_BootstrapAutoInitialize_CS_Options_None.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/WindowsAppSDK-VersionInfo.cs
Labels: area-DynamicDependencies

#2366 Remove the duplicate ToastNotifications-spec.md in spec\PushNotifications
  specs/PushNotifications/PushNotifications-spec.md
  specs/PushNotifications/ToastNotifications-spec.md
Labels: needs-triage :mag:, area-Notifications

#2249 Add API contract version to Deployment interface
  specs/Deployment/DeploymentAPI.md
Labels: api-design, area-Installer

#2362 Resolve issues where AppInstance.FindOrRegisterForKey("key") can return null.
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/AppInstance.h
Labels: needs-triage :mag:

#2369 Deleting SetDisplayNameAndIcon from test and demo apps
  test/TestApps/PushNotificationsDemoApp/main.cpp
  test/TestApps/ToastNotificationsTestApp/main.cpp
Labels: needs-triage :mag:, area-Notifications

#2376 [Cherrypick] Bootstrap AutoInitialize - Fix typos due to bad merge
  WindowsAppRuntime.sln
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/WindowsAppSDK-VersionInfo.h
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Default/Test_BootstrapAutoInitialize_CS_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Default/Test_BootstrapAutoInitialize_CS_Options_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Defined/Test_BootstrapAutoInitialize_CS_Options_Defined.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_None/Test_BootstrapAutoInitialize_CS_Options_None.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/WindowsAppSDK-VersionInfo.cs
Labels: needs-triage :mag:

#2377 FI from main to develop
  WindowsAppRuntime.sln
  build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.CS.targets
  build/ProjectReunion-CI.yml
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/AppInstance.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
  docs/Coding-Guidelines/HybridCRT.md
  eng/Version.Details.xml
  eng/Versions.props
  specs/Deployment/DeploymentAPI.md
  specs/PushNotifications/PushNotifications-spec.md
  specs/PushNotifications/ToastNotifications-spec.md
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/README.txt
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.filters
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/WindowsAppSDK-VersionInfo.h
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Default/Test_BootstrapAutoInitialize_CS_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Default/Test_BootstrapAutoInitialize_CS_Options_Default.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_Defined/Test_BootstrapAutoInitialize_CS_Options_Defined.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/Test_BootstrapAutoInitialize_CS_Options_None/Test_BootstrapAutoInitialize_CS_Options_None.csproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CS/WindowsAppSDK-VersionInfo.cs
Labels: needs-triage :mag:

#2379 Update FrameworkUDK To 1.1.2-CI-25087.1000.220401-1608.1
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#2367 Use .NET SDK's default inclusion support for Windows App SDK and remove our own broken solution.
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.props
Labels: area-MRTCore

#2375 Update WinRT contracts per specs\WinRT\WinRTAPIContracts.md
  dev/AccessControl/AccessControl.idl
  dev/AppNotifications/AppNotifications.idl
  dev/DynamicDependency/API/M.AM.DynamicDependency.idl
  dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.idl
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.idl
  dev/PowerNotifications/PowerNotifications.idl
  specs/WinRT/WinRTAPIContracts.md
Labels: needs-triage :mag:, area-Resources, area-DynamicDependencies, area-Security, area-Notifications, area-Power

#2374 [1.1-preview2] Resolve issues where AppInstance.FindOrRegisterForKey("key") can return null. (#2362)
  dev/AppLifecycle/AppInstance.cpp
  dev/AppLifecycle/AppInstance.h
Labels: needs-triage :mag:

#2381 [Chery-pick] Use .NET SDK's default inclusion support for Windows App SDK and remove our own broken solution.
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.props
Labels: area-MRTCore

#2384 Contracts: Add commit missed by previous PR
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.idl
Labels: needs-triage :mag:, area-Resources

#2380 Update FrameworkUDK To 1.1.2-CI-25087.1001.220410-1342.0
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#2396 Revert 'Use .NET SDK's default inclusion support for Windows App SDK and remove our own broken solution. (#2381)'
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.props
Labels: area-MRTCore

#2390 Update local path string
  dev/AppNotifications/ShellLocalization.cpp
  dev/AppNotifications/ShellLocalization.h
  test/TestApps/ToastNotificationsTestApp/ToastNotificationsTestApp.rc
  test/TestApps/ToastNotificationsTestApp/ToastNotificationsTestApp.vcxproj
  test/TestApps/ToastNotificationsTestApp/ToastNotificationsTestApp.vcxproj.filters
  test/TestApps/ToastNotificationsTestApp/icon1.ico
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/TestApps/ToastNotificationsTestApp/resource.h
  test/ToastNotificationTests/APITests.cpp
Labels: needs-triage :mag:, area-Notifications

#2393 [MRT Core] Set properties to get default file inclusion only if we're in a .NET project.
  dev/MRTCore/packaging/MrtCore.PriGen.targets
Labels: area-resourcemanagement

#2401 Push Notifications Telemetry Improvements
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationTelemetry.h
Labels: needs-triage :mag:, area-Notifications

#2417 FI 1.1-preview2 to main
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
Labels: needs-triage :mag:

#2389 Refactoring PushNotification unit tests
  test/DynamicDependency/data/WindowsAppRuntime.Test.Singleton.Msix/WindowsAppRuntime.Test.Singleton.Msix.vcxproj
  test/DynamicDependency/data/WindowsAppRuntime.Test.Singleton.Msix/appxmanifest.xml
  test/PushNotificationTests/APITests.cpp
  test/PushNotificationTests/BaseTestSuite.cpp
  test/PushNotificationTests/BaseTestSuite.h
  test/PushNotificationTests/LRPTests.cpp
  test/PushNotificationTests/PackagedTests.cpp
  test/PushNotificationTests/PackagedTests.h
  test/PushNotificationTests/PushNotification-Test-Constants.h
  test/PushNotificationTests/PushNotificationTests.vcxproj
  test/PushNotificationTests/PushNotificationTests.vcxproj.filters
  test/PushNotificationTests/PushNotifications-AppxManifest.xml
  test/PushNotificationTests/UnpackagedTests.cpp
  test/PushNotificationTests/UnpackagedTests.h
  test/PushNotificationTests/packages.config
  test/PushNotificationTests/pch.h
  test/TestApps/PushNotificationsTestApp/main.cpp
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/ToastNotificationTests/APITests.cpp
  test/ToastNotificationTests/AppNotification-Test-Constants.h
  test/ToastNotificationTests/ToastNotificationTests.vcxproj
  test/ToastNotificationTests/ToastNotificationTests.vcxproj.filters
  test/inc/TestDef.h
  test/inc/WindowsAppRuntime.Test.Bootstrap.h
Labels: area-Notifications

#2424 Under a .NET SDK version check, bring back our (broken) default file inclusion solution for RESW and image files (applies to non-single project MSIX apps only).
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
  build/publish-mrt.yml
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.props
Labels: area-resourcemanagement

#2428 add end dev library adoption section, link to community call
  docs/Coding-Guidelines/HybridCRT.md
Labels: needs-triage :mag:

#2411 Fix IsSelfContained() to lookup framework packagefamilyname at runtime
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/WindowsAppRuntime.SelfContained.cpp
  dev/Common/WindowsAppRuntime.SelfContained.h
  dev/Common/WindowsAppRuntime.VersionInfo.cpp
  dev/Common/WindowsAppRuntime.VersionInfo.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_Insights/WindowsAppRuntimeInsights.h
  docs/Coding-Guidelines/SelfContained.md
  test/Common/Test_SelfContained.cpp
  test/Common/pch.h
  test/PushNotificationTests/BaseTestSuite.cpp
  test/PushNotificationTests/pch.h
  test/TestApps/PushNotificationsTestApp/main.cpp
  test/TestApps/PushNotificationsTestApp/pch.h
Labels: bug

#2420 Fix compiler warnings
  installer/dev/install.cpp
Labels: needs-triage :mag:, area-Installer

#2436 Fix warning C4018 on x86
  dev/AppNotifications/AppNotificationUtility.h
Labels: needs-triage :mag:, area-Notifications

#2442 Trim Resource Id prefix from WINDOWSAPPRUNTIME_ to MSIX_
  installer/dev/WindowsAppRuntimeInstall.rc
  installer/dev/install.cpp
  installer/dev/packages.h
  installer/dev/windowsappruntime_definitions.h
Labels: bug, area-Installer

#2321 MddBootstrap Telemetry & TraceLogging
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.h
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj.filters
  dev/WindowsAppRuntime_BootstrapDLL/pch.h
Labels: feature, area-DynamicDependencies

#2446 [Ask mode approved] [Cherry-pick] Fix IsSelfContained() to lookup framework packagefamilyname at runtime
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/WindowsAppRuntime.SelfContained.cpp
  dev/Common/WindowsAppRuntime.SelfContained.h
  dev/Common/WindowsAppRuntime.VersionInfo.cpp
  dev/Common/WindowsAppRuntime.VersionInfo.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_Insights/WindowsAppRuntimeInsights.h
  docs/Coding-Guidelines/SelfContained.md
  test/Common/Test_SelfContained.cpp
  test/Common/pch.h
  test/PushNotificationTests/BaseTestSuite.cpp
  test/PushNotificationTests/pch.h
  test/TestApps/PushNotificationsTestApp/main.cpp
  test/TestApps/PushNotificationsTestApp/pch.h
Labels: bug, needs-triage :mag:
