Repository microsoft/WindowsAppSDK, pull requests merged in 2022-06, with the labels that each got.

#2562 39817966: [WinAppSDK 1.1] Unpackaged + self-contained Blank Project crashes at startup
  dev/UndockedRegFreeWinRT/catalog.cpp
Labels: area-UndockedRegFreeWinRT

#2571 Publish to Feed and Maestro if build is scheduled or PublishPackage is true
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#2560 Remove Timestamp from VSIX version due to WinAppSDK NuGet Version Update
  dev/VSIX/Extension/Directory.Build.targets
Labels: needs-triage :mag:

#2557 Refactor register API
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationManager.h
  dev/AppNotifications/AppNotificationUtility.cpp
  dev/AppNotifications/AppNotificationUtility.h
Labels: needs-triage :mag:, area-Notifications

#2584 Update readme for 1.1.0
  README.md
Labels: needs-triage :mag:

#2458 Update maestro docs. Added a note about dotnet default values.
  docs/EngineeringSystem/WinAppSDK-Maestro.md
Labels: needs-triage :mag:

#2537 UndockedRegFreeWinRT: RoGetMetaDataFile() fix for 1.1-servicing
  WindowsAppRuntime.sln
  dev/UndockedRegFreeWinRT/typeresolution.cpp
Labels: bug, area-UndockedRegFreeWinRT

#2588 Cherry-pick fix for break away process creation attribute from release/1.1-stable to main
  dev/Deployment/DeploymentActivityContext.h
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.h
  installer/dev/InstallActivityContext.cpp
  installer/dev/InstallActivityContext.h
  installer/dev/install.cpp
  installer/dev/main.cpp
  installer/dev/tracelogging.cpp
  installer/dev/tracelogging.h
Labels: bug, area-App deployment

#2599 Fix issue where WinUI C# and C++ item templates are not appearing in WinUI projects
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
Labels: needs-triage :mag:

#2544 Making EM RS5+. Limiting the tracking capability to Windows11+ (Spec)
  specs/AppLifecycle/EnvironmentVariables/AppLifecycle - Environment Variables (EV).md
Labels: area-Lifecycle, api-design, servicing-consider-1.1

#2610 Create a pipeline to automate FIs from main to develop
  build/WindowsAppSDK-MergeMainToDevelop.yml
Labels: needs-triage :mag:

#2611 Update App Licensing to 1.0.0-preview1.20220610.4
  eng/Version.Details.xml
Labels: needs-triage :mag:

#2608 v1.1 SDK throws an access violation from MddBootstrapInitialize's logging code if no matching packages are installed #2592
  WindowsAppRuntime.sln
  dev/Common/WindowsAppRuntime.SelfContained.cpp
  dev/Common/WindowsAppRuntime.VersionInfo.cpp
  dev/Common/WindowsAppRuntime.VersionInfo.h
  dev/DynamicDependency/API/DataStore.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/DynamicDependency/API/pch.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTest.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.cpp
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/framework.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
  dev/WindowsAppRuntime_DLL/pch.h
  test/Common/Test_SelfContained.cpp
  test/Deployment/Deployment-RealNameFramework-AppxManifest.xml
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestPackages.cpp
  test/DynamicDependency/Test_Win32/TestPackages.h
  test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
  test/DynamicDependency/Test_Win32/Test_LifetimeManagement.cpp
  test/DynamicDependency/Test_Win32/Test_Win32.cpp
  test/DynamicDependency/Test_WinRT/TestPackages.cpp
  test/DynamicDependency/Test_WinRT/TestPackages.h
  test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
  test/DynamicDependency/data/DynamicDependency.DataStore.Msix/appxmanifest.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest-arm64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest-x64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest-x86.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest-arm64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest-x64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest-x86.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest-arm64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest-x64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest-x86.xml
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/DynamicDependency/data/WindowsAppRuntime.Test.Singleton.Msix/appxmanifest.xml
  test/EnvironmentManagerTests/AppxManifest.pkg.xml
  test/EnvironmentManagerTests/CentennialAppxManifest.pkg.xml
  test/PowerNotifications/PowerNotifications-AppxManifest.xml
  test/PushNotificationTests/BaseTestSuite.cpp
  test/PushNotificationTests/PushNotifications-AppxManifest.xml
  test/PushNotifications/PushNotificationsLongRunningTask.Msix/appxmanifest.xml
  test/TestApps/AccessControlTestAppPackage/Package.appxmanifest
  test/TestApps/AppLifecycleTestApp/Helpers.cpp
  test/TestApps/AppLifecycleTestPackage/Package.appxmanifest
  test/TestApps/ManualTestApp/main.cpp
  test/TestApps/PushNotificationsDemoApp/main.cpp
  test/TestApps/PushNotificationsDemoPackage/Package.appxmanifest
  test/TestApps/PushNotificationsTestApp/main.cpp
  test/TestApps/PushNotificationsTestAppPackage/Package.appxmanifest
  test/TestApps/ToastNotificationsDemoApp/main.cpp
  test/TestApps/ToastNotificationsDemoAppPackage/Package.appxmanifest
  test/TestApps/ToastNotificationsDemoPackage/Package.appxmanifest
  test/TestApps/ToastNotificationsTestAppPackage/Package.appxmanifest
  test/inc/WindowsAppRuntime.Test.Bootstrap.h
  test/inc/WindowsAppRuntime.Test.Metadata.h
  test/inc/WindowsAppRuntime.Test.Package.h
Labels: bug, needs-triage :mag:, area-DynamicDependencies, servicing-consider-1.1

#2623 Detoured GetCurrentPackageInfo3() should route to the OS any PackageInfoType value it doesn't handle
  dev/DynamicDependency/API/MddDetourPackageGraph.cpp
  dev/DynamicDependency/API/MddDetourPackageGraph.h
  dev/DynamicDependency/API/PackageGraphManager.cpp
Labels: bug, area-DynamicDependencies

#2636 Overhaul NuGet versions to include "main" or "develop"
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
  build/WindowsAppSDK-CommonVariables.yml
  build/WindowsAppSDK-Versions.yml
Labels: needs-triage :mag:

#2638 Some old MSTest.pfx references were lingering (and now breaking things)
  test/TestApps/AccessControlTestAppPackage/AccessControlTestAppPackage.wapproj
  test/TestApps/ToastNotificationsDemoPackage/ToastNotificationsDemoPackage.wapproj
Labels: bug, area-Security, area-Notifications

#2565 Installation with System-Account doesn't work #2546
  dev/Common/Security.User.h
  dev/Deployment/DeploymentActivityContext.cpp
  dev/Deployment/DeploymentActivityContext.h
  dev/Deployment/DeploymentManager.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.cpp
  installer/dev/InstallActivityContext.cpp
  installer/dev/InstallActivityContext.h
  installer/dev/console.cpp
  installer/dev/install.cpp
  installer/dev/main.cpp
  installer/dev/pch.h
  installer/dev/tracelogging.cpp
  test/Common/Common.vcxproj
  test/Common/Common.vcxproj.filters
  test/Common/Test_Security_User.cpp
  test/Common/pch.h
Labels: bug, area-Installer, servicing-consider-1.1

#2569 Add <auto-generated> tag in C# files added to projects #2533 (servicing 1.1)
  dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Bootstrap.cs
  dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
Labels: bug, needs-triage :mag:, area-Infrastructure, area-DynamicDependencies, area-UndockedRegFreeWinRT, servicing-consider-1.1

#2640 Fix the .NET SDK installer script used by MRT Core, and don't run the script anymore
  build/build-mrt.yml
  dev/MRTCore/build/DownloadDotNetCoreSdk.ps1
  dev/MRTCore/global.json
Labels: needs-triage :mag:

#2641 [Cherry-pick][1.1 servicing] Fix issue where WinUI C# and C++ item templates are not appearing in WinUI projects
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
Labels: needs-triage :mag:

#2627 Add 1.1.1 & 1.0.4 to bug template and remove outdated versions
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#2662 Update Newtonsoft.Json explicit reference in Dev16 extension projects
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#2663 Update Newtonsoft.Json explicit reference in Dev16 projects
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#2660 User/erlangl/fi develop into feature
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Labels: needs-triage :mag:

#2688 add explicit Newtonsoft.Json reference
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
Labels: needs-triage :mag:

#2596 Introduce Register Overload for assets
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationManager.h
  dev/AppNotifications/AppNotificationUtility.cpp
  dev/AppNotifications/AppNotificationUtility.h
  dev/AppNotifications/AppNotifications.idl
  dev/AppNotifications/ShellLocalization.cpp
  dev/AppNotifications/ShellLocalization.h
  specs/AppNotifications/AppNotifications-spec.md
  test/TestApps/ToastNotificationsTestApp/main.cpp
  test/ToastNotificationTests/APITests.cpp
Labels: needs-triage :mag:, area-Notifications
