Repository microsoft/WindowsAppSDK, pull requests merged in 2022-11, with the labels that each got.

#3093 Microsoft.WindowsAppRuntime.dll!DllMain fails if exe has resources but no SxS manifest
  dev/UndockedRegFreeWinRT/urfw.cpp
Labels: area-UndockedRegFreeWinRT, needs-triage :mag:

#3104 Revert "Make the VersionInfo API experimental (#3072)"
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/Common/TerminalVelocityFeatures-VersionInfo.h
  dev/Common/TerminalVelocityFeatures-VersionInfo.xml
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/pch.h
Labels: needs-triage :mag:

#3113 Update App Licensing Package to 1.2.0-main.20221103.4
  eng/Version.Details.xml
Labels: needs-triage :mag:

#3114 Update cppwinrt for ComponentConnectorT build error fix
  dev/VSIX/Directory.Build.props
Labels: needs-triage :mag:

#3120 Allow WinAppSDK Project Templates VSIX to be installed on ARM64
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#3121 [Cherry-pick] Allow WinAppSDK Project Templates VSIX to be installed on ARM64
  dev/VSIX/Directory.Build.props
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#3123 Enable auto TSA bug filing
  .config/tsaoptions.json
  build/AzurePipelinesTemplates/WindowsAppSDK-BinaryAnalysis-steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SourceAnalysis-job.yml
Labels: needs-triage :mag:

#3118 Introducing WIL activities in the App Notification Builder
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilderTelemetry.h
  dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationComboBox.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationProgressBar.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationTextProperties.cpp
  dev/Common/NotificationTelemetryHelper.h
  dev/PushNotifications/externs.h
Labels: area-Notifications

#3127 Introducing WIL activities for AppNotifications
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationTelemetry.h
  test/AppNotificationTests/AppNotifications.Test.h
  test/AppNotificationTests/UnpackagedTests.cpp
Labels: area-Notifications

#3130 Updated areaPath and codebaseName in TsaOptions.json
  .config/tsaoptions.json
Labels: needs-triage :mag:

#3134 1.2 readme updates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  README.md
Labels: documentation, needs-triage :mag:

#3131 Introducing WIL activities for Push Notifications
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilderTelemetry.h
  dev/AppNotifications/AppNotificationTelemetry.h
  dev/Common/NotificationTelemetryHelper.h
  dev/PushNotifications/PushNotificationChannel.cpp
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationTelemetry.h
Labels: area-Notifications

#3154 Fix StripSymbols Script and Remove Unused Yml
  build/AzurePipelinesTemplates/WindowsAppSDK-ProduceStrippedSymbols-Steps.yml
  build/StripSymbols.ps1
Labels: needs-triage :mag:

#3155 Update bug report template to 1.2.1
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: documentation

#3094 Fixed minor phrasing missed in previous PR 2359
  docs/Coding-Guidelines/WinRT-Registration.md
Labels: documentation

#3169 Fix dependencies and bad merge
  WindowsAppRuntime.sln
  dev/DeploymentAgent/DeploymentAgent.vcxproj
  dev/DeploymentAgent/packages.config
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/src/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/UnitTests/packages.config
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmex/packages.config
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/RestartAgent/RestartAgent.vcxproj
  dev/RestartAgent/packages.config
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/packages.config
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.vcxproj
  dev/WindowsAppRuntime_MSIXInstallFromPath/packages.config
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/dev/packages.config
  installer/test/InstallerFunctionalTests/InstallerFunctionalTests.vcxproj
  installer/test/InstallerFunctionalTests/packages.config
  test/AccessControlTests/AccessControlTests.vcxproj
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
  test/LRPTests/LRPTests.vcxproj
Labels: area-Infrastructure, needs-triage :mag:

#3172 Update WindowsAppSDK.Build.Cpp.props to add /Qspectre flag
  WindowsAppSDK.Build.Cpp.props
Labels: needs-triage :mag:

#3170 Fix Various Issues in the BuildTransportPackage.ps1
  BuildTransportPackage.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  docs/Coding-Guidelines/TerminalVelocity.md
Labels: needs-triage :mag:

#3183 Update WindowsAppSDK-ProductInfo.h release = 1.3
  dev/Common/WindowsAppSDK-ProductInfo.h
Labels: area-Infrastructure, needs-triage :mag:

#3195 Update DynamicDependencies\Test_Win* dependencies to prevent out-of-order builds
  DevCheck.cmd
  WindowsAppRuntime.sln
Labels: bug, area-DynamicDependencies, needs-triage :mag:
