Repository microsoft/WindowsAppSDK, pull requests merged in 2023-04, with the labels that each got.

#3552 Fix Version Info Experimental
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
Labels: needs-triage :mag:

#3560 ADO bug 43814738 - Fixed call to deprecated NuGetAuthenticate
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
Labels: needs-triage :mag:

#3571 Disable BuildMRT in public CI builds
  build/ProjectReunion-CI.yml
  dev/MRTCore/mrt/Core/unittests/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/packages.config
  dev/MRTCore/mrt/mrm/UnitTests/packages.config
  eng/Version.Dependencies.xml
  installer/test/InstallerFunctionalTests/packages.config
  test/AccessControlTests/packages.config
  test/AppLifecycle/packages.config
  test/AppNotificationBuilderTests/packages.config
  test/AppNotificationTests/packages.config
  test/Common/packages.config
  test/Deployment/API/packages.config
  test/DynamicDependency/Test_Win32/packages.config
  test/DynamicDependency/Test_WinRT/packages.config
  test/EnvironmentManagerTests/packages.config
  test/Kozani/KozaniAppGraphTests/packages.config
  test/Kozani/KozaniHostRuntimeTests/packages.config
  test/Kozani/KozaniManagerRuntimeTests/packages.config
  test/Kozani/KozaniManagerTests/packages.config
  test/Kozani/KozaniPackageTests/packages.config
  test/Kozani/KozaniRemoteManagerTests/packages.config
  test/Kozani/KozaniSendToLocalTests/packages.config
  test/Kozani/KozaniSendToRemoteTests/packages.config
  test/Kozani/KozaniSettingsTests/packages.config
  test/Kozani/MakeMSIXTests/packages.config
  test/LRPTests/packages.config
  test/PowerNotifications/packages.config
  test/PushNotificationTests/packages.config
  test/TestApps/AccessControlTestApp/packages.config
  test/TestApps/AppLifecycleTestApp/packages.config
  test/TestApps/ManualTestApp/packages.config
  test/TestApps/PushNotificationsDemoApp/packages.config
  test/TestApps/PushNotificationsTestApp/packages.config
  test/TestApps/ToastNotificationsDemoApp/packages.config
  test/TestApps/ToastNotificationsTestApp/packages.config
  test/VersionInfo/packages.config
  tools/ProjectTemplates/test.cpp.dll.taef/packages.config
Labels: needs-triage :mag:

#3574 ADO b#44156775 - Updated versions of some tasks
  build/ProjectReunion-CI.yml
Labels: needs-triage :mag:

#3564 resolving license confusion
  LICENSE
  LICENSE-CODE
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
  dev/VSIX/Extension/LICENSE
Labels: needs-triage :mag:

#3578 AppLifecycle: Add tests to the pipeline test runs
  test/AppLifecycle/AppLifecycle.testdef
  test/AppLifecycle/AppLifecycle.vcxproj
Labels: area-Lifecycle, area-Infrastructure, needs-triage :mag:

#3581 User/alexlam/43856157 dev 20230417
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-job.yml
Labels: needs-triage :mag:

#2335 Updated Bootstrapper spec for MddBootstrapIntialize2(...options)
  specs/dynamicdependencies/DynamicDependencies.md
Labels: documentation, area-DynamicDependencies

#3593 44283881 Installer fails to build ARM64 (CETCOMPAT=true not compatible)
  installer/dev/WindowsAppRuntimeInstall.vcxproj
Labels: area-Infrastructure

#3596 Resolve Nuget install error when creating new C++ project using WinAppSDK 1.3 VSIX
  NuGet.config
  eng/common/nuget.config
Labels: needs-triage :mag:

#3598 [Cherry-pick] Resolve Nuget install error when creating new C++ project using WinAppSDK 1.3 VSIX
  NuGet.config
  eng/common/nuget.config
Labels: servicing-consider
