Repository microsoft/WindowsAppSDK, pull requests merged in 2023-05, with the labels that each got.

#3612 Move William's KozaniHostRuntime change to Ruke's branch
  WindowsAppRuntime.sln
  dev/Kozani/KozaniHostRuntime/framework.h
  dev/Kozani/KozaniHostRuntime/main.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/JustDoIt.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/JustDoIt.h
  test/Kozani/KozaniHostRuntimeTestPackage/KozaniHostRuntimeTestPackage.vcxproj
  test/Kozani/KozaniHostRuntimeTestPackage/KozaniHostRuntimeTestPackage.vcxproj.filters
  test/Kozani/KozaniHostRuntimeTestPackage/appxmanifest.xml
  test/Kozani/KozaniHostRuntimeTestPackage/dllmain.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/logo.png
  test/Kozani/KozaniHostRuntimeTestPackage/module.def
  test/Kozani/KozaniHostRuntimeTestPackage/packages.config
  test/Kozani/KozaniHostRuntimeTestPackage/pch.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/pch.h
  test/Kozani/KozaniHostRuntimeTestPackage/targetver.h
Labels: needs-triage :mag:

#3613 Merge Kozani HostRuntime change to latest branch
  WindowsAppRuntime.sln
  dev/Kozani/KozaniHostRuntime/framework.h
  dev/Kozani/KozaniHostRuntime/main.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/JustDoIt.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/JustDoIt.h
  test/Kozani/KozaniHostRuntimeTestPackage/KozaniHostRuntimeTestPackage.vcxproj
  test/Kozani/KozaniHostRuntimeTestPackage/KozaniHostRuntimeTestPackage.vcxproj.filters
  test/Kozani/KozaniHostRuntimeTestPackage/appxmanifest.xml
  test/Kozani/KozaniHostRuntimeTestPackage/dllmain.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/logo.png
  test/Kozani/KozaniHostRuntimeTestPackage/module.def
  test/Kozani/KozaniHostRuntimeTestPackage/packages.config
  test/Kozani/KozaniHostRuntimeTestPackage/pch.cpp
  test/Kozani/KozaniHostRuntimeTestPackage/pch.h
  test/Kozani/KozaniHostRuntimeTestPackage/targetver.h
Labels: needs-triage :mag:

#3587 Convert Foundation Build Pipelines to OneBranch
  BuildAll.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-BinaryAnalysis-steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndPublishPGONuGet-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildSolution-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-InstallNuget-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-InstallWindowsSDK-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackNuget-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PopulateBuildDateAndRevision-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SourceAnalysis-job.yml
  build/ProjectReunion-BuildFoundation-Weekly.yml
  build/ProjectReunion-BuildFoundation.yml
  build/WindowsAppSDK-CommonVariables.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-PR.yml
  build/WindowsAppSDK-Foundation-Release.yml
  build/scripts/Install-WindowsSdkISO.ps1
  build/scripts/windows-sdk.ps1
  dev/MRTCore/.gdn/mrt.gdnsuppress
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
Labels: needs-triage :mag:

#3618 Update Defaults for Nightly and Release
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Release.yml
Labels: needs-triage :mag:

#3621 Update bug-report.yaml to 1.3.1
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#3623 DevCheck ExitCode if issues detected. Fix dependencies
  DevCheck.ps1
  test/Kozani/KozaniManagerRuntimeTests/packages.config
Labels: area-Infrastructure

#3628 Fix Installer Stage Failing Because DevCheck Exit With Failure
  DevCheck.ps1
Labels: needs-triage :mag:

#3627 Update MRTCore ManagedTests to use TAEF and onboard it to Pipeline Tests
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
  build/ProjectReunion-CI.yml
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.testdef
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/UnitTest.cs
Labels: needs-triage :mag:

#3630 Update SyncMirror Pipeline to include 1.4-stable
  build/WindowsAppSDK-SyncMirroredRepository.yml
Labels: needs-triage :mag:

#3637 Don't break on binskim
  build/WindowsAppSDK-Foundation-Release.yml
Labels: needs-triage :mag:

#3599 Fix: FAIL_FAST_FATAL_APP_EXIT_c0000409_Microsoft.Windows.ApplicationModel.Resources.dll!winrt::com_array_winrt::hstring_::clear
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.h
Labels: bug, area-MRTCore, needs-triage :mag:

#3650 Change Get-Service calls to ignore errors
  DevCheck.ps1
Labels: area-Infrastructure, needs-triage :mag:

#3654 Update bug-report.yaml for 1.4 experimental 1
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#3656 Make BuildAll.ps1 compatible with VS prerelease installs
  BuildAll.ps1
Labels: needs-triage :mag:

#3640 API Spec for Microsoft.UI.ThemeSettings class
  specs/themes/HighContrastThemes.gif
  specs/themes/ThemeSettings.md
Labels: needs-triage :mag:
