Repository microsoft/WindowsAppSDK, pull requests merged in 2023-01, with the labels that each got.

#3301 Fix GettingStarted doc formatting
  docs/Coding-Guidelines/GettingStarted.md
Labels: documentation, needs-triage :mag:

#3324 Fix issues with template files
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/BlankWindow.xaml
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/BlankWindow.xaml.cs
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/BlankWindow.xaml
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/BlankPage.xaml
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/BlankPage.xaml.cs
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/ResourceDictionary.xaml
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/CustomControl.cs
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/UserControl.xaml
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/UserControl.xaml.cs
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/BlankPage.xaml
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/ResourceDictionary.xaml
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/UserControl.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/Class1.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/MainWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/MainWindow.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/App.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/MainWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/MainWindow.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.xaml
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/MainWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/App.xaml
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/MainWindow.xaml
  tools/VerifyCopyrightHeaders.ps1
Labels: needs-triage :mag:

#3327 Update WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#3331 Update WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#3333 Update WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#3332 Update WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#3232 [Cherrypick] Update Newtonsoft.Json to 13.0.2 #3229
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage :mag:

#3358 dev.cpp.*.com-oopserver[-main] + Kozani[Remote]Manager lacking C++/WinRT support
  dev/Kozani/KozaniManager/KozaniManager.vcxproj
  dev/Kozani/KozaniManager/packages.config
  dev/Kozani/KozaniManager/pch.h
  dev/Kozani/KozaniRemoteManager/KozaniRemoteManager.vcxproj
  dev/Kozani/KozaniRemoteManager/packages.config
  dev/Kozani/KozaniRemoteManager/pch.h
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/packages.config
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/pch.h
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/PurojekutoTenpuretActivity.h
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/packages.config
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/pch.h
Labels: area-Infrastructure, needs-triage :mag:, area-Kozani

#3357 Refactor Installer Solution
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/nuget.config
  installer/test/InstallerFunctionalTests/InstallerFunctionalTests.vcxproj
Labels: needs-triage :mag:

#3363 Add latest .editorconfig from OS.2020
  .editorconfig
Labels: area-Infrastructure, needs-triage :mag:

#3335 Fix PushNotificationChannel::ExpirationTime incorrectly returning DateTime
  dev/PushNotifications/PushNotificationManager.cpp
  test/PushNotificationTests/BaseTestSuite.cpp
  test/PushNotificationTests/BaseTestSuite.h
  test/PushNotificationTests/PackagedTests.cpp
  test/PushNotificationTests/PackagedTests.h
  test/PushNotificationTests/UnpackagedTests.cpp
  test/PushNotificationTests/UnpackagedTests.h
Labels: area-Notifications, needs-triage :mag:

#3375 Update PR Template to Address Inaccuracies.
  docs/pull_request_template.md
Labels: needs-triage :mag:

#3377 DevCheck: -CheckDeveloperMode
  DevCheck.ps1
Labels: area-Infrastructure, needs-triage :mag:

#3366 Eliminate relative package locations for nuget
  BuildAll.ps1
  Directory.Build.props
  dev/DeploymentAgent/DeploymentAgent.vcxproj
  dev/Detours/Detours.vcxproj
  dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependency.DataStore.ProxyStub.vcxproj
  dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
  dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
  dev/DynamicDependencyLifetimeManager/IDynamicDependencyLifetimeManager/IDynamicDependencyLifetimeManager.vcxproj
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/PushNotificationsLongRunningTask.ProxyStub.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
  dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
  dev/RestartAgent/RestartAgent.vcxproj
  dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_MSIXInstallFromPath/WindowsAppRuntime_MSIXInstallFromPath.vcxproj
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/test/InstallerFunctionalTests/InstallerFunctionalTests.vcxproj
  test/AccessControlTests/AccessControlTests.vcxproj
  test/AppLifecycle/AppLifecycle.vcxproj
  test/AppNotificationBuilderTests/AppNotificationBuilderTests.vcxproj
  test/AppNotificationTests/AppNotificationTests.vcxproj
  test/Common/Common.vcxproj
  test/Deployment/API/DeploymentTests.vcxproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Default/Test_DeploymentManagerAutoInitialize_CPP_Default.vcxproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Default/Test_DeploymentManagerAutoInitialize_CPP_Options_Default.vcxproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Defined/Test_DeploymentManagerAutoInitialize_CPP_Options_Defined.vcxproj
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_None/Test_DeploymentManagerAutoInitialize_CPP_Options_None.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/Test_BootstrapAutoInitialize_CPP_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/Test_BootstrapAutoInitialize_CPP_Options_Default.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/Test_BootstrapAutoInitialize_CPP_Options_Defined.vcxproj
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/Test_BootstrapAutoInitialize_CPP_Options_None.vcxproj
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
  test/DynamicDependency/data/Framework.Widgets/Framework.Widgets.vcxproj
  test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
  test/LRPTests/LRPTests.vcxproj
  test/PowerNotifications/PowerNotifications.vcxproj
  test/PushNotificationTests/PushNotificationTests.vcxproj
  test/TestApps/AccessControlTestApp/AccessControlTestApp.vcxproj
  test/TestApps/AppLifecycleTestApp/AppLifecycleTestApp.vcxproj
  test/TestApps/ManualTestApp/ManualTestApp.vcxproj
  test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
  test/TestApps/PushNotificationsTestApp/PushNotificationsTestApp.vcxproj
  test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.vcxproj
  test/TestApps/ToastNotificationsTestApp/ToastNotificationsTestApp.vcxproj
  test/VersionInfo/VersionInfoTests.vcxproj
Labels: needs-triage :mag:

#3384 Minor polish code in dev\common
  dev/Common/Security.User.h
Labels: needs-triage :mag:

#3385 Update WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Labels: needs-triage :mag:

#3364 Update bug template to 1.2.3
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: documentation
