Repository microsoft/WindowsAppSDK, pull requests merged in 2023-03, with the labels that each got.

#3462 User/alexlam/42500021 dev 20230222
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-job.yml
  build/ProjectReunion-BuildFoundation-Weekly.yml
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#3475 Update ESRP Signing Task to 2: EsrpCodeSigning@2
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#3474 Update ESRP Signing Task to 2: EsrpCodeSigning@2
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#3459 Fix issue where scope_exit instances weren't being held in local variables.
  dev/PushNotifications/PushNotificationManager.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
Labels: area-Notifications, needs-triage :mag:

#3482 Add /await:strict to C++ build props
  WindowsAppSDK.Build.Cpp.props
  dev/AppNotifications/AppNotificationManager.cpp
Labels: bug, area-Infrastructure, area-Notifications, needs-triage :mag:

#3478 Add DynamicDependencies' tests to the CI/PR/nightly/etc test runs
  TestAll.ps1
  dev/Common/Security.IntegrityLevel.h
  test/DynamicDependency/Test_Win32/DynamicDependency_API_Win32.testdef
  test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
  test/DynamicDependency/Test_Win32/TestFilesystem.cpp
  test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestPackages.cpp
  test/DynamicDependency/Test_Win32/pch.h
  test/DynamicDependency/Test_WinRT/DynamicDependency_API_WinRT.testdef
  test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
Labels: area-DynamicDependencies

#3491 Update Minor Version to 4
  build/WindowsAppSDK-Versions.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
Labels: needs-triage :mag:

#3495 Update WindowsAppSDK-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
  build/Helix/global.json
  build/Helix/packages.config
  build/ProjectReunion-CI.yml
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.testdef
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.testdef
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.testdef
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  test/WindowsAppSDK.Helix.Test.NetCore/Program.cs
  test/WindowsAppSDK.Helix.Test.NetCore/WindowsAppSDK.Helix.Test.NetCore.csproj
  test/WindowsAppSDK.Helix.Test/WindowsAppSDK.Helix.Test.sln
  test/WindowsAppSDK.Helix.TestCommon/TestAssembly.cs
  test/WindowsAppSDK.Helix.TestCommon/TestMachineSetup.cmd
  test/WindowsAppSDK.Helix.TestCommon/TestPass-EnsureMachineState.ps1
  test/WindowsAppSDK.Helix.TestCommon/TestPass-OneTimeMachineSetup.ps1
  test/WindowsAppSDK.Helix.TestCommon/TestPass-PostRun.ps1
  test/WindowsAppSDK.Helix.TestCommon/TestPass-PreRun.ps1
  test/WindowsAppSDK.Helix.TestCommon/WindowsAppSDK.Helix.TestCommon.csproj
Labels: needs-triage :mag:

#3508 Add 1.2.5 to bug report template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#3510 Update 1.3-stable to migrate 3 MRT test suites away from Helix into the pipeline test environment
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
  build/Helix/RunTestsInHelix.proj
  build/Helix/global.json
  build/Helix/packages.config
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.testdef
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.testdef
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.testdef
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  test/WindowsAppSDK.Helix.Test.NetCore/Program.cs
  test/WindowsAppSDK.Helix.Test.NetCore/WindowsAppSDK.Helix.Test.NetCore.csproj
  test/WindowsAppSDK.Helix.Test/WindowsAppSDK.Helix.Test.sln
  test/WindowsAppSDK.Helix.TestCommon/TestAssembly.cs
  test/WindowsAppSDK.Helix.TestCommon/TestMachineSetup.cmd
  test/WindowsAppSDK.Helix.TestCommon/TestPass-EnsureMachineState.ps1
  test/WindowsAppSDK.Helix.TestCommon/TestPass-OneTimeMachineSetup.ps1
  test/WindowsAppSDK.Helix.TestCommon/TestPass-PostRun.ps1
  test/WindowsAppSDK.Helix.TestCommon/TestPass-PreRun.ps1
  test/WindowsAppSDK.Helix.TestCommon/WindowsAppSDK.Helix.TestCommon.csproj
Labels: needs-triage :mag:

#3493 Change supportedOS guid to Win10 and improve comment
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/app.manifest
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/app.manifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/app.manifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/app.manifest
Labels: needs-triage :mag:

#3476 Update ESRP Signing Task to 2: EsrpCodeSigning@2
  build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
  build/ProjectReunion-BuildFoundation.yml
Labels: needs-triage :mag:

#3529 Re-enable PREFast scanning in build pipeline
  BuildAll.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-BinaryAnalysis-steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SourceAnalysis-job.yml
  dev/MRTCore/build/DevCmd.cmd
  dev/MRTCore/build/init.cmd
Labels: needs-triage :mag:

#3538 Work around ADO bug 43856157 to unblock PREFast scanning
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildAndTestMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-job.yml
Labels: needs-triage :mag:

#3542 Make VersionInfo [Experimental] until it is fully working
  dev/Common/TerminalVelocityFeatures-VersionInfo.h
  dev/Common/TerminalVelocityFeatures-VersionInfo.xml
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/pch.h
Labels: needs-triage :mag:

#3547 [1.3] Mark Repair as [experimental] (#3543)
  dev/Common/TerminalVelocityFeatures-DeploymentAPI.h
  dev/Common/TerminalVelocityFeatures-DeploymentAPI.xml
  dev/Deployment/Deployment.idl
  dev/Deployment/DeploymentManager.cpp
Labels: needs-triage :mag:

#3551 [1.3] Fix Version Info Experimental
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
Labels: needs-triage :mag:

#3550 Bug 43948918 - fix error in the StageAndPackge stage in Foundation repo's weekly pipeline
  build/ProjectReunion-BuildFoundation-Weekly.yml
Labels: needs-triage :mag:
