Repository microsoft/WindowsAppSDK, pull requests merged in 2023-02, with the labels that each got.

#3398 Patch version of TAEF referenced by DevCheck
  DevCheck.ps1
Labels: area-DeveloperTools, area-Infrastructure, needs-triage :mag:

#3365 Update README
  docs/README.md
Labels: needs-triage :mag:

#3397 [CherryPick] Fix PushNotificationChannel::ExpirationTime (#3388)
  dev/PushNotifications/PushNotificationManager.cpp
  test/PushNotificationTests/BaseTestSuite.cpp
  test/PushNotificationTests/BaseTestSuite.h
  test/PushNotificationTests/PackagedTests.cpp
  test/PushNotificationTests/PackagedTests.h
  test/PushNotificationTests/UnpackagedTests.cpp
  test/PushNotificationTests/UnpackagedTests.h
Labels: area-Notifications

#3399 Refactoring MRTCore and Consolidate Nuget.configs
  build/EnsureOutputLayout.props
  build/ProjectReunion-BuildFoundation.yml
  build/licensing.nuget.config
  dev/MRTCore/mrt/Core/src/MRM.vcxproj
  dev/MRTCore/mrt/Core/unittests/MrmUnitTest.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
  dev/MRTCore/mrt/mrm/UnitTests/MrmBaseUnitTests.vcxproj
  dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
  dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
  dev/WindowsAppRuntime_Insights/nuget.config
Labels: needs-triage :mag:

#3407 Add WinAppSDK 1.3-exp1 to bug template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: documentation

#3403 VSWhere
  DevCheck.ps1
Labels: area-DeveloperTools, area-Infrastructure, needs-triage :mag:

#3409 Link README to Coding-Guidelines
  README.md
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/GettingStarted.md
  docs/Coding-Guidelines/GitCheckinToMainPolicy.md
  docs/Coding-Guidelines/develop-branch.md
  docs/contributor-guide.md
Labels: documentation, needs-triage :mag:

#3417 DevCheck fix: No taefservice detected = boom
  DevCheck.ps1
Labels: area-Infrastructure, needs-triage :mag:

#3367 Support TAEF testing in foundation pipeline
  TestAll.cmd
  TestAll.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/scripts/DownloadDotNetRuntimeInstaller.ps1
  build/scripts/DownloadVCLibsDesktop.ps1
  build/scripts/DownloadVCRedistInstaller.ps1
  test/PushNotificationTests/PushNotificationTests.testdef
  test/PushNotificationTests/PushNotificationTests.vcxproj
  test/PushNotificationTests/PushNotificationTests.vcxproj.filters
  tools/ProjectTemplates/test.cpp.dll.taef/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/test.cpp.dll.taef/Test.testdef
Labels: area-Infrastructure, area-Notifications, needs-triage :mag:

#3413 Fix Xml header
  dev/MRTCore/packaging/ProjectItemsSchema.xaml
Labels: area-MRTCore

#3414 Packages vs packages
  NuGet.config
  dev/Kozani/KozaniAppGraph/KozaniAppGraph.vcxproj
  dev/Kozani/KozaniHostRuntime/KozaniHostRuntime.vcxproj
  dev/Kozani/KozaniManager/KozaniManager.vcxproj
  dev/Kozani/KozaniManagerInterface/KozaniManagerInterface.vcxproj
  dev/Kozani/KozaniManagerProxyStub/KozaniManagerProxyStub.vcxproj
  dev/Kozani/KozaniManagerRuntime/KozaniManagerRuntime.vcxproj
  dev/Kozani/KozaniPackage/KozaniPackage.vcxproj
  dev/Kozani/KozaniRemoteManager/KozaniRemoteManager.vcxproj
  dev/Kozani/KozaniRemoteManagerInterface/KozaniRemoteManagerInterface.vcxproj
  dev/Kozani/KozaniRemoteManagerProxyStub/KozaniRemoteManagerProxyStub.vcxproj
  dev/Kozani/KozaniSendToLocal/KozaniSendToLocal.vcxproj
  dev/Kozani/KozaniSendToRemote/KozaniSendToRemote.vcxproj
  dev/Kozani/KozaniSettings/KozaniSettings.vcxproj
  dev/Kozani/MakeMSIX/MakeMSIX.vcxproj
  test/Kozani/KozaniAppGraphTests/KozaniAppGraphTests.vcxproj
  test/Kozani/KozaniHostRuntimeTests/KozaniHostRuntimeTests.vcxproj
  test/Kozani/KozaniManagerRuntimeTests/KozaniManagerRuntimeTests.vcxproj
  test/Kozani/KozaniManagerTests/KozaniManagerTests.vcxproj
  test/Kozani/KozaniPackageTests/KozaniPackageTests.vcxproj
  test/Kozani/KozaniRemoteManagerTests/KozaniRemoteManagerTests.vcxproj
  test/Kozani/KozaniSendToLocalTests/KozaniSendToLocalTests.vcxproj
  test/Kozani/KozaniSendToRemoteTests/KozaniSendToRemoteTests.vcxproj
  test/Kozani/KozaniSettingsTests/KozaniSettingsTests.vcxproj
  test/Kozani/MakeMSIXTests/MakeMSIXTests.vcxproj
  tools/ProjectTemplates/dev.cpp.dll.winrt-client-server/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.dll.winrt-client/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuretInterface/PurojekutoTenpuretInterface.vcxproj
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuretProxyStub/PurojekutoTenpuretProxyStub.vcxproj
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-interface/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-proxystub/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe.console-winrt-client/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/dev.cpp.exe.winmain-winrt-client/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/test.cpp.dll.msixpackage/PurojekutoTenpuret.vcxproj
  tools/ProjectTemplates/test.cpp.dll.taef/PurojekutoTenpuret.vcxproj
Labels: needs-triage :mag:

#3434 Automation Syncing the Mirrored release/1.3-stable Branch
  build/WindowsAppSDK-SyncMirroredRepository.yml
Labels: needs-triage :mag:

#3458 Updating bug report for WinAppSDK v1.2.4
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#3461 Update name from ProjectReunionClosed to WindowsAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage :mag:
