Repository microsoft/WindowsAppSDK, pull requests merged in 2023-06, with the labels that each got.

#3522 Do not add xbf files to UpToDateCheckInput as they are output files.
  dev/MRTCore/packaging/MrtCore.PriGen.targets
Labels: area-MRTCore

#3671 Update Installer exe to include Architecture
  installer/dev/WindowsAppRuntimeInstall.vcxproj
  installer/test/InstallerFunctionalTests/constants.h
Labels: needs-triage :mag:

#3679 Remove experimental-ness from DeploymentContract
  dev/Common/TerminalVelocityFeatures-DeploymentAPI.h
  dev/Deployment/Deployment.idl
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
Labels: area-Deployment, needs-triage :mag:

#3675 Update bug-report.yaml for 1.3.2
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#3688 Remove experimental-ness from DeploymentContract
  dev/Common/TerminalVelocityFeatures-DeploymentAPI.h
  dev/Deployment/Deployment.idl
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
Labels: needs-triage :mag:

#3672 Change to using the centrally shared copy of DevCheck (from eng\common)
  DevCheck.cmd
  DevCheck.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
Labels: area-Infrastructure

#3683 Fix PostBuild event for copying Bootstrap DLL
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: needs-triage :mag:

#3691 Don't reference VersionInfo WinRT API if it's disabled
  test/VersionInfo/VersionInfoTests.cpp
Labels: area-VersionInfo, needs-triage :mag:
