Repository microsoft/WindowsAppSDK, pull requests merged in 2024-12, with the labels that each got.

#4930 Add FeedbackHub trigger to WindowsAppSDK repository
  .github/policies/resourceManagement.yml
Labels: needs-triage

#4934 Add DetourFinishHelperProcess export
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
Labels: needs-triage, area-DynamicDependencies, area-UndockedRegFreeWinRT

#4937 [1.6 servicing] Add DetourFinishHelperProcess export
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
Labels: area-DynamicDependencies

#4919 Fix the GUID in CameraCaptureUITelemetry
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUITelemetry.h
Labels: needs-triage

#4940 Use separate folder for publishing redist files, not the nuget package cache
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  tools/DevCheck/DevCheck.ps1
Labels: needs-triage

#4946 Find custom.props in parent dir
  LkgToolset.props
Labels: needs-triage

#4951 Bug 55435589: MrtCore build now fails due to mrt.gdnsuppress exclusions not being found, due to case sensitive of nuget package cache
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#4952 [Build] Removed mrt.gdnsuppress and the reference to it
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  dev/MRTCore/.gdn/mrt.gdnsuppress
Labels: needs-triage

#4954 Add one telemetry for FileOpenPicker.PickerSingleFileAsync
  dev/Interop/StoragePicker/FileOpenPicker.cpp
  dev/Interop/StoragePicker/FileOpenPicker.h
  dev/Interop/StoragePicker/StoragePickersTelemetry.h
Labels: needs-triage

#4823 API Spec for Badge Notifications in WindowsAppSdk
  specs/BadgeNotifications/BadgeNotifications-spec.md
  specs/BadgeNotifications/GlyphBadgeExample.png
  specs/BadgeNotifications/NumericBadgeExample.png
  specs/BadgeNotifications/badge-activity.png
  specs/BadgeNotifications/badge-alarm.png
  specs/BadgeNotifications/badge-alert.png
  specs/BadgeNotifications/badge-attention.png
  specs/BadgeNotifications/badge-available.png
  specs/BadgeNotifications/badge-away.png
  specs/BadgeNotifications/badge-busy.png
  specs/BadgeNotifications/badge-error.png
  specs/BadgeNotifications/badge-newmessage.png
  specs/BadgeNotifications/badge-paused.png
  specs/BadgeNotifications/badge-playing.png
  specs/BadgeNotifications/badge-unavailable.png
Labels: needs-triage, area-Notifications, api-design

#4926 Local Badge Notification code changes
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/AppNotifications/NotificationProperties.cpp
  dev/AppNotifications/NotificationProperties.h
  dev/AppNotifications/NotificationTransientProperties.cpp
  dev/AppNotifications/NotificationTransientProperties.h
  dev/Common/TerminalVelocityFeatures-BadgeNotifications.h
  dev/Common/TerminalVelocityFeatures-BadgeNotifications.xml
  dev/Notifications/BadgeNotifications/BadgeNotification.cpp
  dev/Notifications/BadgeNotifications/BadgeNotification.h
  dev/Notifications/BadgeNotifications/BadgeNotificationManager.cpp
  dev/Notifications/BadgeNotifications/BadgeNotificationManager.h
  dev/Notifications/BadgeNotifications/BadgeNotificationTelemetry.h
  dev/Notifications/BadgeNotifications/BadgeNotifications.idl
  dev/Notifications/BadgeNotifications/BadgeNotifications.vcxitems
  dev/Notifications/BaseNotifications/BaseNotification.cpp
  dev/Notifications/BaseNotifications/BaseNotification.h
  dev/Notifications/BaseNotifications/BaseNotifications.vcxitems
  dev/Projections/CS/Microsoft.Windows.BadgeNotifications.Projection/Microsoft.Windows.BadgeNotifications.Projection.csproj
  dev/PushNotifications/PushNotificationUtility.h
  dev/PushNotifications/externs.h
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
Labels: needs-triage

#4970 Cherry pick LKG/MsUCRT fixes
  BuildAll.ps1
  Directory.Build.props
  LkgToolset.props
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-AnyCPU-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
  installer/dev/main.cpp
Labels: needs-triage

#4964 [1.6 servicing] Bug Fix for Cannot install version 1.3: DDLM package not found
  installer/dev/install.cpp
Labels: needs-triage

#4911 Update C# templates to introduce file scoped namespaces
  dev/VSIX/Extension/Cs/Dev17/VSPackage.cs
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/BlankWindow.xaml
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/BlankWindow.xaml.cs
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/BlankWindow.cpp
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/BlankWindow.h
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/BlankWindow.xaml
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/BlankPage.xaml
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/BlankPage.xaml.cs
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/CustomControl.cs
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/UserControl.xaml.cs
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/BlankPage.cpp
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/BlankPage.h
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/BlankPage.xaml
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/UserControl.cpp
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/UserControl.h
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/UserControl.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/Class1.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/MainWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/MainWindow.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/App.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/MainWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/MainWindow.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestApp.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestAppWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestAppWindow.xaml.cs
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTests.cs
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/MainWindow.cpp
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/MainWindow.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/MainWindow.xaml
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/MainWindow.cpp
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/MainWindow.h
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/MainWindow.xaml
  dev/VSIX/Shared/WizardImplementation.cs
Labels: needs-triage

#4975 Unit tests for OAuth2Manager API
  WindowsAppRuntime.sln
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/OAuth2ManagerTests/OAuth2APITests.cpp
  test/OAuth2ManagerTests/OAuth2APITests.h
  test/OAuth2ManagerTests/OAuth2ManagerTests.vcxproj
  test/OAuth2ManagerTests/OAuth2ManagerTests.vcxproj.filters
  test/OAuth2ManagerTests/packages.config
  test/OAuth2ManagerTests/pch.cpp
  test/OAuth2ManagerTests/pch.h
  test/TestApps/OAuthTestApp/OAuthTestApp.vcxproj
  test/TestApps/OAuthTestApp/OAuthTestApp.vcxproj.filters
  test/TestApps/OAuthTestApp/main.cpp
  test/TestApps/OAuthTestApp/packages.config
  test/TestApps/OAuthTestApp/pch.cpp
  test/TestApps/OAuthTestApp/pch.h
  test/TestApps/OAuthTestAppPackage/Images/LockScreenLogo.scale-200.png
  test/TestApps/OAuthTestAppPackage/Images/SplashScreen.scale-200.png
  test/TestApps/OAuthTestAppPackage/Images/Square150x150Logo.scale-200.png
  test/TestApps/OAuthTestAppPackage/Images/Square44x44Logo.scale-200.png
  test/TestApps/OAuthTestAppPackage/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  test/TestApps/OAuthTestAppPackage/Images/StoreLogo.png
  test/TestApps/OAuthTestAppPackage/Images/Wide310x150Logo.scale-200.png
  test/TestApps/OAuthTestAppPackage/OAuthTestAppPackage.wapproj
  test/TestApps/OAuthTestAppPackage/Package.appxmanifest
Labels: needs-triage

#4967 Unit tests for BackgroundTaskBuilder API
  WindowsAppRuntime.sln
  test/BackgroundTaskTests/BackgroundTaskBuilder-AppxManifest.xml
  test/BackgroundTaskTests/BackgroundTaskBuilderTests.cpp
  test/BackgroundTaskTests/BackgroundTaskTests.vcxproj
  test/BackgroundTaskTests/BackgroundTaskTests.vcxproj.filters
  test/BackgroundTaskTests/packages.config
  test/BackgroundTaskTests/pch.cpp
  test/BackgroundTaskTests/pch.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Labels: needs-triage

#4997 Updating windows SDK version to 10.0
  test/TestApps/OAuthTestApp/OAuthTestApp.vcxproj
  test/TestApps/OAuthTestAppPackage/OAuthTestAppPackage.wapproj
Labels: needs-triage

#4979 [OAuth2Manager] Remove APIs for Implicit grant type
  dev/OAuth/AuthRequestAsyncOperation.cpp
  dev/OAuth/AuthRequestAsyncOperation.h
  dev/OAuth/OAuth.idl
  dev/OAuth/OAuth2Manager.cpp
  dev/OAuth/OAuth2Manager.h
  dev/OAuth/OAuth2ManagerTelemetry.h
  dev/OAuth/TokenRequestParams.cpp
  dev/OAuth/TokenRequestParams.h
  specs/OAuth/OAuth2Manager.md
Labels: needs-triage

#4994 Added TaskGroup property support to BackgroundTaskBuilder API
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.cpp
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.h
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
  specs/BackgroundTask/BackgroundTaskBuilder.md
Labels: needs-triage
