Repository microsoft/WindowsAppSDK, pull requests merged in 2024-09, with the labels that each got.

#4692 Update bug-report.yaml for 1.6.0
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#4708 Reintroduce Runtime Identifier in Pubxml to Resolve Platform Mismatch
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
Labels: needs-triage

#4701 Onboard 1.6 to use Maestro
  build/AzurePipelinesTemplates/WindowsAppSDK-Publish-Stage.yml
  build/WindowsAppSDK-Foundation-Official.yml
  eng/common/AzurePipelinesTemplates/Maestro-PublishBuildToMaestro-Steps.yml
Labels: needs-triage

#4707 DevCheck: Settings options, configuration dependency paths, Sync'd dependencies
  dev/WindowsAppRuntime_DLL/packages.config
  eng/common/DevCheck.ps1
  test/PackageManager/API/packages.config
Labels: needs-triage, area-Infrastructure

#4712 Revert "[MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride (#4608)"
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Labels: needs-triage

#4716 [WinAppSDK 1.6] Revert "[MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride (#4608)"
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Labels: needs-triage

#4576 CameraCaptureUI API Spec
  specs/CameraCaptureUI/CameraCaptureUI.md
  specs/CameraCaptureUI/CameraCaptureUI_Snapshot.png
Labels: needs-triage

#4714 Create a DevCheck NuGet Package from which DevCheck.cmd in feeder repos can restore and utilize
  DevCheck.cmd
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/WindowsAppSDK-BuildDevCheck.yml
  tools/DevCheck/DevCheck.ps1
  tools/DevCheck/nuspec/Microsoft.WindowsAppSDK.DevCheck.nuspec
Labels: needs-triage

#4721 CameraCaptureUI - API Spec
  specs/CameraCaptureUI/CameraCaptureUI.md
  specs/CameraCaptureUI/CameraCaptureUI_Snapshot.png
Labels: needs-triage

#4727 53812687 - Disable auto bug filing via TSA for the 1.6-Stable branch on the Foundation repo
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#4729 [CP to 1.5] 53812687 - Disable auto bug filing via TSA for the 1.6-Stable branch on the Foundation repo
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#4731 clarified error message for when the Microsoft.WindowsAppRuntime FWP alone has been installed (and not DDLM, e.g.)
  dev/Deployment/DeploymentManager.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: needs-triage

#4732 Machine Folder's ACL docs improved
  specs/applicationdata/ApplicationData.md
Labels: documentation, needs-triage, area-ApplicationData

#4740 Fix BuildAll Error Stemming from StrictMode and Retarget Solution
  BuildAll.ps1
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj.filters
Labels: needs-triage

#4744 [WinAppSDK 1.5] Roll back build image to VS 17.9
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#4747 Refactor Repo Mirroring from Two Pipelines to One Pipeline
  build/WindowsAppSDK-SyncMirroredRepository.yml
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4748 Bring back SourceToTargetBranch parameter
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4749 Use $(Source.BuildBranch) parameter in SyncMirrors
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4750 Fix Typo refs/heads/ in SyncMirrors
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4751 [Cherrypick] Refactor Repo Mirroring from Two Pipelines to One Pipeline
  build/WindowsAppSDK-SyncMirroredRepository.yml
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4752 [Cherrypick] Refactor Repo Mirroring from Two Pipelines to One Pipeline
  build/WindowsAppSDK-SyncMirroredRepository.yml
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4753 [Cherrypick] Refactor Repo Mirroring from Two Pipelines to One Pipeline
  build/WindowsAppSDK-SyncMirroredRepository.yml
  build/WindowsAppSDK-SyncTrigger.yml
Labels: needs-triage

#4757 .yml cleanup: lower true and false
  .github/policies/resourceManagement.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-Publish-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#4759 [Build] Fix obsolete area path for filing TSA bugs on the Foundation repo
  .config/tsaoptions.json
Labels: needs-triage

#4760 [release/1.5-stable] Update dependencies from LiftedIXP and WindowsAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage
