Repository microsoft/WindowsAppSDK, pull requests merged in 2024-08, with the labels that each got.

#4605 Update dependencies
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  test/ApplicationData/packages.config
  test/PackageManager/data/PackageManager.Test.M.Black.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Blacker.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.White.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Whiter.msix/packages.config
Labels: needs-triage, area-Infrastructure

#4608 [MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Labels: needs-triage

#4609 1.6-stable: cherry-pick Fix IsPackageDeploymentFeatureSupported (#4598)
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/WindowsAppRuntime_DLL/packages.config
  test/ApplicationData/packages.config
  test/PackageManager/API/packages.config
  test/PackageManager/data/PackageManager.Test.M.Black.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Blacker.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.White.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Whiter.msix/packages.config
Labels: needs-triage, area-Deployment

#4611 [Cherry-pick][WinAppSDK 1.6] [MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Labels: needs-triage

#4612 Update Runtime Identifier Paths for Compatibility with .NET 8
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage

#4614 [release/1.4-stable] Define package versions centrally
  Directory.Packages.props
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage

#4617 [release/1.6-stable] Update dependencies from DCPP and AppLicensing
  eng/Version.Details.xml
Labels: needs-triage

#4616 Update to template format
  specs/CameraCaptureUI/CameraCaptureUI.md
Labels: needs-triage

#4619 [1.6-stable] Add AppData Terminal Velocity call to yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
Labels: needs-triage

#4620 [main] Add AppData Terminal Velocity call to yml (#4619)
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
Labels: needs-triage

#4624 Update to use WindowsAppSDK-PublishSymbol-Steps.yml from WindowsAppSDK Config
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PublishSymbol-Steps.yml
Labels: needs-triage

#4627 Update AppLicensing to 1.7.0-main.20240611.0
  eng/Version.Details.xml
Labels: needs-triage

#4626 Revert #4612 (NETSDK1206 Fix)
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage

#4629 Fix ExtractWindowsAppSDKVersion to only look at WindowsAppSDK nupkg
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
Labels: needs-triage

#4637 Update bug-report.yaml for 1.5.6 and 1.6-preview1
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#4628 Update CsWinRT version to stable versions
  Directory.Build.props
  eng/Version.Details.xml
Labels: needs-triage

#4647 Update Channel to stable
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#4639 Onboard to DotNet's Maestro using WindowsAppSDKConfig PublishToMaestro Template
  build/AzurePipelinesTemplates/WindowsAppSDK-Publish-Stage.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#4648 update versions for 1.6 stable
  Directory.Build.props
  eng/Version.Details.xml
  global.json
Labels: needs-triage

#4650 Update Taef, CppWinRT, and WIL
  dev/DeploymentAgent/packages.config
  dev/MRTCore/mrt/Core/src/packages.config
  dev/MRTCore/mrt/Core/unittests/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/MRTCore/mrt/mrm/UnitTests/packages.config
  dev/MRTCore/mrt/mrm/mrmex/packages.config
  dev/MRTCore/mrt/mrm/mrmmin/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/RestartAgent/packages.config
  dev/WindowsAppRuntime_BootstrapDLL/packages.config
  dev/WindowsAppRuntime_DLL/packages.config
  eng/Version.Dependencies.xml
  installer/dev/packages.config
  installer/test/InstallerFunctionalTests/packages.config
  test/AccessControlTests/packages.config
  test/AppLifecycle/packages.config
  test/AppNotificationBuilderTests/packages.config
  test/AppNotificationTests/packages.config
  test/ApplicationData/packages.config
  test/Common/packages.config
  test/Deployment/API/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Default/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Default/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Defined/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_Win32/packages.config
  test/DynamicDependency/Test_WinRT/packages.config
  test/DynamicDependency/data/Framework.Widgets/packages.config
  test/EnvironmentManagerTests/packages.config
  test/LRPTests/packages.config
  test/PackageManager/API/packages.config
  test/PackageManager/data/PackageManager.Test.M.Black.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Blacker.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.White.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Whiter.msix/packages.config
  test/PowerNotifications/packages.config
  test/PushNotificationTests/packages.config
  test/TestApps/AccessControlTestApp/packages.config
  test/TestApps/AppLifecycleTestApp/packages.config
  test/TestApps/ManualTestApp/packages.config
  test/TestApps/PushNotificationsDemoApp/packages.config
  test/TestApps/PushNotificationsTestApp/packages.config
  test/TestApps/ToastNotificationsDemoApp/packages.config
  test/TestApps/ToastNotificationsTestApp/packages.config
  test/VersionInfo/packages.config
  tools/ProjectTemplates/dev.cpp.dll.winrt-client-server/packages.config
  tools/ProjectTemplates/dev.cpp.dll.winrt-client/packages.config
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/packages.config
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/packages.config
  tools/ProjectTemplates/dev.cpp.exe.console-winrt-client/packages.config
  tools/ProjectTemplates/dev.cpp.exe.winmain-winrt-client/packages.config
  tools/ProjectTemplates/test.cpp.dll.taef/packages.config
Labels: needs-triage

#4657 fix dotnet versions in Versions.Details.xml
  eng/Version.Details.xml
Labels: needs-triage

#4656 [1.6] Update Taef, WIL, AzureKeyVault task versions. Sync FrameworkUdk versions.
  dev/DeploymentAgent/packages.config
  dev/MRTCore/mrt/Core/src/packages.config
  dev/MRTCore/mrt/Core/unittests/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/packages.config
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
  dev/MRTCore/mrt/mrm/UnitTests/packages.config
  dev/MRTCore/mrt/mrm/mrmex/packages.config
  dev/MRTCore/mrt/mrm/mrmmin/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/packages.config
  dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
  dev/RestartAgent/packages.config
  dev/WindowsAppRuntime_BootstrapDLL/packages.config
  dev/WindowsAppRuntime_DLL/packages.config
  eng/Version.Dependencies.xml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  installer/dev/packages.config
  installer/test/InstallerFunctionalTests/packages.config
  test/AccessControlTests/packages.config
  test/AppLifecycle/packages.config
  test/AppNotificationBuilderTests/packages.config
  test/AppNotificationTests/packages.config
  test/ApplicationData/packages.config
  test/Common/packages.config
  test/Deployment/API/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Default/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Default/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_Defined/packages.config
  test/Deployment/Test_DeploymentManagerAutoInitialize/CPP/Test_DeploymentManagerAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Default/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_Defined/packages.config
  test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/Test_BootstrapAutoInitialize_CPP_Options_None/packages.config
  test/DynamicDependency/Test_Win32/packages.config
  test/DynamicDependency/Test_WinRT/packages.config
  test/DynamicDependency/data/Framework.Widgets/packages.config
  test/EnvironmentManagerTests/packages.config
  test/LRPTests/packages.config
  test/PackageManager/API/packages.config
  test/PackageManager/data/PackageManager.Test.M.Black.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Blacker.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.White.msix/packages.config
  test/PackageManager/data/PackageManager.Test.M.Whiter.msix/packages.config
  test/PowerNotifications/packages.config
  test/PushNotificationTests/packages.config
  test/TestApps/AccessControlTestApp/packages.config
  test/TestApps/AppLifecycleTestApp/packages.config
  test/TestApps/ManualTestApp/packages.config
  test/TestApps/PushNotificationsDemoApp/packages.config
  test/TestApps/PushNotificationsTestApp/packages.config
  test/TestApps/ToastNotificationsDemoApp/packages.config
  test/TestApps/ToastNotificationsTestApp/packages.config
  test/VersionInfo/packages.config
  tools/ProjectTemplates/dev.cpp.dll.winrt-client-server/packages.config
  tools/ProjectTemplates/dev.cpp.dll.winrt-client/packages.config
  tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/packages.config
  tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/packages.config
  tools/ProjectTemplates/dev.cpp.exe.console-winrt-client/packages.config
  tools/ProjectTemplates/dev.cpp.exe.winmain-winrt-client/packages.config
  tools/ProjectTemplates/test.cpp.dll.taef/packages.config
Labels: needs-triage

#4658 [1.6] Update dependencies from WinAppSDKClosed
  eng/Version.Details.xml
Labels: needs-triage

#4659 update dependencies from WinAppSDKClosed, DCPP
  eng/Version.Details.xml
Labels: needs-triage

#4663 New PackageDeploymentManager methods not tagged with new v2 contract
  dev/PackageManager/API/PackageManager.idl
Labels: needs-triage, area-Deployment

#4664 Fix ApplicationData.MachineFolder path
  dev/ApplicationData/M.W.S.ApplicationData.cpp
  specs/applicationdata/ApplicationData.md
  test/ApplicationData/ApplicationDataTests.cpp
Labels: needs-triage, area-ApplicationData

#4666 Fix Source Link information so it points to Github rather than internal AzDO mirror
  Directory.Build.props
Labels: needs-triage

#4668 1.6 Fix ApplicationData.MachineFolder path
  dev/ApplicationData/M.W.S.ApplicationData.cpp
  specs/applicationdata/ApplicationData.md
  test/ApplicationData/ApplicationDataTests.cpp
Labels: needs-triage, area-ApplicationData

#4667 1.6 New PackageDeploymentManager methods not tagged with new v2 contract
  dev/PackageManager/API/PackageManager.idl
Labels: needs-triage, area-Deployment

#4670 [Cherry-pick][Windows App SDK 1.6] Fix Source Link information so it points to Github rather than internal AzDO mirror
  Directory.Build.props
Labels: needs-triage

#4675 Update bug-report.yaml for 1.6-preview2
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#4674 Fix centrally-versioned package references
  Directory.Packages.props
  dev/VSIX/Directory.Build.props
Labels: needs-triage

#4677 [CP to main] Fix centrally-versioned package references
  Directory.Packages.props
  dev/VSIX/Directory.Build.props
Labels: needs-triage

#4673 Binlogs for Installer and VSIX
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
Labels: needs-triage

#4684 Onebranch Build Pipeline Update: Remove deprecated auth variables from build pipelines
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#4686 NETSDK1206 Fix
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: needs-triage

#4687 [1.6] NETSDK1206 Fix
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: needs-triage
