Repository microsoft/WindowsAppSDK, pull requests merged in 2024-05, with the labels that each got.

#4372 Improved Logging v3
  dev/Common/Common.vcxitems
  dev/Common/Logging.h
  dev/DynamicDependency/API/DataStore.cpp
  dev/DynamicDependency/API/MsixDynamicDependency.h
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/MsixPackageManager.h
  dev/PackageManager/API/PackageDeploymentResolver.cpp
  dev/PackageManager/API/PackageManager.vcxitems
  dev/PackageManager/API/PackageManager.vcxitems.filters
  dev/PackageManager/API/pch.h
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/pch.h
  docs/Coding-Guidelines.md
  docs/Coding-Guidelines/ErrorHandlingAndLogging.md
Labels: documentation, area-Deployment, area-Infrastructure, area-DynamicDependencies, needs-triage :mag:

#4380 Update bug-report.yaml for 1.5.3
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage :mag:

#4384 Setup release/1.6 branch to sync to the internal mirror
  build/WindowsAppSDK-SyncMirroredRepository.yml
Labels: needs-triage :mag:

#4345 Fix CoreUtility warning regressions
  dev/VSIX/Extension/Cpp/Dev16/ExtensionPack.vsext
  dev/VSIX/Extension/Cpp/Dev16/VSPackage.cs
  dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
  dev/VSIX/Extension/Cpp/Dev16/source.extension.vsixmanifest
  dev/VSIX/Extension/Cs/Dev16/ExtensionPack.vsext
  dev/VSIX/Extension/Cs/Dev16/VSPackage.cs
  dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
  dev/VSIX/Extension/Cs/Dev16/source.extension.vsixmanifest
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.csproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.csproj
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.csproj
Labels: needs-triage :mag:

#4397 Fix initialization of _InOut_ variable
  dev/Deployment/DeploymentManager.cpp
  dev/Deployment/DeploymentManager.h
Labels: needs-triage :mag:

#4398 49601674: Exclude the \Packages folder from PREfast scans
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
Labels: needs-triage :mag:

#4404 49601674: Fixing the previous PR
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
Labels: needs-triage :mag:

#4405 Fix a test failure due to WindowsCreateString error
  dev/Deployment/DeploymentManager.cpp
  dev/UndockedRegFreeWinRT/typeresolution.cpp
Labels: needs-triage :mag:

#4408 Class Library $DotNetVersion$ fix
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
Labels: needs-triage :mag:

#4414 Changing Default Platform to x64
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.vstemplate
Labels: needs-triage :mag:

#4411 Improve GettingStarted docs. DevCheck verify RS5 SDK.
  docs/Coding-Guidelines/GettingStarted.md
  eng/common/DevCheck.ps1
Labels: area-Infrastructure

#4425 Refactor Runtime Identifiers to Support .NET 8 and higher by default
  build/CopyFilesToStagingDir.ps1
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
Labels: needs-triage :mag:

#4418 Update GitHub ResourceManagement policy yml
  .github/policies/resourceManagement.yml
Labels: needs-triage :mag:

#4416 Removing UWP reference
  docs/faq.md
Labels: needs-triage :mag:

#4422 Updating roadmap for 1.6
  docs/roadmap.md
Labels: needs-triage :mag:

#4427 Update version of CsWinRT and Windows SDK projection
  Directory.Build.props
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.Management.Deployment.Projection/Microsoft.Windows.Management.Deployment.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
  eng/Version.Details.xml
  tools/ProjectTemplates/dev.cs.dll.projection/PurojekutoTenpuret.Projection.csproj
Labels: needs-triage :mag:

#4441 Copy Microsoft.WindowsAppRuntime.Bootstrap.dll from portable RID folder
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Labels: needs-triage

#4445 Revert "Refactor Runtime Identifiers to Support .NET 8 and higher by default"
  build/CopyFilesToStagingDir.ps1
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
Labels: needs-triage

#4451 Fix missing trimming annotation and set couple cswinrt properties
  dev/Projections/Directory.Build.props
  eng/common/VersionInfo/AssemblyInfo.cs
  eng/common/VersionInfo/GenerateVersionInfo.ps1
Labels: needs-triage

#4436 [release/1.6-stable] Update version of CsWinRT and Windows SDK projection (#4427)
  Directory.Build.props
  dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.Management.Deployment.Projection/Microsoft.Windows.Management.Deployment.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
  dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
  dev/Projections/Directory.Build.props
  eng/Version.Details.xml
  eng/common/VersionInfo/AssemblyInfo.cs
  eng/common/VersionInfo/GenerateVersionInfo.ps1
  tools/ProjectTemplates/dev.cs.dll.projection/PurojekutoTenpuret.Projection.csproj
Labels: needs-triage

#4458 Remove condition for develop and main branch on versioning and always add $(PipelineType) to the tag
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#4461 Remove condition for develop and main branch on versioning and always add $(PipelineType) to the tag
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#4459 [BuildFix] Fix APIScan config to properly honor parameters.runStaticAnalysis
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
Labels: needs-triage

#4462 Remove condition for develop and main branch on versioning and always add $(PipelineType) to the tag
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#4464 Update tsaoptions.json
  .config/tsaoptions.json
Labels: needs-triage
