Repository microsoft/WindowsAppSDK, pull requests merged in 2024-10, with the labels that each got.

#4762 Bug 54198205: The Tags in nuspec file is wrong on Foundation repo
  tools/DevCheck/nuspec/Microsoft.WindowsAppSDK.DevCheck.nuspec
Labels: needs-triage

#4765 Update bug-report.yaml for 1.6.1
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#4767 Updated stale dependencies via DevCheck -SyncDependencies
  dev/WindowsAppRuntime_DLL/packages.config
  test/PackageManager/API/packages.config
Labels: needs-triage, area-Infrastructure

#4775 Change default project name to UnitTestApp
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.vstemplate
Labels: needs-triage

#4793 Update System.Text.Json to 8.0.5
  Directory.Packages.props
Labels: needs-triage

#4795 Update System.Text.Json to 8.0.5
  dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
  dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Labels: needs-triage

#4794 Update System.Text.Json to 8.0.5 (#4793)
  Directory.Packages.props
Labels: needs-triage

#4813 RegisterPackageSetAsync() requires URI when it should be optional to register by PackageFamilyName
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  specs/packagemanager/PackageManagement.md
  test/PackageManager/API/PackageDeploymentManagerTests_Register.cpp
  test/PackageManager/API/PackageManagerTests.Packages.h
Labels: area-Packaging, needs-triage

#4815 [1.6 servicing] RegisterPackageSetAsync() requires URI when it should be optional to register by PackageFamilyName
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  specs/packagemanager/PackageManagement.md
  test/PackageManager/API/PackageDeploymentManagerTests_Register.cpp
  test/PackageManager/API/PackageManagerTests.Packages.h
Labels: needs-triage, area-Deployment

#4772 "OAuth2Manager" API for OAuth 2.0 in WindowsAppSDK
  specs/OAuth/OAuth2Manager.md
  specs/WinRT/WinRTAPIContracts.md
Labels: needs-triage

#4771 CameraCaptureUI API Implementation
  Directory.Packages.props
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Common/Common.vcxitems
  dev/Common/Common.vcxitems.filters
  dev/Common/TelemetryHelper.h
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.cpp
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.h
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.idl
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.vcxitems
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUIPhotoCaptureSettings.cpp
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUIPhotoCaptureSettings.h
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUITelemetry.h
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUIVideoCaptureSettings.cpp
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUIVideoCaptureSettings.h
  dev/Projections/CS/Microsoft.Windows.Media.Capture.Projection/Microsoft.Windows.Media.Capture.Projection.csproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_DLL/packages.config
  dev/WindowsAppRuntime_DLL/pch.h
  eng/PackageReference/ProjectReunion.InteractiveExperiences/Microsoft.ProjectReunion.InteractiveExperiences.TransportPackage.PackageReference.csproj
  eng/Version.Dependencies.props
  eng/Version.Details.xml
  test/CameraCaptureUITests/APITests.cpp
  test/CameraCaptureUITests/CameraCaptureUI-AppxManifest.xml
  test/CameraCaptureUITests/CameraCaptureUITests.vcxproj
  test/CameraCaptureUITests/CameraCaptureUITests.vcxproj.filters
  test/CameraCaptureUITests/packages.config
  test/CameraCaptureUITests/pch.cpp
  test/CameraCaptureUITests/pch.h
  test/CameraCaptureUITests/wil.natvis
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/PackageManager/API/packages.config
  test/PowerNotifications/FunctionalTests.cpp
Labels: needs-triage

#4828 OAuth2Manager Implementation
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Common/TelemetryHelper.h
  dev/Common/TerminalVelocityFeatures-OAuth.h
  dev/Common/TerminalVelocityFeatures-OAuth.xml
  dev/OAuth/AuthFailure.cpp
  dev/OAuth/AuthFailure.h
  dev/OAuth/AuthRequestAsyncOperation.cpp
  dev/OAuth/AuthRequestAsyncOperation.h
  dev/OAuth/AuthRequestParams.cpp
  dev/OAuth/AuthRequestParams.h
  dev/OAuth/AuthRequestResult.cpp
  dev/OAuth/AuthRequestResult.h
  dev/OAuth/AuthResponse.cpp
  dev/OAuth/AuthResponse.h
  dev/OAuth/ClientAuthentication.cpp
  dev/OAuth/ClientAuthentication.h
  dev/OAuth/Crypto.h
  dev/OAuth/LockableMap.h
  dev/OAuth/OAuth.idl
  dev/OAuth/OAuth.vcxitems
  dev/OAuth/OAuth2Manager.cpp
  dev/OAuth/OAuth2Manager.h
  dev/OAuth/OAuth2ManagerTelemetry.h
  dev/OAuth/TokenFailure.cpp
  dev/OAuth/TokenFailure.h
  dev/OAuth/TokenRequestParams.cpp
  dev/OAuth/TokenRequestParams.h
  dev/OAuth/TokenRequestResult.cpp
  dev/OAuth/TokenRequestResult.h
  dev/OAuth/TokenResponse.cpp
  dev/OAuth/TokenResponse.h
  dev/OAuth/common.h
  dev/Projections/CS/Microsoft.Security.Authentication.OAuth/Microsoft.Security.Authentication.OAuth.Projection.csproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
Labels: needs-triage
