Repository microsoft/WindowsAppSDK, pull requests merged in 2024-11, with the labels that each got.

#4838 Fix for the winmd references
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Labels: needs-triage

#4822 API spec for BackgroundTaskBuilder API
  specs/BackgroundTask/BackgroundTaskBuilder.md
  specs/WinRT/WinRTAPIContracts.md
Labels: needs-triage, api-design

#4831 BackgroundTaskBuilder Implementation
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.cpp
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.h
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.vcxitems
  dev/Projections/CS/Microsoft.Windows.ApplicationModel.Background.Projection/Microsoft.Windows.ApplicationModel.Background.Projection.csproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.cpp
  dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.h
  dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.idl
  dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.def
  dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj
  dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj.filters
  dev/WindowsAppRuntime_UniversalBGTaskDLL/packages.config
  dev/WindowsAppRuntime_UniversalBGTaskDLL/pch.cpp
  dev/WindowsAppRuntime_UniversalBGTaskDLL/pch.h
  dev/WindowsAppRuntime_UniversalBGTaskDLL/readme.txt
Labels: needs-triage, api-design

#4852 Adding reference for DynamicDependency winmd
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Labels: needs-triage

#4855 Automatically generate password to avoid using Convert-To-SecureString
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  tools/DevCheck/DevCheck.ps1
Labels: needs-triage

#4858 Automatically generate password to avoid using Convert-To-SecureString (Cherry Pick)
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  tools/DevCheck/DevCheck.ps1
Labels: needs-triage

#4859 DevCheck: Start the TAEFService if we install it
  tools/DevCheck/DevCheck.ps1
Labels: needs-triage, area-Infrastructure

#4863 Removing UniversalBGTask Activation class entry from framework manifest
  build/NuSpecs/AppxManifest.xml
Labels: needs-triage

#4869 Removing UniversalBGTask Activation class entry from framework manifest
  build/NuSpecs/AppxManifest.xml
Labels: needs-triage

#4875 Update bug-report.yaml for 1.6.2
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#4873 Fix incorrect cch param
  dev/MRTCore/mrt/Core/src/MRM.cpp
Labels: needs-triage

#4896 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#4895 Updating CameraCaptureUI Spec Doc
  specs/CameraCaptureUI/CameraCaptureUI.md
  specs/WinRT/WinRTAPIContracts.md
Labels: needs-triage

#4890 Bug Fix for Cannot install version 1.3: DDLM package not found
  installer/dev/install.cpp
Labels: needs-triage

#4908 Added TerminalVelocity for BackgroundTaskBuilder API
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.h
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
  dev/Common/TerminalVelocityFeatures-BackgroundTask.h
  dev/Common/TerminalVelocityFeatures-BackgroundTask.xml
  specs/BackgroundTask/BackgroundTaskBuilder.md
Labels: needs-triage

#4906 Adding Terminal Velocity Check for CameraCaptureUI Experimental API
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/Common/TerminalVelocityFeatures-CameraCaptureUI.h
  dev/Common/TerminalVelocityFeatures-CameraCaptureUI.xml
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.h
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.idl
  test/CameraCaptureUITests/APITests.cpp
  test/CameraCaptureUITests/CameraCaptureUITests.vcxproj
Labels: needs-triage

#4912 Update TeminalVelocity changes for OAuth2Manager Experimental API
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/Common/TerminalVelocityFeatures-OAuth.xml
Labels: needs-triage

#4783 Interfaces for "Enhanced UX Notification for Video and Audio Call Feature"
  dev/AppNotifications/AppNotification.cpp
  dev/AppNotifications/AppNotification.h
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.h
  dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.idl
  dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.cpp
  dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.h
  dev/AppNotifications/AppNotificationConferencingConfig.cpp
  dev/AppNotifications/AppNotificationConferencingConfig.h
  dev/AppNotifications/AppNotificationManager.cpp
  dev/AppNotifications/AppNotificationTelemetry.h
  dev/AppNotifications/AppNotifications.idl
  dev/AppNotifications/AppNotifications.vcxitems
  dev/AppNotifications/NotificationConferencingConfig.cpp
  dev/AppNotifications/NotificationConferencingConfig.h
  dev/AppNotifications/NotificationProperties.cpp
  dev/AppNotifications/NotificationProperties.h
  dev/Common/TerminalVelocityFeatures-AppNotifications.xml
  dev/Common/TerminalVelocityFeatures-CallingPreviewSupport.h
  test/AppNotificationBuilderTests/APITests.cpp
  test/AppNotificationTests/BaseTestSuite.cpp
  test/AppNotificationTests/BaseTestSuite.h
  test/AppNotificationTests/PackagedTests.cpp
  test/AppNotificationTests/PackagedTests.h
  test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Labels: needs-triage, area-Notifications, api-design, feature proposal
