Repository microsoft/WindowsAppSDK, pull requests merged in 2025-03, with the labels that each got.

#5194 56138352 - Upgrade the Foundation repo to use the latest LKG18 native compiler
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#5220 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5215 Throw right exception in case of CoCreateInstance failure
  dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.cpp
  dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.h
Labels: needs-triage

#5222 [Cherry-pick to 1.7] Updating project / item template icons and descriptions (#4986)
  assets/WindowsAppSDK128.png
  assets/WindowsAppSDK128.svg
  assets/WindowsAppSDK240.png
  assets/WindowsAppSDK240.svg
  assets/WindowsAppSDK64.png
  assets/WindowsAppSDK64.svg
  assets/WindowsAppSDK768.png
  assets/WindowsAppSDK768.svg
  dev/VSIX/Extension/Cpp/Common/VSPackage.resx
  dev/VSIX/Extension/Cs/Common/VSPackage.resx
  dev/VSIX/Extension/WindowsAppSDK.png
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.ico
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.png
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.ico
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.png
  dev/VSIX/WindowsAppSDK.ico
Labels: needs-triage

#5243 WASDK-BugTemplate Update
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5191 [1.7] EnsurePackage*ReadyAsync() doesn't register v2 if v1 is registered and caller asks for minVersion=v1 #5182
  dev/PackageManager/API/M.W.M.D.AddPackageOptions.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  dev/PackageManager/API/M.W.M.D.RegisterPackageOptions.cpp
  dev/PackageManager/API/M.W.M.D.StagePackageOptions.cpp
  dev/PackageManager/API/MsixPackageManager.h
  test/PackageManager/API/PackageDeploymentManagerTests_EnsureReady_RegisterNewerIfAvailable.cpp
Labels: area-Deployment

#5268 Add telemetry
  dev/Common/StoragePickersTelemetryHelper.h
  dev/Interop/StoragePickers/FileOpenPicker.cpp
  dev/Interop/StoragePickers/FileOpenPicker.h
  dev/Interop/StoragePickers/FileSavePicker.cpp
  dev/Interop/StoragePickers/FileSavePicker.h
  dev/Interop/StoragePickers/FolderPicker.cpp
  dev/Interop/StoragePickers/FolderPicker.h
  dev/Interop/StoragePickers/StoragePickersTelemetry.h
Labels: needs-triage

#5240 Experimental Microsoft.Windows.Storage.Pickers.* API
  WindowsAppRuntime.sln
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
  dev/Common/TerminalVelocityFeatures-StoragePickers.h
  dev/Common/TerminalVelocityFeatures-StoragePickers.xml
  dev/Interop/StoragePickers/FileOpenPicker.cpp
  dev/Interop/StoragePickers/FileOpenPicker.h
  dev/Interop/StoragePickers/FileSavePicker.cpp
  dev/Interop/StoragePickers/FileSavePicker.h
  dev/Interop/StoragePickers/FolderPicker.cpp
  dev/Interop/StoragePickers/FolderPicker.h
  dev/Interop/StoragePickers/Microsoft.Windows.Storage.Pickers.idl
  dev/Interop/StoragePickers/PickFileResult.cpp
  dev/Interop/StoragePickers/PickFileResult.h
  dev/Interop/StoragePickers/PickFolderResult.cpp
  dev/Interop/StoragePickers/PickFolderResult.h
  dev/Interop/StoragePickers/PickerCommon.cpp
  dev/Interop/StoragePickers/PickerCommon.h
  dev/Interop/StoragePickers/StoragePickers.vcxitems
  dev/Interop/StoragePickers/StoragePickersTelemetry.h
  dev/Interop/StoragePickers/StoragePickersTelemetryHelper.h
  dev/Projections/CS/Microsoft.Windows.Storage.Pickers.Projection/Microsoft.Windows.Storage.Pickers.Projection.csproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/StoragePickersTests/StoragePickersTests.cpp
  test/StoragePickersTests/StoragePickersTests.vcxproj
  test/StoragePickersTests/StoragePickersTests.vcxproj.filters
  test/StoragePickersTests/packages.config
  test/StoragePickersTests/pch.cpp
  test/StoragePickersTests/pch.h
Labels: needs-triage

#5155 Public Spec for Microsoft.Windows.Storage.Pickers
  specs/StoragePickers/FileOpenPicker.md
  specs/StoragePickers/FileSavePicker.md
  specs/StoragePickers/FolderPicker.md
  specs/StoragePickers/Microsoft.Windows.Storage.Pickers.md
  specs/StoragePickers/PickFileResult.md
  specs/StoragePickers/PickFolderResult.md
  specs/StoragePickers/PickerLocationId.md
  specs/StoragePickers/PickerViewMode.md
Labels: needs-triage

#5271 Adding implementation for IsCallingPreviewSupported method
  dev/AppNotifications/AppNotificationConferencingConfig.cpp
Labels: needs-triage

#5275 Fix Install-TAEFService using wrong path to Wex.Sevice.exe
  tools/DevCheck/DevCheck.ps1
Labels: needs-triage, area-Infrastructure

#5278 PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events.
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  dev/PackageManager/API/PackageManagerTelemetry.h
  test/DynamicDependency/Test_Win32/Test_Win32_Create_Add_Architectures_Explicit_NoMatch.cpp
Labels: needs-triage, area-Deployment

#5261 [1.7] 56439870: A/B Containment for EnsurePackage*ReadyAsync()
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/PackageManager.Containment.h
  dev/PackageManager/API/PackageManager.vcxitems
  dev/PackageManager/API/PackageManager.vcxitems.filters
  dev/PackageManager/API/pch.h
  dev/WindowsAppRuntime_DLL/pch.h
Labels: needs-triage, area-Deployment

#5284 PackageDeploymentManager - Add missing .Stop() event on CompletedSuccess
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
Labels: needs-triage, area-Deployment

#5283 Add TraceLogging tagging and generic fields to failure events.
  installer/dev/tracelogging.cpp
Labels: needs-triage

#5286 Task 56847091: [WASDK][Compliance] Update the WindowsAppSDK repo to use the global default LKG compiler version on the Config repo
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/WindowsAppSDK-CommonVariables.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#5289 [1.7] Add TraceLogging tagging and generic fields to failure events.
  installer/dev/tracelogging.cpp
Labels: needs-triage

#5291 [1.6] Add TraceLogging tagging and generic fields to failure events.
  installer/dev/tracelogging.cpp
Labels: needs-triage

#5290 [1.8] Add TraceLogging tagging and generic fields to failure events.
  installer/dev/tracelogging.cpp
Labels: needs-triage
