Repository microsoft/WindowsAppSDK, pull requests merged in 2025-09, with the labels that each got.

#5774 Update MSIX build tools version to 1.7.20250829.1
  dev/WindowsAppRuntime_DLL/packages.config
  eng/Version.Dependencies.xml
Labels: needs-triage

#5753 Enable Common tests
  test/Common/Common.testdef
  test/Common/Test_SelfContained.cpp
Labels: needs-triage

#5765 Update build channel for 1.8 stable release
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#5755 change dev package suffix
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#5791 Update StaticValidationTests to use 26100 SDK
  build/AzurePipelinesTemplates/WindowsAppSDK-StaticValidationTest-Stage.yml
Labels: needs-triage

#5789 Add the matching ORT headers and version header
  inc/README.md
  inc/abi/runtime/WindowsAppSDK-VersionInfo.h
  inc/abi/winml/Microsoft.Windows.AI.MachineLearning.h
  inc/abi/winml/WindowsMLAutoInitializer.cpp
  inc/abi/winml/onnxruntime/cpu_provider_factory.h
  inc/abi/winml/onnxruntime/provider_options.h
  inc/abi/winml/onnxruntime/win_onnxruntime_c_api.h
  inc/abi/winml/onnxruntime/win_onnxruntime_cxx_api.h
  inc/abi/winml/onnxruntime/win_onnxruntime_cxx_inline.h
  inc/abi/winml/onnxruntime/win_onnxruntime_float16.h
  inc/abi/winml/onnxruntime/win_onnxruntime_lite_custom_op.h
  inc/abi/winml/onnxruntime/win_onnxruntime_run_options_config_keys.h
  inc/abi/winml/onnxruntime/win_onnxruntime_session_options_config_keys.h
Labels: needs-triage

#5793 Add 1.7.4 runtime compatibility enums
  dev/RuntimeCompatibilityOptions/RuntimeCompatibilityOptions.idl
Labels: needs-triage

#5786 Update Pack stage's condition
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#5794 Enabling access control tests
  test/AccessControlTests/APITests.cpp
  test/AccessControlTests/AccessControlTests.testdef
  test/AccessControlTests/AccessControlTests.vcxproj
  test/BypassTests.json
  test/TestApps/AccessControlTestAppPackage/Package.appxmanifest
Labels: needs-triage

#5809 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5785 DevCheck: LongPath support, verify nuget.exe, fix ExitCode, fix InstallWindowsSDK, add/fix SettingsFile, update Getting Started docs
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  docs/Coding-Guidelines/GettingStarted.md
  tools/DevCheck/DevCheck-Settings.ps1
  tools/DevCheck/DevCheck.ps1
Labels: area-Infrastructure

#5812 change staticValidationTest windowsSdk version
  build/AzurePipelinesTemplates/WindowsAppSDK-StaticValidationTest-Stage.yml
Labels: needs-triage

#5759 Enabling LRP tests
  test/BypassTests.json
  test/LRPTests/APITests.cpp
  test/LRPTests/LRPTests.testdef
  test/LRPTests/LRPTests.vcxproj
  test/LRPTests/pch.h
Labels: needs-triage

#5838 [release/2.0-stable] Update dependencies from microsoft/LiftedIXP/DCPP
  eng/Version.Details.xml
Labels: needs-triage

#5846 PackageDeployment API Progress status bug #5532
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  test/PackageManager/API/PackageDeploymentManagerTests.h
Labels: area-Deployment

#5781 Enabling app notification tests
  test/AppNotificationTests/AppNotification-Test-Constants.h
  test/AppNotificationTests/AppNotificationTests.testdef
  test/AppNotificationTests/AppNotificationTests.vcxproj
  test/AppNotificationTests/BaseTestSuite.cpp
  test/AppNotificationTests/UnpackagedTests.h
Labels: needs-triage

#5816 Installing VCLibs from tests in pipeline
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/InstallVCLibs.ps1
  test/AppLifecycle/AppLifecycle.testdef
  test/BypassTests.json
Labels: needs-triage

#5854 DynamicDependency: Expanded powershell cmdlets
  dev/DynamicDependency/Powershell/Add-PackageDependency.ps1
  dev/DynamicDependency/Powershell/Get-PackageDependency.ps1
  dev/DynamicDependency/Powershell/Get-PackageDependencyProcesses.ps1
  dev/DynamicDependency/Powershell/MsixDynamicDependency.psm1
Labels: needs-triage, area-DynamicDependencies

#5865 Fixing reset activity data on deployment initialization
  dev/Deployment/DeploymentActivityContext.cpp
  dev/Deployment/DeploymentManager.cpp
Labels: needs-triage

#5877 Fix the Sample Tests failure caused by ModifySampleAppsReferences.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildSamplesCompat-Job.yml
  test/ModifySampleAppsReferences.ps1
Labels: needs-triage
