Repository microsoft/WindowsAppSDK, pull requests merged in 2025-02, with the labels that each got.

#5100 Marking CameraCaptureUI Telemetry as Critical
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUITelemetry.h
Labels: needs-triage

#5103 Set Channel to Preview
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#5104 [1.7] Removing terminal velocity (#5070)
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.idl
  test/CameraCaptureUITests/APITests.cpp
Labels: needs-triage

#5107 Removed TerminalVelocity usages from IDL
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
Labels: needs-triage

#5106 Bootstrapper formatting bad DDLM package name in FindDDLMViaEnumeration()
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  test/DynamicDependency/Test_Win32/TestPackages.h
  test/DynamicDependency/Test_WinRT/TestPackages.h
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest-arm64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest-x64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest-x86.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest-arm64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest-x64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1000.Msix/appxmanifest-x86.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest-arm64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest-x64.xml
  test/DynamicDependency/data/DynamicDependencyLifetimeManagerGC1010.Msix/appxmanifest-x86.xml
  test/inc/WindowsAppRuntime.Test.Metadata.h
  test/inc/WindowsAppRuntime.Test.Package.h
Labels: needs-triage, area-DynamicDependencies

#5105 [OAuth2Manager]: Make Telemetry Critical
  dev/OAuth/OAuth2ManagerTelemetry.h
Labels: needs-triage

#5110 [Cherry-pick to 1.7] Removed TerminalVelocity usages from IDL
  dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
Labels: needs-triage

#5113 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5109 [1.7] Fix TerminalVelocityFeatures-CallingPreviewSupport.h to be generated. #5108
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/AppNotifications/AppNotificationConferencingConfig.cpp
Labels: needs-triage

#5108 Fix TerminalVelocityFeatures-CallingPreviewSupport.h to be generated.
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/AppNotifications/AppNotificationConferencingConfig.cpp
Labels: needs-triage

#5119 [Cherry-pick to 1.7]Making the telemetry for OAuth2Manager Critical.
  dev/OAuth/OAuth2ManagerTelemetry.h
Labels: needs-triage

#4927 Unpackaged App CTA compliance code changes
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
  dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
Labels: needs-triage

#5111 TerminalVelocity: -Output filename/basename generation and doc update
  docs/Coding-Guidelines/TerminalVelocity.md
  tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
Labels: needs-triage, area-Infrastructure

#5133 PackageDeploymentManager: Some tests running elevated but didn't need elevation
  test/PackageManager/API/PackageDeploymentManagerTests_EnsureReady_RegisterNewerIfAvailable.cpp
Labels: needs-triage, area-Deployment

#5130 [Build] Update WindowsAppSDK-BuildFoundation-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
Labels: needs-triage

#5142 Update README.md
  README.md
Labels: needs-triage

#5148 [OAuth2Manager] Remove velocity tags added due to conflict resolution
  dev/Common/TerminalVelocityFeatures-OAuth.xml
Labels: needs-triage

#5134 Removed Handling for Pre-Existing Password Files
  tools/DevCheck/DevCheck.ps1
Labels: needs-triage

#5152 Update Minor Version to 8
  build/VersionInfo/AssemblyInfo.h
  build/WindowsAppSDK-Versions.yml
Labels: needs-triage

#5140 BadgeNotification: Onboarding Unit tests to the pipeline test runs
  test/BadgeNotificationTest/BadgeNotification.testdef
  test/BadgeNotificationTest/BadgeNotificationTest.vcxproj
  test/BadgeNotificationTest/BadgeNotificationTest.vcxproj.filters
  test/BadgeNotificationTest/BadgeNotifications-AppxManifest.xml
  test/BadgeNotificationTest/PackagedTests.cpp
  test/BadgeNotificationTest/resource.h
Labels: needs-triage

#4986 Updating project / item template icons and descriptions
  assets/WindowsAppSDK128.png
  assets/WindowsAppSDK128.svg
  assets/WindowsAppSDK240.png
  assets/WindowsAppSDK240.svg
  assets/WindowsAppSDK64.png
  assets/WindowsAppSDK64.svg
  assets/WindowsAppSDK768.png
  assets/WindowsAppSDK768.svg
  dev/VSIX/Extension/Cpp/Common/VSPackage.resx
  dev/VSIX/Extension/Cs/Common/VSPackage.resx
  dev/VSIX/Extension/WindowsAppSDK.png
  dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.ico
  dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.ico
  dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.ico
  dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.png
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.ico
  dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.png
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.ico
  dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.png
  dev/VSIX/WindowsAppSDK.ico
Labels: needs-triage

#5169 Set R1 Network Flag on Windows Container Image
  build/WindowsAppSDK-BuildDevCheck.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#5189 Remove NuGetWrapper.cmd Usage from dist.nuget.org
  BuildAll.ps1
  build/NuSpecs/build-nupkg.ps1
  tools/NugetWrapper.cmd
Labels: needs-triage

#5182 EnsurePackage*ReadyAsync() doesn't register v2 if v1 is registered and caller asks for minVersion=v1
  dev/PackageManager/API/M.W.M.D.AddPackageOptions.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  dev/PackageManager/API/M.W.M.D.RegisterPackageOptions.cpp
  dev/PackageManager/API/M.W.M.D.StagePackageOptions.cpp
  dev/PackageManager/API/MsixPackageManager.h
  test/PackageManager/API/PackageDeploymentManagerTests_EnsureReady_RegisterNewerIfAvailable.cpp
Labels: needs-triage, area-Deployment

#5195 Fallback to the Documents Library when the specified SuggestedStartLocation doesn't exist on end user's environment
  dev/Interop/StoragePickers/PickerCommon.cpp
Labels: needs-triage
