Repository microsoft/WindowsAppSDK, pull requests merged in 2025-04, with the labels that each got.

#5175 [Issue #3871] File activation for unpackaged App would fail when file path contains unicode characters or special characters
  dev/AppLifecycle/ExtensionContract.h
  dev/AppLifecycle/FileActivatedEventArgs.h
  test/AppLifecycle/FunctionalTests.cpp
Labels: area-Activation

#5297 [1.6 servicing] PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  dev/PackageManager/API/PackageManagerTelemetry.h
Labels: needs-triage, area-Deployment

#5296 [1.7 servicing] PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
  dev/PackageManager/API/PackageManagerTelemetry.h
Labels: needs-triage, area-Deployment

#5312 Fix some type mismatch issues in MRT
  dev/MRTCore/mrt/mrm/UnitTests/DecisionInfo.UnitTests.cpp
  dev/MRTCore/mrt/mrm/UnitTests/testUtils.cpp
  dev/MRTCore/mrt/mrm/mrmmin/DecisionInfoBuilder.cpp
Labels: needs-triage

#5308 Wasdk/1.7/1.7.1 bug template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5324 [Build] Eliminate non-fatal PREfast errors with a temporarily workaround
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#5327 [CP to 1.8][Build] Eliminate non-fatal PREfast errors with a temporarily workaro…
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Labels: needs-triage

#5338 Wasdk/1.8/1.8.exp1 bug template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5341 Revert "[main] Update dependencies from microsoft/LiftedIXP/DCPP"
  eng/Version.Details.xml
Labels: needs-triage

#5337 Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019
  build/WindowsAppSDK-TDBuild.yml
Labels: needs-triage

#5342 [CP to 1.8] Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019
  build/WindowsAppSDK-TDBuild.yml
Labels: needs-triage

#5343 [CP to 1.7] Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019
  build/WindowsAppSDK-TDBuild.yml
Labels: needs-triage

#5344 [CP to 1.6] Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019
  build/WindowsAppSDK-TDBuild.yml
Labels: needs-triage

#5321 Fix Bootstrapper only use Win11 DynamicDependency API if available AND WinAppSDK target >= 1.7
  WindowsAppRuntime.sln
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: area-DynamicDependencies

#4988 Remove MRT Core .props/.targets files
  BuildAll.ps1
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
  build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.targets
  dev/MRTCore/packaging/MrtCore.PriGen.targets
  dev/MRTCore/packaging/MrtCore.References.targets
  dev/MRTCore/packaging/MrtCore.props
  dev/MRTCore/packaging/MrtCore.targets
  dev/MRTCore/packaging/ProjectItemsSchema.xaml
  dev/MRTCore/packaging/README.md
  dev/MRTCore/packaging/native/MrtCore.targets
Labels: needs-triage, area-MRTCore, breaking change

#5349 [1.7 servicing] Fix Bootstrapper only use Win11 DynamicDependency API if available AND WinAppSDK target >= 1.7 (#5321)
  WindowsAppRuntime.sln
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Labels: needs-triage, area-DynamicDependencies

#5355 Update FrUdk for agg pipeline coherency
  eng/Version.Details.xml
Labels: needs-triage

#5360 Remove factored mrtcore.props,targets imports
  build/NuSpecs/WindowsAppSDK-Nuget-Native.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Labels: needs-triage

#5336 Add ABForward Tests
  WindowsAppRuntime.sln
  eng/Version.Dependencies.props
  eng/Version.Dependencies.xml
  test/ABForward/ABForward.testdef
  test/ABForward/ABForward.vcxproj
  test/ABForward/ABForward.vcxproj.filters
  test/ABForward/FunctionalTests.cpp
  test/ABForward/packages.config
  test/ABForward/pch.cpp
  test/ABForward/pch.h
  test/inc/WindowsAppRuntime.Test.Bootstrap.h
Labels: needs-triage

#5361 Update BuildTools version for BuildTools.MSIX refactor
  dev/VSIX/Directory.Build.props
Labels: needs-triage

#5366 Add binlog for msbuild invoke
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
Labels: needs-triage

#5367 Bugfix - Storage Pickers cannot launch on ARM64
  dev/Interop/StoragePickers/FileOpenPicker.cpp
  dev/Interop/StoragePickers/FileSavePicker.cpp
  dev/Interop/StoragePickers/FolderPicker.cpp
Labels: needs-triage

#5358 Supplements Missing Functionalities for FileOpenPicker.FileTypeFilter and FileSavePicker.FilterTypeChoices
  dev/Interop/StoragePickers/FileOpenPicker.cpp
  dev/Interop/StoragePickers/FileSavePicker.cpp
  dev/Interop/StoragePickers/ManualTests/README.md
  dev/Interop/StoragePickers/ManualTests/media/add-unioned-auto-select.gif
  dev/Interop/StoragePickers/ManualTests/media/alter-extension-with-choices-beforefix.gif
  dev/Interop/StoragePickers/ManualTests/media/alter-extension-with-choices.gif
  dev/Interop/StoragePickers/ManualTests/media/force-known-extensions-beforefix.gif
  dev/Interop/StoragePickers/ManualTests/media/force-known-extensions.gif
  dev/Interop/StoragePickers/ManualTests/media/no-unioned-type-before-fix.png
  dev/Interop/StoragePickers/PickerCommon.cpp
  specs/StoragePickers/FileSavePicker.md
Labels: needs-triage

#5377 Fix regex matching for getting the WinAppSDK version number in a generic way
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
Labels: needs-triage

#5375 [Experimental] Decimal data type
  WindowsAppRuntime.sln
  dev/AppLifecycle/ExtensionContract.h
  dev/Common/TerminalVelocityFeatures-Decimal.h
  dev/Common/TerminalVelocityFeatures-Decimal.xml
  dev/Decimal/Decimal.idl
  dev/Decimal/Decimal.vcxitems
  dev/Decimal/Decimal.vcxitems.filters
  dev/Decimal/DecimalTelemetry.h
  dev/Decimal/M.W.F.Decimal.cpp
  dev/Decimal/M.W.F.Decimal.h
  dev/Decimal/decimal.h
  dev/Decimal/decimalcppwinrt.h
  dev/Decimal/pch.h
  dev/Projections/CS/Microsoft.Windows.Foundation/DecimalExtensions.cs
  dev/Projections/CS/Microsoft.Windows.Foundation/Microsoft.Windows.Foundation.Projection.csproj
  dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
  specs/decimal/decimal.md
  test/Decimal/CPP/DecimalTests.cpp
  test/Decimal/CPP/DecimalTests.vcxproj
  test/Decimal/CPP/DecimalTests.vcxproj.filters
  test/Decimal/CPP/Test.testdef
  test/Decimal/CPP/packages.config
  test/Decimal/CPP/pch.cpp
  test/Decimal/CPP/pch.h
  test/Decimal/CS/DecimalTest_CS.csproj
  test/Decimal/CS/DotNetTests.cs
  test/Decimal/CS/Program.cs
  test/Decimal/CS/Verify.cs
  test/Decimal/CS/WinAppSDKTests.cs
  test/Decimal/DecimalCalcuator/CS/DecimalCalculator_CS.csproj
  test/Decimal/DecimalCalcuator/CS/Program.cs
  test/Decimal/DecimalCalcuator/CS/py_test_mod.cmd
  test/Decimal/DecimalCalcuator/CS/test_mod.cmd
  test/Decimal/WinRT/DecimalTest_WinRT.cpp
  test/Decimal/WinRT/DecimalTest_WinRT.vcxproj
  test/Decimal/WinRT/DecimalTest_WinRT.vcxproj.filters
  test/Decimal/WinRT/Test.testdef
  test/Decimal/WinRT/packages.config
  test/Decimal/WinRT/pch.cpp
  test/Decimal/WinRT/pch.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
  test/inc/WindowsAppRuntime.Test.Bootstrap.h
  test/inc/WindowsAppRuntime.Test.Diagnostics.h
  tools/VerifyCopyrightHeaders.ps1
Labels: area-Decimal

#5380 Remove NuGetToolInstaller Tasks; Update DevCheck
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-AnyCPU-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  build/ProjectReunion-CI.yml
  eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
  eng/common/DevCheck.ps1
Labels: needs-triage

#5381 [Cherrypick] Remove NuGetWrapper.cmd Usage from dist.nuget.org
  BuildAll.ps1
  build/NuSpecs/build-nupkg.ps1
  tools/NugetWrapper.cmd
Labels: needs-triage

#5386 Use older IXP package version to produce release candidate
  eng/Version.Details.xml
Labels: needs-triage
