Repository microsoft/WindowsAppSDK, pull requests merged in 2025-06, with the labels that each got.

#5496 search vars should persist, not be loop local
  dev/MRTCore/mrt/Core/src/MRM.cpp
Labels: needs-triage

#5497 cherry pick: search vars should persist, not be loop local (#5496)
  dev/MRTCore/mrt/Core/src/MRM.cpp
Labels: needs-triage

#5503 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5514 Hardcode release/1.8-stable Branch Value into WindowsAppSDKConfig reference
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#5523 Decimal updated per API Review
  dev/Decimal/Decimal.idl
  dev/Decimal/Decimal.vcxitems
  dev/Decimal/Decimal.vcxitems.filters
  dev/Decimal/M.W.F.DecimalHelper.cpp
  dev/Decimal/M.W.F.DecimalHelper.h
  dev/Decimal/decimal.h
  dev/Decimal/decimalcppwinrt.h
  dev/Decimal/pch.h
  dev/Projections/CS/Microsoft.Windows.Foundation/DecimalExtensions.cs
  specs/decimal/decimal.md
  test/Decimal/CPP/DecimalTests.cpp
  test/Decimal/DecimalCalcuator/CS/Program.cs
  test/Decimal/WinRT/DecimalTest_WinRT.cpp
Labels: area-Decimal

#5549 Changes for https://github.com/microsoft/WindowsAppSDK/pull/5540/files
  dev/Deployment/DeploymentManager.cpp
  installer/dev/install.cpp
Labels: needs-triage

#5555 Compliance for Deployment and Boostrapper Insights
  dev/Deployment/DeploymentTracelogging.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.cpp
Labels: needs-triage

#5540 [1.7 servicing] WinAppSdk 1.7 installer not able to install Singleton package when WinAppSdk 1.6 is installed and 1.6 Singleton is being used in the background
  dev/Deployment/DeploymentManager.cpp
  installer/dev/install.cpp
Labels: needs-triage

#5561 Fix Foundation component package libs to be under native folder
  BuildAll.ps1
  build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
  build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
  build/NuSpecs/WindowsAppSDK-Nuget-Native.props
  dev/MRTCore/packaging/native/MrtCore.C.props
Labels: needs-triage

#5285 Improve TraceLogging
  dev/Deployment/DeploymentTraceLogging.h
  dev/Deployment/DeploymentTracelogging.cpp
  dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
  dev/PackageManager/API/PackageDeploymentResolver.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
  dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.h
Labels: area-Deployment, area-DynamicDependencies

#5579 Fix FeedbackHub trigger
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/policies/resourceManagement.yml
Labels: needs-triage
