Repository microsoft/WindowsAppSDK, pull requests merged in 2025-01, with the labels that each got.

#5003 Switch auto initializer targets to add via BeforeClCompileTargets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.Bootstrap.targets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.DeploymentManager.targets
  build/NuSpecs/WindowsAppSDK-Nuget-Native.UndockedRegFreeWinRT.targets
Labels: needs-triage

#5001 Publish experimental VersionInfo API
  build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
  dev/Common/TerminalVelocityFeatures-VersionInfo.h
  dev/Common/TerminalVelocityFeatures-VersionInfo.xml
  dev/VersionInfo/VersionInfo.ReleaseInfo.cpp
  dev/VersionInfo/VersionInfo.RuntimeInfo.cpp
  dev/VersionInfo/VersionInfo.idl
  dev/VersionInfo/VersionInfo.vcxitems
  test/VersionInfo/VersionInfoTests.cpp
  test/VersionInfo/VersionInfoTests.vcxproj
  test/VersionInfo/pch.h
Labels: area-VersionInfo

#5020 Update Install-WindowsSdkISO.ps1 to use new FW links
  build/scripts/Install-WindowsSdkISO.ps1
Labels: needs-triage

#5014 Bug Fix for Badge Notification c# projection
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
Labels: needs-triage

#5015 removing BadgeNotification Expiration API
  dev/Notifications/BadgeNotifications/BadgeNotificationManager.h
  dev/Notifications/BadgeNotifications/BadgeNotifications.idl
  specs/BadgeNotifications/BadgeNotifications-spec.md
Labels: needs-triage

#5013 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5023 Update Install-WindowsSdkISO.ps1 to use new FW links (#5020)
  build/scripts/Install-WindowsSdkISO.ps1
Labels: needs-triage

#5026 Adding AppNotificationConferencingConfig to AppxManifest.xml
  build/NuSpecs/AppxManifest.xml
Labels: needs-triage

#5029 [release/1.7-stable] Cherry-pick a few API fixes into 1.7
  WindowsAppRuntime.sln
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/AppxManifest.xml
  dev/Notifications/BadgeNotifications/BadgeNotificationManager.h
  dev/Notifications/BadgeNotifications/BadgeNotifications.idl
  specs/BadgeNotifications/BadgeNotifications-spec.md
Labels: needs-triage

#4920 Updated README with new logo
  README.md
  dev/MRTCore/README.md
  docs/README.md
  docs/images/header.png
  docs/images/winui-gallery.png
  docs/roadmap.md
Labels: needs-triage

#5036 Update bug-report.yaml
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: needs-triage

#5042 54239817 - Update Agg repo to use latest LKG17 compiler version 19.40.33817100
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#5043 [CP to 1.7] 54239817 - Update Foundation repo to use latest LKG17 compiler version 19.40.33817100
  build/WindowsAppSDK-CommonVariables.yml
Labels: needs-triage

#5009 Unittests for badge notifications
  WindowsAppRuntime.sln
  test/BadgeNotificationTest/BadgeNotification-Test-Constants.h
  test/BadgeNotificationTest/BadgeNotificationTest.vcxproj
  test/BadgeNotificationTest/BadgeNotificationTest.vcxproj.filters
  test/BadgeNotificationTest/BadgeNotificationTests.rc
  test/BadgeNotificationTest/BadgeNotifications-AppxManifest.xml
  test/BadgeNotificationTest/PackagedTests.cpp
  test/BadgeNotificationTest/PackagedTests.h
  test/BadgeNotificationTest/icon1.ico
  test/BadgeNotificationTest/packages.config
  test/BadgeNotificationTest/pch.cpp
  test/BadgeNotificationTest/pch.h
  test/BadgeNotificationTest/resource.h
  test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Labels: needs-triage

#4824 Adding spec for enhanced Audio or Video Calling
  specs/AppNotifications/AppNotificationBuider/AppNotificationBuilder-spec.md
  specs/AppNotifications/AppNotifications-spec.md
  specs/AppNotifications/Enhanced_ux_video_call_Notifications.png
Labels: Status: In PR, area-Notifications, api-design

#5047 Adding contract for UniversalBGTask
  dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.idl
  dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj
  dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj.filters
  dev/WindowsAppRuntime_UniversalBGTaskDLL/pch.h
Labels: needs-triage

#5055 Match Build Number and Version
  build/ProjectReunion-BuildFoundation.yml
  build/ProjectReunion-CI.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
Labels: needs-triage

#5065 Onboard Static Validation Tests
  build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-Publish-Stage.yml
  build/AzurePipelinesTemplates/WindowsAppSDK-StaticValidationTest-Stage.yml
  build/WindowsAppSDK-Foundation-Nightly.yml
  build/WindowsAppSDK-Foundation-Official.yml
  build/WindowsAppSDK-Foundation-PR.yml
  test/StaticValidationTests/CommandLineProcess.cs
  test/StaticValidationTests/PackageInspectionTest.csproj
  test/StaticValidationTests/Program.cs
  test/StaticValidationTests/ValidationTestCommon.cs
Labels: needs-triage

#5067 Revert "Update dependencies from https://dev.azure.com/microsoft/Lift…
  eng/Version.Details.xml
Labels: needs-triage

#5070 Removing terminal velocity from CameraCaptureUI
  dev/Common/TerminalVelocityFeatures-CameraCaptureUI.xml
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.h
  dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.idl
  test/CameraCaptureUITests/APITests.cpp
Labels: needs-triage

#5074 Setting BackgroundTask API as AlwaysEnabled
  dev/Common/TerminalVelocityFeatures-BackgroundTask.xml
Labels: needs-triage

#5072 Remove terminal velocity feature tag from OAuth2Manager APIs, enabling for stable release
  dev/Common/TerminalVelocityFeatures-OAuth.xml
  dev/OAuth/AuthRequestParams.cpp
  dev/OAuth/ClientAuthentication.cpp
  dev/OAuth/OAuth.idl
  dev/OAuth/OAuth2Manager.cpp
  dev/OAuth/TokenRequestParams.cpp
  dev/OAuth/common.h
  test/OAuth2ManagerTests/OAuth2APITests.cpp
Labels: needs-triage

#5078 Update IXP in hardcoded packages.config
  Directory.Packages.props
  dev/WindowsAppRuntime_DLL/packages.config
  test/CameraCaptureUITests/packages.config
  test/OAuth2ManagerTests/packages.config
  test/PackageManager/API/packages.config
Labels: needs-triage

#5075 CameraCaptureUI: Onboarding Unit tests to the pipeline test runs
  test/CameraCaptureUITests/APITests.cpp
  test/CameraCaptureUITests/CameraCaptureUI.testdef
  test/CameraCaptureUITests/CameraCaptureUITests.vcxproj
Labels: needs-triage

#5080 Fix DownloadPipelineArtifacts Failing With System.OutOfMemoryException on Arm64 Testjobs
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
Labels: needs-triage

#5084 Fix DownloadPipelineArtifacts Failing With System.OutOfMemoryException on Arm64 Testjobs; Update Install-WindowsSdkISO.ps1 to use new FW links
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
  build/scripts/Install-WindowsSdkISO.ps1
Labels: needs-triage

#5083 Fix DownloadPipelineArtifacts Failing With System.OutOfMemoryException on Arm64 Testjobs; Update Install-WindowsSdkISO.ps1 to use new FW links
  build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
  build/scripts/Install-WindowsSdkISO.ps1
Labels: needs-triage

#5087 Remove terminal velocity feature tag from Badge Notification APIs, enabling it for stable release
  dev/Common/TerminalVelocityFeatures-BadgeNotifications.xml
  dev/Notifications/BadgeNotifications/BadgeNotifications.idl
Labels: needs-triage

#5089 Remove terminal velocity feature tag from Badge Notification APIs, enabling it for stable release
  dev/Common/TerminalVelocityFeatures-BadgeNotifications.xml
  dev/Notifications/BadgeNotifications/BadgeNotifications.idl
Labels: needs-triage

#5091 Adding IXP & FrameworkUDK to Central Package Management
  Directory.Packages.props
  dev/WindowsAppRuntime_DLL/packages.config
  test/CameraCaptureUITests/packages.config
  test/OAuth2ManagerTests/packages.config
  test/PackageManager/API/packages.config
Labels: needs-triage

#4966 App-configurable compatibility options spec: RuntimeCompatibilityOptions
  specs/Compatibility/RuntimeCompatibilityOptions.md
Labels: needs-triage

#5093 Adding IXP & FrameworkUDK to Central Package Management
  Directory.Packages.props
  dev/WindowsAppRuntime_DLL/packages.config
  test/CameraCaptureUITests/packages.config
  test/OAuth2ManagerTests/packages.config
  test/PackageManager/API/packages.config
Labels: needs-triage
